// Consolidated full-text terms, rendered as nine complete language blocks one
// after another in a single document.
//
// This file is deliberately NOT part of the i18n bundle. The three other member
// documents are machine-translated by scripts/sync-member-locales-local.mjs;
// binding legal wording must not be rewritten by a compact local model, so every
// language here is authored and stays put.
//
// Every clause restates something the system actually does — the source of truth
// is TermsPage.jsx, PrivacyPolicyPage.jsx and memberDocs.js. Do not add a promise
// the product does not keep.
const CONTACT = "contact@hugowishpax.studio";

export const LEGAL_LANGUAGES = [
  { code: "vi", name: "Tiếng Việt", htmlLang: "vi" },
  { code: "en", name: "English", htmlLang: "en" },
  { code: "zh", name: "中文", htmlLang: "zh-CN" },
  { code: "th", name: "ไทย", htmlLang: "th" },
  { code: "ja", name: "日本語", htmlLang: "ja" },
  { code: "ko", name: "한국어", htmlLang: "ko" },
  { code: "id", name: "Bahasa Indonesia", htmlLang: "id" },
  { code: "es", name: "Español", htmlLang: "es" },
  { code: "fr", name: "Français", htmlLang: "fr" },
];

export const LEGAL_FULL_TEXT = {
  vi: {
    title: "Điều khoản toàn văn",
    intro: "Bản hợp nhất của Điều khoản sử dụng, Chính sách bảo mật và quy tắc thành viên. Bản tiếng Việt là bản gốc; các ngôn ngữ sau là bản dịch tham khảo.",
    sections: [
      {
        id: "scope",
        title: "Điều 1 — Phạm vi áp dụng",
        items: [
          "Hugo Studio là sản phẩm cá nhân do Lê Gia Huy vận hành, gồm trang công khai, khu vực thành viên, ứng dụng và các tiện ích đi kèm.",
          "Khi tạo tài khoản hoặc tiếp tục sử dụng sau khi được cung cấp điều khoản, bạn xác nhận đã đọc và đồng ý với phần áp dụng cho mình.",
          "Chính sách bảo mật là một phần không tách rời của điều khoản này.",
          "Điều khoản riêng của Google, PayOS, ngân hàng và các bên thứ ba khác vẫn ràng buộc bạn khi bạn dùng phần tính năng kết nối tới họ.",
          "Nếu một quyền lợi có nhiều cách hiểu hợp lý, cách hiểu có lợi hơn cho thành viên được ưu tiên trong phạm vi pháp luật cho phép.",
        ],
      },
      {
        id: "age",
        title: "Điều 2 — Tài khoản và độ tuổi",
        items: [
          "Người dưới 14 tuổi được xem nội dung công khai nhưng không được tạo hoặc sử dụng tài khoản thành viên.",
          "Từ đủ 14 đến dưới 16 tuổi: cha mẹ hoặc người giám hộ phải đọc Chính sách bảo mật và đồng ý trước khi tài khoản tiếp tục xử lý dữ liệu. Hệ thống ghi lại thời điểm xác nhận và không đòi giấy tờ tuỳ thân chỉ để chứng minh tuổi.",
          "Từ đủ 16 đến dưới 18 tuổi: dùng được tính năng thành viên thông thường; tính năng 18+, giao dịch và thoả thuận cần năng lực hành vi đầy đủ vẫn bị giới hạn.",
          "Từ 18 tuổi: tính năng người lớn có thể mở sau khi khai đủ ngày tháng năm sinh và đáp ứng điều kiện riêng của từng tính năng.",
          "Mỗi người dùng một tài khoản chính. Tài khoản phụ lập ra để thao túng lượt giới thiệu, JOY, thành tích hay quyền lợi có thể bị gộp, thu hồi quyền lợi hoặc khoá.",
          "Ngày sinh được khoá sau lần khai đầu để bảo vệ cổng tuổi; bạn vẫn có quyền yêu cầu sửa sai sau bước xác minh hợp lý.",
          "Khi có căn cứ cho thấy tài khoản dưới 14 tuổi hoặc thiếu xác nhận cần thiết, Hugo Studio có thể tạm ngừng xử lý để xác minh, sau đó xoá hoặc hạn chế dữ liệu theo pháp luật.",
        ],
      },
      {
        id: "tiers",
        title: "Điều 3 — Hạng thẻ và đặc quyền",
        items: [
          "Hạng thẻ thành viên tính theo số người đăng ký thành công bằng mã giới thiệu của bạn. Một lượt chỉ được tính khi một thành viên mới thật sự tạo tài khoản và nhập mã của bạn.",
          "Mỗi tài khoản chỉ được nhập một mã giới thiệu, tại bước đăng ký ban đầu. Lập thêm tài khoản để tự dùng mã của mình là gian lận và có thể bị thu hồi JOY cùng quyền lợi liên quan.",
          "Đặc quyền đã cấp hợp lệ được ghi vào tài khoản; bạn xem được trạng thái, hạn dùng và điều kiện trước khi sử dụng.",
          "Nếu Hugo Studio thay đổi cơ cấu hạng, cơ cấu mới áp dụng cho tương lai. Quyền lợi hợp lệ chưa hết hạn vẫn giữ theo điều kiện hiển thị lúc cấp, trừ khi phát sinh từ lỗi hệ thống, gian lận hoặc pháp luật yêu cầu khác.",
          "Nếu một quyền lợi không còn khả năng cung cấp vì tính năng đã dừng, Hugo Studio có thể thay bằng quyền lợi tương đương về giá trị sử dụng và báo trước cho thành viên.",
          "Quyền lợi chưa dùng không quy đổi thành tiền mặt: JOY, voucher và thời gian truy cập là lợi ích nội bộ, không phải tiền gửi hay khoản đầu tư.",
        ],
      },
      {
        id: "star",
        title: "Điều 4 — Hạng Star và quà sinh nhật",
        items: [
          "Hạng Star được tính từ ngày sinh mỗi lần đọc và không lưu cố định. Star-14 tự thành Star-18 vào sinh nhật thứ 18.",
          "Star-14 (14 đến dưới 18 tuổi): thêm 15 ngày truy cập tài khoản.",
          "Star-18 (từ 18 tuổi): thêm 30 ngày, kèm voucher giảm 15% cho landing page hoặc website nhiều trang.",
          "Star-VIP (danh hiệu do Hugo Studio trao): thêm 90 ngày, kèm voucher 15% web tĩnh và 10% web động.",
          "Quà chỉ mở trong tháng sinh nhật, một lần mỗi năm, kèm một lượt quay may mắn.",
          "Cần khai đủ ngày, tháng và năm sinh; thiếu năm sinh thì hệ thống coi như chưa xác định tuổi.",
          "Voucher dịch vụ hết hạn sau 30 ngày kể từ khi cấp, dùng một lần và nên đưa ra khi trao đổi dự án.",
        ],
      },
      {
        id: "joy",
        title: "Điều 5 — Điểm JOY",
        items: [
          "JOY là điểm ghi nhận hoạt động bên trong Hugo Studio. JOY không phải tiền, không phải phương tiện thanh toán, không quy đổi ra tiền mặt và không rút về tài khoản ngân hàng.",
          "JOY không được mua bán hay chuyển nhượng ra ngoài hệ thống.",
          "JOY đến từ nhiệm vụ, điểm danh, trò chơi, giới thiệu và phần thưởng hệ thống. Mọi lần cộng và trừ đều được ghi vào lịch sử ví.",
          "Chuyển JOY cho người khác cần mã PIN giao dịch sáu chữ số, thiết lập trong ví.",
          "Điểm phát sinh từ lỗi kỹ thuật, khai thác lỗi hoặc công cụ tự động có thể bị điều chỉnh về đúng trạng thái và tài khoản liên quan có thể bị khoá.",
          "Khi tài khoản bị xoá hoặc khi Hugo Studio ngừng hoạt động, số dư JOY chấm dứt và không phát sinh nghĩa vụ tài chính nào.",
        ],
      },
      {
        id: "content",
        title: "Điều 6 — Nội dung của bạn",
        items: [
          "Bạn giữ nguyên quyền tác giả với nội dung mình tạo: trang Bio, ảnh, bài viết cộng đồng, ghi chú.",
          "Bạn cấp cho Hugo Studio quyền lưu trữ, sao chép kỹ thuật và hiển thị nội dung đúng phạm vi bạn chọn, chỉ nhằm vận hành tính năng. Quyền này chấm dứt khi bạn xoá nội dung.",
          "Bạn cam kết có quyền với nội dung đã đăng: ảnh do bạn chụp hoặc được cấp phép, chữ do bạn viết, nhạc và phông chữ có giấy phép hợp lệ.",
          "Hugo Studio không dùng nội dung riêng tư của bạn để huấn luyện mô hình AI riêng.",
          "Trang Bio là nội dung công khai: bất kỳ ai có đường dẫn đều xem được. Hãy cân nhắc trước khi đăng ảnh có mặt người khác, thông tin trường lớp, số điện thoại hoặc địa chỉ.",
          "Báo cáo vi phạm bản quyền gửi tới " + CONTACT + " với tiêu đề bắt đầu bằng “[Bản quyền]”. Hugo Studio xác nhận đã nhận trong 3 ngày làm việc và xử lý trong 10 ngày làm việc kể từ khi nhận đủ thông tin.",
        ],
      },
      {
        id: "data",
        title: "Điều 7 — Dữ liệu cá nhân",
        items: [
          "Tài khoản: email, tên và ảnh đại diện từ Google; thời điểm đăng nhập; khoá công khai của thiết bị nếu bạn dùng WebAuthn.",
          "Hồ sơ và nội dung: Bio, liên kết, ảnh, ghi chú, nhật ký giấc ngủ và nội dung bạn chủ động tạo.",
          "HugoPSY và AI: câu hỏi, nội dung trò chuyện và bài tự đánh giá cần thiết để tạo câu trả lời. Bản lưu hội thoại HugoPSY trong cơ sở dữ liệu được mã hoá.",
          "JOY và hoạt động: số dư, lịch sử thay đổi, điểm game, tiến độ học, ván cờ và thành tích.",
          "Đặt lịch và Donate: tên, email, nội dung yêu cầu, số tiền, mã giao dịch và trạng thái PayOS trả về.",
          "Thiết bị và vận hành: loại thiết bị, đường dẫn, lỗi kỹ thuật, chỉ số tốc độ; địa chỉ mạng có thể được xử lý để chống lạm dụng.",
          "Hugo Studio không thấy mật khẩu Google, mật khẩu ngân hàng hay mã OTP của bạn, không nhận vân tay hoặc dữ liệu khuôn mặt, và không quay lại phiên truy cập.",
          "Hạ tầng và dịch vụ được dùng (Google, MongoDB Atlas, Cloudinary, Pinecone, SendGrid, Render, Vercel, Cloudflare) đặt máy chủ ở nhiều quốc gia, nên dữ liệu tương ứng có thể được truyền và lưu ngoài Việt Nam.",
          "Thời gian lưu dự kiến: thông báo trong ứng dụng khoảng 90 ngày; trạng thái tạm chưa hoàn tất khoảng 30 ngày; nhật ký lỗi thường không quá 30 ngày; tài khoản và nội dung giữ đến khi bạn xoá.",
        ],
      },
      {
        id: "rights",
        title: "Điều 8 — Quyền dữ liệu và cách thực hiện",
        items: [
          "Bạn có quyền được biết, đồng ý hoặc từ chối, xem và chỉnh sửa, nhận bản sao, xoá hoặc hạn chế xử lý, rút lại sự đồng ý, phản đối xử lý, khiếu nại và yêu cầu bồi thường theo pháp luật.",
          "Gửi yêu cầu từ email tài khoản tới " + CONTACT + ", nêu quyền muốn thực hiện và phạm vi dữ liệu liên quan.",
          "Hugo Studio xác minh bạn là chủ thể dữ liệu hoặc người đại diện hợp pháp, chỉ hỏi thông tin ở mức cần thiết để ngăn mạo danh.",
          "Yêu cầu hợp lệ được phản hồi ban đầu trong 02 ngày làm việc. Thời gian thực hiện thông thường là 15 ngày; trường hợp phức tạp hoặc cần phối hợp bên thứ ba có thể cần 20–30 ngày theo quy định hiện hành.",
          "Thực hiện quyền dữ liệu không làm bạn mất quyền lợi khác. Nếu dữ liệu là điều kiện kỹ thuật bắt buộc của một tính năng, việc xoá chỉ khiến đúng tính năng đó ngừng hoạt động.",
          "Hugo Studio chỉ giữ lại dữ liệu sau yêu cầu xoá khi có căn cứ pháp luật, nghĩa vụ đối soát, tranh chấp hoặc quyền của người khác; phần bị giữ được hạn chế sử dụng đúng mục đích đó.",
        ],
      },
      {
        id: "permissions",
        title: "Điều 9 — Quyền trên thiết bị",
        items: [
          "Thông báo: chỉ dùng khi bạn bật nhắc việc và cập nhật tài khoản. Từ chối thì tài khoản vẫn chạy bình thường, chỉ không có thông báo đẩy.",
          "Vị trí: chỉ dùng khi bạn bật thời tiết, tính năng theo vị trí hoặc bảo vệ đăng nhập theo vị trí. Từ chối thì tính năng đó không chạy hoặc dùng dữ liệu mặc định.",
          "Camera: chỉ dùng khi bạn chọn quét mã QR hoặc chụp ảnh. Từ chối thì bạn có thể nhập tay hoặc chọn tệp ở nơi tính năng hỗ trợ.",
          "Micro: chỉ dùng khi bạn chọn tính năng nhập âm thanh. Từ chối thì bạn tiếp tục nhập bằng chữ.",
          "Sinh trắc học: thiết bị tự xác nhận đăng nhập passkey. Hugo Studio không nhận vân tay hay dữ liệu khuôn mặt của bạn.",
          "Từ chối một quyền tuỳ chọn chỉ tắt đúng tính năng cần nó. Hugo Studio không hạ hạng thẻ, không trừ JOY và không chặn tính năng không liên quan chỉ vì bạn từ chối quyền thiết bị.",
        ],
      },
      {
        id: "ai",
        title: "Điều 10 — Giới hạn của AI và tính năng sức khoẻ",
        items: [
          "HugoPSY, bài tự đánh giá, theo dõi giấc ngủ và các phân tích sức khoẻ trong ứng dụng là công cụ tự ghi chép và tham khảo. Chúng không phải hoạt động khám bệnh, chữa bệnh và không thay thế chẩn đoán, đơn thuốc hay tư vấn của người có chuyên môn.",
          "Chỉ nội dung cần cho câu trả lời mới được gửi tới dịch vụ AI, khi bạn chủ động nhắn. Cách Google Gemini xử lý dữ liệu tại hạ tầng của Google tuân theo chính sách của Google.",
          "Nội dung do AI tạo ra có thể sai. Hãy kiểm chứng trước khi dùng cho việc học, việc làm hoặc quyết định quan trọng.",
          "Trong tình huống khẩn cấp, đừng chờ phản hồi của AI: hãy liên hệ người bạn tin tưởng, cơ sở y tế gần nhất hoặc dịch vụ hỗ trợ khẩn cấp nơi bạn đang ở.",
          "Giấy chứng nhận Study with Hugo ghi nhận tiến độ học trong ứng dụng; đây không phải văn bằng, chứng chỉ thuộc hệ thống giáo dục quốc dân.",
          "Radio chỉ mở đường dẫn phát sóng công khai và Bản tin hôm nay chỉ hiển thị tiêu đề, tóm tắt do toà soạn viết cùng liên kết về bài gốc; bản quyền nội dung thuộc về đơn vị phát hành.",
        ],
      },
      {
        id: "payment",
        title: "Điều 11 — Dịch vụ trả phí, đặt lịch và ủng hộ",
        items: [
          "Giá dịch vụ niêm yết trên trang Dịch vụ. Phạm vi công việc, thời gian và số lần chỉnh sửa được chốt bằng văn bản trước khi bắt đầu.",
          "Thanh toán xử lý qua PayOS và ngân hàng. Hugo Studio không lưu thông tin thẻ hay tài khoản ngân hàng của bạn, và không thể truy cập tài khoản ngân hàng của bạn.",
          "Khoản ủng hộ là tự nguyện, không phải giao dịch mua bán và không hoàn lại, trừ trường hợp giao dịch bị trùng hoặc sai số tiền do lỗi kỹ thuật. Ủng hộ không mở khoá tính năng và không ảnh hưởng tới báo giá hay quyền thành viên.",
          "Với dịch vụ đã đặt cọc: huỷ trước khi bắt đầu triển khai được hoàn phần chưa thực hiện; sau khi đã bàn giao bản nháp đầu tiên thì hoàn theo khối lượng còn lại.",
          "Khiếu nại giao dịch gửi tới " + CONTACT + " kèm mã đơn; Hugo Studio phản hồi trong 5 ngày làm việc.",
          "Vấn đề thuộc luồng thanh toán, ứng dụng ngân hàng hoặc dữ liệu PayOS cần xử lý qua kênh hỗ trợ chính thức của PayOS hoặc ngân hàng.",
        ],
      },
      {
        id: "suspension",
        title: "Điều 12 — Tạm ngưng, khiếu nại và trách nhiệm",
        items: [
          "Khi rủi ro không khẩn cấp, Hugo Studio ưu tiên cảnh báo hoặc hạn chế đúng tính năng liên quan trước khi khoá toàn bộ tài khoản. Trong tình huống khẩn cấp, hệ thống có thể chặn trước rồi xác minh sau để ngăn thiệt hại.",
          "Khi có thể thông báo, thành viên được biết nhóm lý do, phạm vi hạn chế, thời hạn dự kiến hoặc việc cần làm để được xem xét khôi phục, và có quyền gửi phản hồi từ email tài khoản tới " + CONTACT + ".",
          "Hugo Studio xem xét lại dựa trên nhật ký hệ thống, bằng chứng của hai bên và mức rủi ro; khôi phục quyền truy cập hoặc thu hẹp biện pháp khi căn cứ hạn chế không còn.",
          "Các tính năng cộng đồng miễn phí được cung cấp theo khả năng vận hành thực tế, không kèm cam kết hoạt động liên tục hay đạt một kết quả học tập, sức khoẻ, nghề nghiệp hoặc thu nhập cụ thể.",
          "Trong phạm vi pháp luật cho phép, Hugo Studio không chịu thiệt hại gián tiếp, lợi nhuận kỳ vọng, cơ hội bị mất hoặc hậu quả do bỏ qua cảnh báo, dùng sai hướng dẫn, cung cấp thông tin sai hay dựa vào nội dung AI cho quyết định quan trọng.",
          "Không nội dung nào ở đây loại trừ trách nhiệm bắt buộc về dữ liệu cá nhân, quyền lợi người tiêu dùng, lỗi cố ý, lỗi nghiêm trọng hoặc nghĩa vụ khác mà pháp luật không cho phép loại trừ.",
          "Điều khoản này được điều chỉnh bởi pháp luật Việt Nam. Tranh chấp trước hết giải quyết bằng thương lượng qua email; nếu không đạt kết quả, vụ việc thuộc thẩm quyền của toà án có thẩm quyền tại Việt Nam. Mọi câu hỏi gửi về " + CONTACT + ".",
        ],
      },
    ],
  },

  en: {
    title: "Full terms",
    intro: "A consolidated text of the Terms of Use, the Privacy Policy and the membership rules. The Vietnamese text is the original; the other languages are reference translations.",
    sections: [
      {
        id: "scope",
        title: "Article 1 — Scope",
        items: [
          "Hugo Studio is a personal product operated by Lê Gia Huy, comprising the public site, the member area, the app and the utilities that come with them.",
          "By creating an account, or by continuing to use the service after these terms are made available, you confirm that you have read and accept the parts that apply to you.",
          "The Privacy Policy forms an inseparable part of these terms.",
          "The separate terms of Google, PayOS, banks and other third parties continue to bind you whenever you use a feature connected to them.",
          "Where a benefit allows more than one reasonable reading, the reading more favourable to the member prevails to the extent the law permits.",
        ],
      },
      {
        id: "age",
        title: "Article 2 — Account and age",
        items: [
          "People under 14 may view public content but may not create or use a member account.",
          "Ages 14 to under 16: a parent or legal guardian must read the Privacy Policy and consent before the account continues processing personal data. The system records the time of confirmation and does not require an identity document solely to prove age.",
          "Ages 16 to under 18: ordinary member features are available; adult features, transactions and agreements requiring full legal capacity remain restricted.",
          "Age 18 and over: adult features may open once a complete date of birth is provided and each feature's own conditions are met.",
          "Each person uses one primary account. Additional accounts created to manipulate referrals, JOY, achievements or benefits may be consolidated, have benefits revoked, or be locked.",
          "Your date of birth is locked after first entry to protect the age gate; you may still request a correction after reasonable verification.",
          "Where there are grounds to believe an account belongs to someone under 14 or lacks the required consent, Hugo Studio may pause processing to verify, then delete or restrict the data as the law requires.",
        ],
      },
      {
        id: "tiers",
        title: "Article 3 — Card tiers and privileges",
        items: [
          "Your card tier is based on the number of people who sign up successfully with your referral code. A referral counts only when a genuine new member creates an account and enters your code.",
          "Each account may enter one referrer's code, during initial registration. Creating extra accounts to use your own code is fraud and may result in the related JOY and privileges being revoked.",
          "A validly issued privilege is recorded in your account; you can review its status, expiry and conditions before using it.",
          "If Hugo Studio changes the tier structure, the new structure applies prospectively. A valid, unexpired benefit remains available under the conditions shown when it was issued, unless it arose from a system error or fraud, or the law requires otherwise.",
          "If a benefit can no longer be provided because its feature has ended, Hugo Studio may replace it with a benefit of comparable practical value and will notify members beforehand.",
          "An unused benefit does not convert to cash: JOY, vouchers and access time are internal benefits, not deposits or investments.",
        ],
      },
      {
        id: "star",
        title: "Article 4 — Star tiers and birthday rewards",
        items: [
          "Your Star tier is calculated from your date of birth each time it is read and is not stored permanently. Star-14 becomes Star-18 on your 18th birthday.",
          "Star-14 (ages 14 to under 18): 15 additional days of account access.",
          "Star-18 (age 18 and over): 30 additional days, plus a 15% voucher for a landing page or a multi-page website.",
          "Star-VIP (an honorary status granted by Hugo Studio): 90 additional days, plus a 15% static-web voucher and a 10% dynamic-web-app voucher.",
          "The reward opens only during your birthday month, once a year, and includes one lucky spin.",
          "A complete day, month and year of birth is required; without the year the system treats your age as unknown.",
          "Service vouchers expire 30 days after issue, may be used once, and should be presented when discussing your project.",
        ],
      },
      {
        id: "joy",
        title: "Article 5 — JOY points",
        items: [
          "JOY records activity inside Hugo Studio. It is not money, not a means of payment, cannot be converted to cash and cannot be withdrawn to a bank account.",
          "JOY may not be bought, sold or transferred outside the system.",
          "JOY comes from missions, check-ins, games, referrals and system rewards. Every credit and debit is written to your wallet history.",
          "Sending JOY to another person requires a six-digit transaction PIN, which you set in the wallet.",
          "Points arising from a technical error, error exploitation or automated tools may be corrected back to the accurate balance, and the account involved may be locked.",
          "When an account is deleted, or if Hugo Studio ceases operation, the JOY balance ends and no financial obligation arises from it.",
        ],
      },
      {
        id: "content",
        title: "Article 6 — Your content",
        items: [
          "You keep authorship of what you create: your Bio page, photos, community posts and notes.",
          "You grant Hugo Studio the right to store, technically copy and display that content within the scope you choose, solely to operate the feature. That right ends when you delete the content.",
          "You confirm you hold the rights to what you publish: photos you took or are licensed to use, text you wrote, and music and fonts with valid licences.",
          "Hugo Studio does not use your private content to train its own AI models.",
          "A Bio page is public content: anyone with the link can view it. Consider carefully before publishing photos of other people, school details, phone numbers or addresses.",
          "Report copyright infringement to " + CONTACT + " with a subject line beginning “[Copyright]”. Hugo Studio acknowledges receipt within 3 working days and resolves the matter within 10 working days of receiving complete information.",
        ],
      },
      {
        id: "data",
        title: "Article 7 — Personal data",
        items: [
          "Account: email, name and avatar from Google; sign-in times; your device's public key if you use WebAuthn.",
          "Profile and content: Bio, links, photos, notes, sleep journal and anything you actively create.",
          "HugoPSY and AI: the questions, conversation content and self-assessments needed to produce a reply. Stored HugoPSY conversations are encrypted in the database.",
          "JOY and activity: balance, change history, game scores, learning progress, chess games and achievements.",
          "Booking and donations: name, email, request details, amount, transaction code and the status PayOS returns.",
          "Device and operations: device type, paths, technical errors and performance metrics; network address may be processed to prevent abuse.",
          "Hugo Studio never sees your Google password, banking password or OTP, never receives your fingerprint or face data, and does not record your session.",
          "The infrastructure and services in use (Google, MongoDB Atlas, Cloudinary, Pinecone, SendGrid, Render, Vercel, Cloudflare) host servers in several countries, so the corresponding data may be transferred and stored outside Vietnam.",
          "Expected retention: in-app notifications about 90 days; incomplete temporary states about 30 days; error logs usually no more than 30 days; account and content until you delete them.",
        ],
      },
      {
        id: "rights",
        title: "Article 8 — Your data rights and how to exercise them",
        items: [
          "You have the right to be informed, to consent or refuse, to view and correct, to obtain a copy, to delete or restrict processing, to withdraw consent, to object, to complain and to seek compensation as provided by law.",
          "Send your request from the account email to " + CONTACT + ", stating the right you wish to exercise and the data it concerns.",
          "Hugo Studio verifies that you are the data subject or a lawful representative, asking only for what is needed to prevent impersonation.",
          "A valid request receives an initial response within 02 working days. The usual processing time is 15 days; complex requests, or those needing third-party cooperation, may take 20–30 days under current requirements.",
          "Exercising a data right does not cost you other benefits. Where data is a technical precondition of a feature, deleting it stops only that feature.",
          "Hugo Studio keeps data after a deletion request only where the law, a reconciliation duty, a dispute or another person's rights require it, and restricts the retained part to that purpose.",
        ],
      },
      {
        id: "permissions",
        title: "Article 9 — Device permissions",
        items: [
          "Notifications: used only when you enable reminders and account updates. Decline and your account still works; push alerts are simply unavailable.",
          "Location: used only when you enable weather, location features or location-based sign-in protection. Decline and the feature is unavailable or uses default data.",
          "Camera: used only when you choose to scan a QR code or capture an image. Decline and you may type or pick a file where the feature offers that.",
          "Microphone: used only when you choose a supported audio-input feature. Decline and you continue with text.",
          "Biometrics: your device confirms a passkey sign-in. Hugo Studio does not receive your fingerprint or face template.",
          "Declining an optional permission disables only the feature that needs it. Hugo Studio will not lower your card tier, deduct JOY or block unrelated features because you declined.",
        ],
      },
      {
        id: "ai",
        title: "Article 10 — Limits of AI and health features",
        items: [
          "HugoPSY, self-assessments, sleep tracking and the in-app health analyses are self-journalling and reference tools. They are not medical examination or treatment and do not replace a diagnosis, prescription or professional advice.",
          "Only the content needed for a reply is sent to the AI service, and only when you actively send a message. How Google Gemini processes data on Google's infrastructure follows Google's own policies.",
          "AI-generated content can be wrong. Verify it before relying on it for study, work or an important decision.",
          "In an emergency, do not wait for an AI reply: contact someone you trust, the nearest medical facility, or the emergency support service where you are.",
          "A Study with Hugo certificate records progress inside the app; it is not a diploma or certificate within the national education system.",
          "Radio only opens public broadcast streams, and Today only shows headlines, the publisher's own summary and a link to the original article; copyright in that content belongs to the publisher.",
        ],
      },
      {
        id: "payment",
        title: "Article 11 — Paid services, booking and donations",
        items: [
          "Service prices are listed on the Services page. Scope, timeline and the number of revision rounds are agreed in writing before work starts.",
          "Payments are processed through PayOS and banks. Hugo Studio does not store your card or bank account details and cannot access your bank account.",
          "A donation is voluntary, is not a purchase and is not refundable, except for a duplicate transaction or a wrong amount caused by a technical error. Donating does not unlock features and does not affect quotations or membership rights.",
          "For a service with a deposit: cancelling before work begins refunds the part not yet performed; after the first draft is delivered, the refund follows the volume of work remaining.",
          "Send transaction complaints to " + CONTACT + " with the order code; Hugo Studio replies within 5 working days.",
          "Issues within the payment flow, the banking app or PayOS data must be handled through the official support channels of PayOS or your bank.",
        ],
      },
      {
        id: "suspension",
        title: "Article 12 — Suspension, review and responsibility",
        items: [
          "Where the risk is not urgent, Hugo Studio prefers a warning or a restriction on the specific feature before locking a whole account. In an emergency the system may block first and verify afterwards to prevent harm.",
          "Where notice can be given, the member is told the general reason, the scope of the restriction, the expected duration or what is needed for a restoration review, and may reply from the account email to " + CONTACT + ".",
          "Hugo Studio reconsiders using system logs, evidence from both sides and the level of risk, and restores access or narrows the measure once the basis for the restriction no longer applies.",
          "Free community features are provided according to actual operating capacity, with no promise of uninterrupted availability or of a particular educational, health, career or income outcome.",
          "To the extent the law permits, Hugo Studio is not liable for indirect loss, expected profit, lost opportunity, or consequences of ignoring a warning, misusing a feature, supplying inaccurate information or relying on AI content for an important decision.",
          "Nothing here excludes mandatory responsibility for personal-data protection, consumer rights, intentional or gross fault, or any other obligation the law does not allow to be excluded.",
          "These terms are governed by the law of Vietnam. Disputes are first addressed by negotiation over email; failing that, they fall to the competent court in Vietnam. Questions go to " + CONTACT + ".",
        ],
      },
    ],
  },

  zh: {
    title: "条款全文",
    intro: "《使用条款》《隐私政策》与会员规则的合并文本。越南语版本为原始版本，其他语言为参考译文。",
    sections: [
      {
        id: "scope",
        title: "第一条 — 适用范围",
        items: [
          "Hugo Studio 是由 Lê Gia Huy 运营的个人产品，包括公开网站、会员区、应用程序及随附的各项工具。",
          "创建账户，或在本条款提供后继续使用服务，即表示你已阅读并接受其中适用于你的部分。",
          "《隐私政策》是本条款不可分割的组成部分。",
          "当你使用与 Google、PayOS、银行及其他第三方相连的功能时，其各自的条款依然对你具有约束力。",
          "同一项权益若存在多种合理解释，在法律允许的范围内，以对会员更有利的解释为准。",
        ],
      },
      {
        id: "age",
        title: "第二条 — 账户与年龄",
        items: [
          "未满 14 周岁者可浏览公开内容，但不得创建或使用会员账户。",
          "已满 14 周岁未满 16 周岁：须由父母或法定监护人阅读《隐私政策》并表示同意，账户方可继续处理个人数据。系统记录确认时间，且不会仅为证明年龄而索取身份证件。",
          "已满 16 周岁未满 18 周岁：可使用普通会员功能；成人功能、交易以及需要完全民事行为能力的协议仍受限制。",
          "已满 18 周岁：在填写完整出生日期并满足各功能自身条件后，成人功能方可开放。",
          "每人使用一个主账户。为操纵推荐数、JOY、成就或权益而开设的额外账户，可能被合并、撤销权益或封锁。",
          "出生日期首次填写后即锁定，以保护年龄门槛；经合理核验后，你仍有权申请更正。",
          "若有依据表明账户属于未满 14 周岁者或缺少必要同意，Hugo Studio 可暂停处理以进行核验，随后依法删除或限制相关数据。",
        ],
      },
      {
        id: "tiers",
        title: "第三条 — 卡等级与特权",
        items: [
          "会员卡等级依据使用你的推荐码成功注册的人数计算。只有真实的新会员创建账户并填入你的推荐码，该次推荐才计入。",
          "每个账户仅可在初次注册时填写一个推荐人代码。开设额外账户以使用自己的推荐码属于欺诈，相关 JOY 与特权可能被撤销。",
          "有效发放的特权会记录在你的账户中；使用前你可查看其状态、有效期与条件。",
          "若 Hugo Studio 调整等级结构，新结构自调整之日起适用。有效且未过期的权益仍按发放时显示的条件保留，因系统错误、欺诈或法律另有要求的除外。",
          "若某项权益因功能停止而无法继续提供，Hugo Studio 可以实际使用价值相当的权益替代，并事先通知会员。",
          "未使用的权益不折算为现金：JOY、代金券与访问时长属于内部权益，并非存款或投资。",
        ],
      },
      {
        id: "star",
        title: "第四条 — Star 等级与生日奖励",
        items: [
          "Star 等级在每次读取时依据出生日期计算，不作长期存储。Star-14 于 18 周岁生日当日自动成为 Star-18。",
          "Star-14（14 周岁至未满 18 周岁）：额外获得 15 天账户访问时长。",
          "Star-18（已满 18 周岁）：额外获得 30 天，并附落地页或多页网站 15% 折扣券。",
          "Star-VIP（由 Hugo Studio 授予的荣誉身份）：额外获得 90 天，并附静态网站 15% 折扣券与动态网页应用 10% 折扣券。",
          "奖励仅在你的生日当月开放，每年一次，并包含一次幸运抽奖。",
          "须填写完整的出生年、月、日；缺少年份时，系统视为年龄未确定。",
          "服务折扣券自发放起 30 天内有效，限用一次，建议在洽谈项目时出示。",
        ],
      },
      {
        id: "joy",
        title: "第五条 — JOY 积分",
        items: [
          "JOY 用于记录你在 Hugo Studio 内部的活动。它不是货币、不是支付工具，不可兑换现金，也不可提取至银行账户。",
          "JOY 不得买卖，也不得转让至系统之外。",
          "JOY 来自任务、签到、游戏、推荐与系统奖励。每一笔增减都会写入钱包记录。",
          "向他人转赠 JOY 需要在钱包中设置的六位交易 PIN 码。",
          "因技术错误、利用漏洞或自动化工具产生的积分，可被更正为正确余额，相关账户可能被封锁。",
          "账户被删除时，或 Hugo Studio 停止运营时，JOY 余额即告终止，且不因此产生任何财务义务。",
        ],
      },
      {
        id: "content",
        title: "第六条 — 你的内容",
        items: [
          "你保留自己所创作内容的著作权：Bio 页面、照片、社区帖子与笔记。",
          "你授予 Hugo Studio 在你所选范围内存储、进行技术性复制并展示该内容的权利，且仅用于运行相应功能。该权利在你删除内容时终止。",
          "你确认对所发布内容拥有权利：由你拍摄或获得许可的照片、你撰写的文字，以及具有有效许可的音乐与字体。",
          "Hugo Studio 不会使用你的私密内容训练自有 AI 模型。",
          "Bio 页面属于公开内容：任何拥有链接的人都可查看。发布他人肖像、学校信息、电话号码或住址前请审慎考虑。",
          "著作权侵权举报请发送至 " + CONTACT + "，主题以“[Copyright]”开头。Hugo Studio 将在 3 个工作日内确认收到，并在收齐信息后 10 个工作日内处理完毕。",
        ],
      },
      {
        id: "data",
        title: "第七条 — 个人数据",
        items: [
          "账户：来自 Google 的电子邮箱、姓名与头像；登录时间；使用 WebAuthn 时的设备公钥。",
          "资料与内容：Bio、链接、照片、笔记、睡眠日志以及你主动创建的内容。",
          "HugoPSY 与 AI：生成回复所需的提问、对话内容与自评结果。数据库中保存的 HugoPSY 对话经过加密。",
          "JOY 与活动：余额、变动记录、游戏得分、学习进度、棋局与成就。",
          "预约与捐助：姓名、电子邮箱、需求内容、金额、交易编号以及 PayOS 返回的状态。",
          "设备与运行：设备类型、访问路径、技术错误与性能指标；网络地址可能被用于防止滥用。",
          "Hugo Studio 绝不会看到你的 Google 密码、网银密码或 OTP，不会接收你的指纹或面部数据，也不会录制你的访问会话。",
          "所使用的基础设施与服务（Google、MongoDB Atlas、Cloudinary、Pinecone、SendGrid、Render、Vercel、Cloudflare）在多个国家设有服务器，因此相应数据可能被传输并存储于越南境外。",
          "预计留存期限：应用内通知约 90 天；未完成的临时状态约 30 天；错误日志通常不超过 30 天；账户与内容保留至你删除为止。",
        ],
      },
      {
        id: "rights",
        title: "第八条 — 你的数据权利及行使方式",
        items: [
          "你依法享有知情权、同意或拒绝权、查阅与更正权、获取副本权、删除或限制处理权、撤回同意权、反对处理权、投诉权以及请求赔偿的权利。",
          "请从账户邮箱发送请求至 " + CONTACT + "，写明拟行使的权利以及所涉数据范围。",
          "Hugo Studio 会核验你是数据主体或合法代理人，且仅索取为防止冒名所必需的信息。",
          "有效请求将在 02 个工作日内获得初步回复。通常处理时间为 15 天；复杂请求或需第三方配合的请求，依现行规定可能需要 20–30 天。",
          "行使数据权利不会使你丧失其他权益。若某项数据是某功能的必要技术前提，删除该数据仅会使该功能停止运行。",
          "仅在法律、对账义务、争议或他人权利有此要求时，Hugo Studio 才会在收到删除请求后继续保留数据，且保留部分仅限用于该目的。",
        ],
      },
      {
        id: "permissions",
        title: "第九条 — 设备权限",
        items: [
          "通知：仅在你开启提醒与账户动态时使用。拒绝后账户照常运行，只是无法收到推送。",
          "位置：仅在你开启天气、位置相关功能或基于位置的登录保护时使用。拒绝后该功能不可用或改用默认数据。",
          "相机：仅在你选择扫描二维码或拍摄图像时使用。拒绝后，在功能支持的情况下你可手动输入或选择文件。",
          "麦克风：仅在你选择支持语音输入的功能时使用。拒绝后你可继续使用文字输入。",
          "生物识别：由你的设备确认 passkey 登录。Hugo Studio 不会接收你的指纹或面部模板。",
          "拒绝可选权限只会关闭需要该权限的那一项功能。Hugo Studio 不会因你拒绝而降低卡等级、扣除 JOY 或封锁无关功能。",
        ],
      },
      {
        id: "ai",
        title: "第十条 — AI 与健康功能的限度",
        items: [
          "HugoPSY、自评量表、睡眠追踪及应用内的健康分析均为自我记录与参考工具。它们不属于诊疗行为，不能替代诊断、处方或专业人士的建议。",
          "只有生成回复所必需的内容才会发送至 AI 服务，且仅在你主动发送消息时。Google Gemini 在其自有基础设施上处理数据的方式，遵循 Google 的政策。",
          "AI 生成的内容可能出错。用于学习、工作或重要决策前请自行核实。",
          "遇到紧急情况请勿等待 AI 回复：请联系你信任的人、就近的医疗机构，或你所在地的紧急支援服务。",
          "Study with Hugo 证书仅记录你在应用内的学习进度；它不是国民教育体系内的文凭或证书。",
          "Radio 仅打开公开的广播流，“今日”仅显示标题、媒体自撰的摘要及原文链接；相关内容的著作权归发布方所有。",
        ],
      },
      {
        id: "payment",
        title: "第十一条 — 付费服务、预约与捐助",
        items: [
          "服务价格公示于「服务」页面。工作范围、时间与修改轮次在开始前以书面方式确定。",
          "支付通过 PayOS 与银行处理。Hugo Studio 不存储你的银行卡或银行账户信息，也无法访问你的银行账户。",
          "捐助属自愿行为，并非买卖交易，且不予退还；因技术错误导致的重复交易或金额有误除外。捐助不会解锁功能，也不影响报价或会员权益。",
          "已支付定金的服务：在开始实施前取消，退还尚未执行的部分；交付第一版草稿之后，按剩余工作量退还。",
          "交易投诉请连同订单编号发送至 " + CONTACT + "；Hugo Studio 将在 5 个工作日内回复。",
          "属于支付流程、银行应用或 PayOS 数据的问题，须通过 PayOS 或银行的官方支持渠道处理。",
        ],
      },
      {
        id: "suspension",
        title: "第十二条 — 暂停、申诉与责任",
        items: [
          "风险并不紧急时，Hugo Studio 优先采取警示或仅限制相关功能，而非直接封锁整个账户。紧急情况下，系统可先行拦截、事后核验，以防止损害扩大。",
          "在能够通知的情况下，会员将获知大致原因、限制范围、预计期限或申请恢复所需的步骤，并可从账户邮箱回复至 " + CONTACT + "。",
          "Hugo Studio 将依据系统日志、双方证据与风险程度重新审查；限制依据不复存在时，即恢复访问权限或缩小措施范围。",
          "免费社区功能按实际运营能力提供，不承诺不间断可用，也不承诺达成特定的学习、健康、职业或收入结果。",
          "在法律允许的范围内，对于间接损失、预期利润、错失机会，以及因忽视警示、误用功能、提供不实信息或依赖 AI 内容作出重要决策而产生的后果，Hugo Studio 不承担责任。",
          "本文任何内容均不排除在个人数据保护、消费者权益、故意或重大过失方面的强制性责任，也不排除法律不允许排除的其他义务。",
          "本条款适用越南法律。争议先通过电子邮件协商解决；协商不成的，由越南有管辖权的法院管辖。如有疑问请联系 " + CONTACT + "。",
        ],
      },
    ],
  },

  th: {
    title: "ข้อกำหนดฉบับเต็ม",
    intro: "ฉบับรวมของข้อกำหนดการใช้งาน นโยบายความเป็นส่วนตัว และกฎของสมาชิก ฉบับภาษาเวียดนามเป็นฉบับต้นทาง ภาษาอื่นเป็นคำแปลเพื่ออ้างอิง",
    sections: [
      {
        id: "scope",
        title: "ข้อ 1 — ขอบเขตการใช้บังคับ",
        items: [
          "Hugo Studio เป็นผลิตภัณฑ์ส่วนบุคคลที่ดำเนินการโดย Lê Gia Huy ประกอบด้วยเว็บไซต์สาธารณะ พื้นที่สมาชิก แอปพลิเคชัน และเครื่องมือที่มาพร้อมกัน",
          "การสร้างบัญชี หรือการใช้บริการต่อหลังจากได้รับข้อกำหนดนี้ ถือว่าคุณได้อ่านและยอมรับส่วนที่ใช้บังคับกับคุณแล้ว",
          "นโยบายความเป็นส่วนตัวเป็นส่วนหนึ่งที่แยกไม่ได้จากข้อกำหนดนี้",
          "ข้อกำหนดเฉพาะของ Google, PayOS, ธนาคาร และบุคคลภายนอกอื่น ยังคงผูกพันคุณเมื่อคุณใช้ฟีเจอร์ที่เชื่อมต่อกับพวกเขา",
          "หากสิทธิประโยชน์หนึ่งตีความได้อย่างสมเหตุสมผลมากกว่าหนึ่งทาง ให้ถือการตีความที่เป็นคุณแก่สมาชิกมากกว่า เท่าที่กฎหมายอนุญาต",
        ],
      },
      {
        id: "age",
        title: "ข้อ 2 — บัญชีและอายุ",
        items: [
          "ผู้มีอายุต่ำกว่า 14 ปี ดูเนื้อหาสาธารณะได้ แต่สร้างหรือใช้บัญชีสมาชิกไม่ได้",
          "อายุ 14 ปีถึงต่ำกว่า 16 ปี: บิดามารดาหรือผู้ปกครองตามกฎหมายต้องอ่านนโยบายความเป็นส่วนตัวและให้ความยินยอมก่อน บัญชีจึงจะประมวลผลข้อมูลส่วนบุคคลต่อได้ ระบบบันทึกเวลาที่ยืนยัน และไม่เรียกเอกสารแสดงตนเพียงเพื่อพิสูจน์อายุ",
          "อายุ 16 ปีถึงต่ำกว่า 18 ปี: ใช้ฟีเจอร์สมาชิกทั่วไปได้ ส่วนฟีเจอร์สำหรับผู้ใหญ่ ธุรกรรม และข้อตกลงที่ต้องมีความสามารถทางกฎหมายเต็มที่ยังคงถูกจำกัด",
          "อายุ 18 ปีขึ้นไป: ฟีเจอร์สำหรับผู้ใหญ่อาจเปิดได้หลังจากกรอกวันเดือนปีเกิดครบถ้วนและเป็นไปตามเงื่อนไขเฉพาะของแต่ละฟีเจอร์",
          "หนึ่งคนใช้หนึ่งบัญชีหลัก บัญชีเพิ่มเติมที่สร้างขึ้นเพื่อปั่นยอดแนะนำ JOY ความสำเร็จ หรือสิทธิประโยชน์ อาจถูกรวม ถูกเพิกถอนสิทธิ หรือถูกล็อก",
          "วันเกิดจะถูกล็อกหลังกรอกครั้งแรกเพื่อคุ้มครองด่านอายุ คุณยังมีสิทธิขอแก้ไขได้หลังการตรวจสอบตามสมควร",
          "หากมีเหตุอันควรเชื่อว่าบัญชีเป็นของผู้มีอายุต่ำกว่า 14 ปี หรือขาดความยินยอมที่จำเป็น Hugo Studio อาจหยุดประมวลผลชั่วคราวเพื่อตรวจสอบ แล้วลบหรือจำกัดข้อมูลตามที่กฎหมายกำหนด",
        ],
      },
      {
        id: "tiers",
        title: "ข้อ 3 — ระดับบัตรและสิทธิพิเศษ",
        items: [
          "ระดับบัตรสมาชิกคำนวณจากจำนวนผู้สมัครสำเร็จด้วยรหัสแนะนำของคุณ การแนะนำจะนับก็ต่อเมื่อสมาชิกใหม่ตัวจริงสร้างบัญชีและกรอกรหัสของคุณ",
          "แต่ละบัญชีกรอกรหัสผู้แนะนำได้หนึ่งรหัส ในขั้นตอนสมัครครั้งแรกเท่านั้น การสร้างบัญชีเพิ่มเพื่อใช้รหัสของตนเองถือเป็นการฉ้อฉล และ JOY กับสิทธิพิเศษที่เกี่ยวข้องอาจถูกเพิกถอน",
          "สิทธิพิเศษที่ออกให้โดยชอบจะถูกบันทึกไว้ในบัญชีของคุณ คุณตรวจสอบสถานะ วันหมดอายุ และเงื่อนไขได้ก่อนใช้",
          "หาก Hugo Studio เปลี่ยนโครงสร้างระดับ โครงสร้างใหม่จะใช้กับอนาคต สิทธิประโยชน์ที่ยังไม่หมดอายุยังคงอยู่ตามเงื่อนไขที่แสดงตอนออกให้ เว้นแต่เกิดจากข้อผิดพลาดของระบบ การฉ้อฉล หรือกฎหมายกำหนดเป็นอย่างอื่น",
          "หากสิทธิประโยชน์หนึ่งให้ต่อไม่ได้เพราะฟีเจอร์ยุติลง Hugo Studio อาจทดแทนด้วยสิทธิประโยชน์ที่มีมูลค่าการใช้งานเทียบเท่า และจะแจ้งสมาชิกล่วงหน้า",
          "สิทธิประโยชน์ที่ยังไม่ได้ใช้ไม่แปลงเป็นเงินสด JOY คูปอง และเวลาการเข้าถึงเป็นสิทธิประโยชน์ภายใน ไม่ใช่เงินฝากหรือการลงทุน",
        ],
      },
      {
        id: "star",
        title: "ข้อ 4 — ระดับ Star และของขวัญวันเกิด",
        items: [
          "ระดับ Star คำนวณจากวันเกิดทุกครั้งที่อ่านค่า และไม่ได้เก็บถาวร Star-14 จะกลายเป็น Star-18 ในวันเกิดอายุ 18 ปี",
          "Star-14 (อายุ 14 ถึงต่ำกว่า 18 ปี): เพิ่มเวลาเข้าถึงบัญชี 15 วัน",
          "Star-18 (อายุ 18 ปีขึ้นไป): เพิ่ม 30 วัน พร้อมคูปองส่วนลด 15% สำหรับแลนดิงเพจหรือเว็บไซต์หลายหน้า",
          "Star-VIP (สถานะกิตติมศักดิ์ที่ Hugo Studio มอบให้): เพิ่ม 90 วัน พร้อมคูปองเว็บสแตติก 15% และเว็บแอปไดนามิก 10%",
          "ของขวัญเปิดเฉพาะในเดือนเกิดของคุณ ปีละหนึ่งครั้ง และมีสิทธิ์หมุนวงล้อหนึ่งครั้ง",
          "ต้องกรอกวัน เดือน ปีเกิดให้ครบ หากขาดปีเกิด ระบบจะถือว่ายังไม่ทราบอายุ",
          "คูปองบริการหมดอายุ 30 วันนับจากวันที่ออก ใช้ได้ครั้งเดียว และควรแจ้งตอนพูดคุยเรื่องโปรเจกต์",
        ],
      },
      {
        id: "joy",
        title: "ข้อ 5 — แต้ม JOY",
        items: [
          "JOY เป็นแต้มบันทึกกิจกรรมภายใน Hugo Studio ไม่ใช่เงิน ไม่ใช่เครื่องมือชำระเงิน แลกเป็นเงินสดไม่ได้ และถอนเข้าบัญชีธนาคารไม่ได้",
          "JOY ซื้อขายหรือโอนออกนอกระบบไม่ได้",
          "JOY มาจากภารกิจ การเช็กอิน เกม การแนะนำ และรางวัลจากระบบ ทุกการเพิ่มและหักจะถูกบันทึกในประวัติกระเป๋าเงิน",
          "การโอน JOY ให้ผู้อื่นต้องใช้รหัส PIN ธุรกรรมหกหลักที่ตั้งไว้ในกระเป๋าเงิน",
          "แต้มที่เกิดจากข้อผิดพลาดทางเทคนิค การใช้ช่องโหว่ หรือเครื่องมืออัตโนมัติ อาจถูกปรับกลับให้ถูกต้อง และบัญชีที่เกี่ยวข้องอาจถูกล็อก",
          "เมื่อบัญชีถูกลบ หรือเมื่อ Hugo Studio ยุติการให้บริการ ยอด JOY จะสิ้นสุดลงและไม่ก่อให้เกิดภาระทางการเงินใด ๆ",
        ],
      },
      {
        id: "content",
        title: "ข้อ 6 — เนื้อหาของคุณ",
        items: [
          "คุณยังคงเป็นเจ้าของลิขสิทธิ์ในสิ่งที่คุณสร้าง ได้แก่ หน้า Bio รูปภาพ โพสต์ในชุมชน และบันทึกต่าง ๆ",
          "คุณให้สิทธิ Hugo Studio ในการจัดเก็บ ทำสำเนาเชิงเทคนิค และแสดงเนื้อหานั้นตามขอบเขตที่คุณเลือก เพียงเพื่อให้ฟีเจอร์ทำงานได้ สิทธิดังกล่าวสิ้นสุดเมื่อคุณลบเนื้อหา",
          "คุณยืนยันว่ามีสิทธิในเนื้อหาที่เผยแพร่ ได้แก่ ภาพที่คุณถ่ายเองหรือได้รับอนุญาต ข้อความที่คุณเขียน รวมถึงเพลงและฟอนต์ที่มีสัญญาอนุญาตถูกต้อง",
          "Hugo Studio ไม่นำเนื้อหาส่วนตัวของคุณไปฝึกโมเดล AI ของตนเอง",
          "หน้า Bio เป็นเนื้อหาสาธารณะ ใครก็ตามที่มีลิงก์สามารถเปิดดูได้ โปรดพิจารณาก่อนโพสต์ภาพที่มีบุคคลอื่น ข้อมูลโรงเรียน เบอร์โทรศัพท์ หรือที่อยู่",
          "แจ้งการละเมิดลิขสิทธิ์ได้ที่ " + CONTACT + " โดยขึ้นต้นหัวข้อด้วย “[Copyright]” Hugo Studio จะยืนยันการรับเรื่องภายใน 3 วันทำการ และดำเนินการให้เสร็จภายใน 10 วันทำการนับจากได้รับข้อมูลครบถ้วน",
        ],
      },
      {
        id: "data",
        title: "ข้อ 7 — ข้อมูลส่วนบุคคล",
        items: [
          "บัญชี: อีเมล ชื่อ และรูปโปรไฟล์จาก Google เวลาที่เข้าสู่ระบบ และกุญแจสาธารณะของอุปกรณ์หากคุณใช้ WebAuthn",
          "โปรไฟล์และเนื้อหา: Bio ลิงก์ รูปภาพ บันทึก ไดอารีการนอน และสิ่งที่คุณสร้างขึ้นเอง",
          "HugoPSY และ AI: คำถาม เนื้อหาบทสนทนา และแบบประเมินตนเองเท่าที่จำเป็นต่อการสร้างคำตอบ บทสนทนา HugoPSY ที่เก็บในฐานข้อมูลถูกเข้ารหัสไว้",
          "JOY และกิจกรรม: ยอดคงเหลือ ประวัติการเปลี่ยนแปลง คะแนนเกม ความคืบหน้าการเรียน กระดานหมากรุก และความสำเร็จ",
          "การจองและการบริจาค: ชื่อ อีเมล รายละเอียดคำขอ จำนวนเงิน รหัสธุรกรรม และสถานะที่ PayOS ส่งกลับ",
          "อุปกรณ์และการทำงานของระบบ: ประเภทอุปกรณ์ เส้นทางการใช้งาน ข้อผิดพลาดทางเทคนิค และตัวชี้วัดความเร็ว ที่อยู่เครือข่ายอาจถูกประมวลผลเพื่อป้องกันการใช้ในทางที่ผิด",
          "Hugo Studio ไม่เคยเห็นรหัสผ่าน Google รหัสผ่านธนาคาร หรือ OTP ของคุณ ไม่รับข้อมูลลายนิ้วมือหรือใบหน้า และไม่บันทึกภาพหน้าจอตลอดเซสชัน",
          "โครงสร้างพื้นฐานและบริการที่ใช้ (Google, MongoDB Atlas, Cloudinary, Pinecone, SendGrid, Render, Vercel, Cloudflare) มีเซิร์ฟเวอร์ในหลายประเทศ ข้อมูลที่เกี่ยวข้องจึงอาจถูกส่งและจัดเก็บนอกประเทศเวียดนาม",
          "ระยะเวลาเก็บโดยประมาณ: การแจ้งเตือนในแอปราว 90 วัน สถานะชั่วคราวที่ยังไม่เสร็จราว 30 วัน บันทึกข้อผิดพลาดปกติไม่เกิน 30 วัน ส่วนบัญชีและเนื้อหาจะเก็บไว้จนกว่าคุณจะลบ",
        ],
      },
      {
        id: "rights",
        title: "ข้อ 8 — สิทธิในข้อมูลและวิธีใช้สิทธิ",
        items: [
          "คุณมีสิทธิได้รับแจ้ง ให้หรือปฏิเสธความยินยอม เข้าถึงและแก้ไข ขอรับสำเนา ลบหรือจำกัดการประมวลผล ถอนความยินยอม คัดค้านการประมวลผล ร้องเรียน และเรียกค่าเสียหายตามที่กฎหมายกำหนด",
          "ส่งคำขอจากอีเมลของบัญชีมาที่ " + CONTACT + " โดยระบุสิทธิที่ต้องการใช้และขอบเขตข้อมูลที่เกี่ยวข้อง",
          "Hugo Studio จะตรวจสอบว่าคุณเป็นเจ้าของข้อมูลหรือผู้แทนโดยชอบด้วยกฎหมาย โดยขอเพียงข้อมูลเท่าที่จำเป็นเพื่อป้องกันการแอบอ้าง",
          "คำขอที่ถูกต้องจะได้รับการตอบกลับเบื้องต้นภายใน 02 วันทำการ ระยะเวลาดำเนินการตามปกติคือ 15 วัน กรณีซับซ้อนหรือต้องประสานบุคคลภายนอกอาจใช้เวลา 20–30 วันตามข้อกำหนดปัจจุบัน",
          "การใช้สิทธิในข้อมูลไม่ทำให้คุณเสียสิทธิประโยชน์อื่น หากข้อมูลนั้นเป็นเงื่อนไขทางเทคนิคที่จำเป็นของฟีเจอร์ใด การลบจะทำให้เฉพาะฟีเจอร์นั้นหยุดทำงาน",
          "Hugo Studio จะเก็บข้อมูลต่อหลังได้รับคำขอลบเฉพาะเมื่อกฎหมาย หน้าที่กระทบยอด ข้อพิพาท หรือสิทธิของบุคคลอื่นกำหนดไว้ และจำกัดการใช้ส่วนที่เก็บไว้ให้ตรงตามวัตถุประสงค์นั้น",
        ],
      },
      {
        id: "permissions",
        title: "ข้อ 9 — สิทธิ์บนอุปกรณ์",
        items: [
          "การแจ้งเตือน: ใช้เมื่อคุณเปิดการเตือนความจำและความเคลื่อนไหวของบัญชีเท่านั้น หากปฏิเสธ บัญชียังทำงานตามปกติ เพียงไม่มีการแจ้งเตือนแบบพุช",
          "ตำแหน่ง: ใช้เมื่อคุณเปิดสภาพอากาศ ฟีเจอร์ตามตำแหน่ง หรือการป้องกันการเข้าสู่ระบบตามตำแหน่งเท่านั้น หากปฏิเสธ ฟีเจอร์นั้นจะใช้ไม่ได้หรือใช้ข้อมูลค่าเริ่มต้น",
          "กล้อง: ใช้เมื่อคุณเลือกสแกนคิวอาร์โค้ดหรือถ่ายภาพเท่านั้น หากปฏิเสธ คุณอาจพิมพ์เองหรือเลือกไฟล์ได้ในจุดที่ฟีเจอร์รองรับ",
          "ไมโครโฟน: ใช้เมื่อคุณเลือกฟีเจอร์ที่รับเสียงเท่านั้น หากปฏิเสธ คุณยังพิมพ์ข้อความต่อได้",
          "ไบโอเมตริก: อุปกรณ์ของคุณเป็นผู้ยืนยันการเข้าสู่ระบบด้วย passkey Hugo Studio ไม่ได้รับลายนิ้วมือหรือแม่แบบใบหน้าของคุณ",
          "การปฏิเสธสิทธิ์ที่เป็นตัวเลือกจะปิดเฉพาะฟีเจอร์ที่ต้องใช้สิทธิ์นั้น Hugo Studio จะไม่ลดระดับบัตร ไม่หัก JOY และไม่ปิดกั้นฟีเจอร์ที่ไม่เกี่ยวข้อง",
        ],
      },
      {
        id: "ai",
        title: "ข้อ 10 — ขอบเขตของ AI และฟีเจอร์สุขภาพ",
        items: [
          "HugoPSY แบบประเมินตนเอง การติดตามการนอน และการวิเคราะห์สุขภาพในแอป เป็นเครื่องมือบันทึกและอ้างอิงเท่านั้น ไม่ใช่การตรวจรักษาโรค และไม่ทดแทนการวินิจฉัย ใบสั่งยา หรือคำแนะนำของผู้เชี่ยวชาญ",
          "เฉพาะเนื้อหาที่จำเป็นต่อการสร้างคำตอบเท่านั้นที่ถูกส่งไปยังบริการ AI และส่งเมื่อคุณเป็นฝ่ายส่งข้อความเอง วิธีที่ Google Gemini ประมวลผลข้อมูลบนโครงสร้างพื้นฐานของ Google เป็นไปตามนโยบายของ Google",
          "เนื้อหาที่ AI สร้างขึ้นอาจผิดพลาดได้ โปรดตรวจสอบก่อนนำไปใช้กับการเรียน การทำงาน หรือการตัดสินใจสำคัญ",
          "ในสถานการณ์ฉุกเฉิน อย่ารอคำตอบจาก AI โปรดติดต่อคนที่คุณไว้ใจ สถานพยาบาลใกล้ที่สุด หรือบริการช่วยเหลือฉุกเฉินในพื้นที่ของคุณ",
          "ใบรับรอง Study with Hugo บันทึกความคืบหน้าการเรียนภายในแอป ไม่ใช่ปริญญาหรือประกาศนียบัตรในระบบการศึกษาแห่งชาติ",
          "Radio เพียงเปิดสตรีมกระจายเสียงสาธารณะ และ “วันนี้” แสดงเฉพาะพาดหัว บทสรุปที่กองบรรณาธิการเขียนเอง และลิงก์ไปยังบทความต้นฉบับ ลิขสิทธิ์ของเนื้อหาเป็นของผู้เผยแพร่",
        ],
      },
      {
        id: "payment",
        title: "ข้อ 11 — บริการมีค่าใช้จ่าย การจอง และการบริจาค",
        items: [
          "ราคาบริการแสดงไว้ที่หน้าบริการ ขอบเขตงาน ระยะเวลา และจำนวนรอบการแก้ไข ตกลงกันเป็นลายลักษณ์อักษรก่อนเริ่มงาน",
          "การชำระเงินดำเนินการผ่าน PayOS และธนาคาร Hugo Studio ไม่เก็บข้อมูลบัตรหรือบัญชีธนาคารของคุณ และเข้าถึงบัญชีธนาคารของคุณไม่ได้",
          "การบริจาคเป็นความสมัครใจ ไม่ใช่การซื้อขาย และไม่คืนเงิน ยกเว้นกรณีธุรกรรมซ้ำหรือจำนวนเงินผิดพลาดจากข้อผิดพลาดทางเทคนิค การบริจาคไม่ปลดล็อกฟีเจอร์ และไม่มีผลต่อใบเสนอราคาหรือสิทธิสมาชิก",
          "บริการที่มีการวางมัดจำ: ยกเลิกก่อนเริ่มดำเนินงานจะคืนส่วนที่ยังไม่ได้ทำ หลังส่งมอบฉบับร่างแรกแล้ว การคืนเงินจะคิดตามปริมาณงานที่เหลือ",
          "ส่งข้อร้องเรียนเกี่ยวกับธุรกรรมมาที่ " + CONTACT + " พร้อมรหัสคำสั่งซื้อ Hugo Studio จะตอบกลับภายใน 5 วันทำการ",
          "ปัญหาที่อยู่ในขั้นตอนชำระเงิน แอปธนาคาร หรือข้อมูลของ PayOS ต้องดำเนินการผ่านช่องทางสนับสนุนอย่างเป็นทางการของ PayOS หรือธนาคาร",
        ],
      },
      {
        id: "suspension",
        title: "ข้อ 12 — การระงับ การทบทวน และความรับผิด",
        items: [
          "เมื่อความเสี่ยงไม่เร่งด่วน Hugo Studio จะเลือกเตือนหรือจำกัดเฉพาะฟีเจอร์ที่เกี่ยวข้องก่อนล็อกทั้งบัญชี ในสถานการณ์ฉุกเฉิน ระบบอาจระงับก่อนแล้วตรวจสอบภายหลังเพื่อป้องกันความเสียหาย",
          "เมื่อสามารถแจ้งได้ สมาชิกจะได้ทราบกลุ่มเหตุผล ขอบเขตของการจำกัด ระยะเวลาที่คาด หรือสิ่งที่ต้องทำเพื่อขอทบทวนการคืนสิทธิ และสามารถตอบกลับจากอีเมลบัญชีมาที่ " + CONTACT + "",
          "Hugo Studio จะทบทวนโดยใช้บันทึกระบบ พยานหลักฐานของทั้งสองฝ่าย และระดับความเสี่ยง แล้วคืนสิทธิการเข้าถึงหรือลดขอบเขตมาตรการเมื่อเหตุแห่งการจำกัดหมดไป",
          "ฟีเจอร์ชุมชนแบบไม่มีค่าใช้จ่ายให้บริการตามความสามารถในการดำเนินงานจริง ไม่รับประกันว่าจะใช้ได้ต่อเนื่อง และไม่รับประกันผลลัพธ์ด้านการเรียน สุขภาพ อาชีพ หรือรายได้",
          "เท่าที่กฎหมายอนุญาต Hugo Studio ไม่รับผิดต่อความเสียหายทางอ้อม กำไรที่คาดหวัง โอกาสที่สูญเสีย หรือผลจากการเพิกเฉยต่อคำเตือน ใช้ฟีเจอร์ผิดวิธี ให้ข้อมูลไม่ถูกต้อง หรืออาศัยเนื้อหาจาก AI ในการตัดสินใจสำคัญ",
          "ไม่มีข้อความใดในเอกสารนี้ที่ยกเว้นความรับผิดตามบังคับเกี่ยวกับการคุ้มครองข้อมูลส่วนบุคคล สิทธิผู้บริโภค ความผิดโดยเจตนาหรือความประมาทเลินเล่ออย่างร้ายแรง หรือหน้าที่อื่นที่กฎหมายไม่อนุญาตให้ยกเว้น",
          "ข้อกำหนดนี้อยู่ภายใต้กฎหมายเวียดนาม ข้อพิพาทจะเริ่มจากการเจรจาทางอีเมล หากไม่เป็นผล ให้อยู่ในเขตอำนาจของศาลที่มีอำนาจในเวียดนาม คำถามส่งมาที่ " + CONTACT + "",
        ],
      },
    ],
  },

  ja: {
    title: "規約全文",
    intro: "利用規約、プライバシーポリシー、会員規則を統合した本文です。ベトナム語版が原本であり、他の言語は参考訳です。",
    sections: [
      {
        id: "scope",
        title: "第1条 — 適用範囲",
        items: [
          "Hugo Studio は Lê Gia Huy が運営する個人プロダクトであり、公開サイト、会員エリア、アプリ、および付随する各種ユーティリティで構成されます。",
          "アカウントを作成した場合、または本規約の提示後にサービスの利用を継続した場合、お客様に適用される部分を読み、同意したものとみなします。",
          "プライバシーポリシーは本規約と不可分の一部です。",
          "Google、PayOS、銀行その他の第三者に接続する機能を利用する際は、それぞれの規約が引き続きお客様を拘束します。",
          "同一の権益について合理的な解釈が複数ある場合、法が認める範囲で会員に有利な解釈を優先します。",
        ],
      },
      {
        id: "age",
        title: "第2条 — アカウントと年齢",
        items: [
          "14歳未満の方は公開コンテンツを閲覧できますが、会員アカウントの作成および利用はできません。",
          "14歳以上16歳未満：アカウントが個人データの処理を継続する前に、保護者または法定代理人がプライバシーポリシーを読み、同意する必要があります。システムは確認時刻を記録しますが、年齢確認のみを目的として身分証明書を求めることはありません。",
          "16歳以上18歳未満：通常の会員機能を利用できます。成人向け機能、取引、および完全な行為能力を要する合意は引き続き制限されます。",
          "18歳以上：生年月日を完全に登録し、各機能固有の条件を満たした場合に、成人向け機能が開放されることがあります。",
          "お一人につき主アカウントは1つです。紹介数、JOY、実績、特典を操作する目的で作成された追加アカウントは、統合、特典の取消、またはロックの対象となることがあります。",
          "生年月日は年齢ゲートを保護するため初回登録後にロックされます。合理的な確認を経たうえで訂正を申請することは可能です。",
          "14歳未満の方のアカウントである、または必要な同意を欠くと認めるに足る根拠がある場合、Hugo Studio は確認のため処理を一時停止し、その後、法令に従いデータを削除または制限することがあります。",
        ],
      },
      {
        id: "tiers",
        title: "第3条 — カードティアと特典",
        items: [
          "会員カードのティアは、お客様の紹介コードで登録を完了した人数に基づいて決まります。実在する新規会員がアカウントを作成し、お客様のコードを入力した場合にのみ紹介として計上されます。",
          "1つのアカウントが入力できる紹介者コードは、初回登録時の1件のみです。自分のコードを使うために追加アカウントを作る行為は不正であり、関連する JOY および特典が取り消されることがあります。",
          "有効に付与された特典はアカウントに記録され、利用前に状態、有効期限、条件を確認できます。",
          "Hugo Studio がティア構成を変更した場合、新しい構成は将来に向かって適用されます。有効かつ未失効の特典は付与時に表示された条件のまま維持されます。ただし、システムの不具合や不正に起因する場合、または法令が別段を求める場合を除きます。",
          "機能の終了により特典を提供できなくなった場合、Hugo Studio は実用上同等の価値を持つ特典で代替することがあり、その際は事前に会員へ通知します。",
          "未使用の特典は現金化されません。JOY、バウチャー、アクセス期間はいずれも内部的な特典であり、預り金や投資ではありません。",
        ],
      },
      {
        id: "star",
        title: "第4条 — Star ティアと誕生日特典",
        items: [
          "Star ティアは読み取りのたびに生年月日から算出され、恒久的には保存されません。Star-14 は18歳の誕生日に Star-18 となります。",
          "Star-14（14歳以上18歳未満）：アカウントのアクセス期間を15日追加。",
          "Star-18（18歳以上）：30日追加に加え、ランディングページまたは複数ページのウェブサイトに使える15%割引バウチャー。",
          "Star-VIP（Hugo Studio が付与する名誉ステータス）：90日追加に加え、静的サイト15%および動的ウェブアプリ10%の割引バウチャー。",
          "特典は誕生月にのみ、年1回開放され、ラッキースピン1回が含まれます。",
          "生年月日は年・月・日すべての登録が必要です。年の登録がない場合、システムは年齢不明として扱います。",
          "サービスバウチャーは発行から30日で失効し、1回のみ利用でき、プロジェクトのご相談時にご提示ください。",
        ],
      },
      {
        id: "joy",
        title: "第5条 — JOY ポイント",
        items: [
          "JOY は Hugo Studio 内部の活動を記録するポイントです。通貨でも決済手段でもなく、現金への換算も銀行口座への出金もできません。",
          "JOY の売買、およびシステム外への譲渡はできません。",
          "JOY はミッション、チェックイン、ゲーム、紹介、システム報酬から得られます。加算と減算はすべてウォレット履歴に記録されます。",
          "他の方へ JOY を送るには、ウォレットで設定する6桁の取引 PIN が必要です。",
          "技術的な不具合、不具合の悪用、または自動化ツールによって発生したポイントは正しい残高に是正されることがあり、関係するアカウントはロックされる場合があります。",
          "アカウントが削除されたとき、または Hugo Studio が運営を終了したとき、JOY 残高は消滅し、これにより金銭的義務が生じることはありません。",
        ],
      },
      {
        id: "content",
        title: "第6条 — お客様のコンテンツ",
        items: [
          "Bio ページ、写真、コミュニティ投稿、メモなど、お客様が作成したものの著作権はお客様に帰属します。",
          "お客様は Hugo Studio に対し、機能を稼働させる目的に限り、選択した範囲で当該コンテンツを保存し、技術的に複製し、表示する権利を許諾します。この権利はコンテンツを削除した時点で終了します。",
          "公開するコンテンツについて権利を有することを保証してください。ご自身が撮影したか使用許諾を得た写真、ご自身が書いた文章、正当なライセンスのある音楽とフォントなどです。",
          "Hugo Studio がお客様の非公開コンテンツを自社 AI モデルの学習に使用することはありません。",
          "Bio ページは公開コンテンツです。リンクを知る人は誰でも閲覧できます。他人が写った写真、学校の情報、電話番号、住所を掲載する前によくご検討ください。",
          "著作権侵害の申立ては、件名を「[Copyright]」で始めて " + CONTACT + " までお送りください。Hugo Studio は3営業日以内に受領を確認し、必要な情報がそろってから10営業日以内に対応します。",
        ],
      },
      {
        id: "data",
        title: "第7条 — 個人データ",
        items: [
          "アカウント：Google から取得するメールアドレス、氏名、アバター、サインイン日時、WebAuthn を利用する場合は端末の公開鍵。",
          "プロフィールとコンテンツ：Bio、リンク、写真、メモ、睡眠記録、およびお客様が能動的に作成したもの。",
          "HugoPSY と AI：返答の生成に必要な質問、会話内容、自己評価。データベースに保存される HugoPSY の会話は暗号化されています。",
          "JOY と活動：残高、変動履歴、ゲームスコア、学習進捗、対局、実績。",
          "予約と寄付：氏名、メールアドレス、依頼内容、金額、取引コード、および PayOS が返す状態。",
          "端末と運用：端末種別、アクセス経路、技術的エラー、性能指標。不正利用防止のためネットワークアドレスを処理する場合があります。",
          "Hugo Studio が Google のパスワード、銀行のパスワード、OTP を見ることはありません。指紋や顔のデータを受け取ることもなく、セッションの録画も行いません。",
          "利用しているインフラおよびサービス（Google、MongoDB Atlas、Cloudinary、Pinecone、SendGrid、Render、Vercel、Cloudflare）は複数国にサーバーを置いているため、該当するデータがベトナム国外へ移転・保存される場合があります。",
          "想定保存期間：アプリ内通知は約90日、未完了の一時状態は約30日、エラーログは通常30日以内、アカウントとコンテンツはお客様が削除するまで。",
        ],
      },
      {
        id: "rights",
        title: "第8条 — データに関する権利と行使方法",
        items: [
          "お客様は、知る権利、同意または拒否する権利、閲覧・訂正する権利、複製物を取得する権利、削除または処理を制限する権利、同意を撤回する権利、処理に異議を述べる権利、苦情を申し立てる権利、および法令に基づき賠償を求める権利を有します。",
          "アカウントのメールアドレスから " + CONTACT + " 宛に、行使したい権利と対象データの範囲を明記してご請求ください。",
          "Hugo Studio は、お客様がデータ主体または適法な代理人であることを確認します。なりすまし防止に必要な範囲でのみ情報を求めます。",
          "有効なご請求には02営業日以内に初回回答を行います。通常の処理期間は15日で、複雑な案件や第三者との連携を要する場合は、現行の規定に従い20〜30日を要することがあります。",
          "データに関する権利の行使によって他の特典が失われることはありません。あるデータが機能の技術的な前提である場合、削除によって停止するのはその機能のみです。",
          "削除請求後に Hugo Studio がデータを保持するのは、法令、照合義務、紛争、または第三者の権利がそれを要する場合に限られ、保持部分の利用はその目的に限定されます。",
        ],
      },
      {
        id: "permissions",
        title: "第9条 — 端末の権限",
        items: [
          "通知：リマインダーとアカウントの更新を有効にした場合にのみ使用します。拒否してもアカウントは通常どおり動作し、プッシュ通知が届かなくなるだけです。",
          "位置情報：天気、位置連動機能、位置に基づくサインイン保護を有効にした場合にのみ使用します。拒否した場合、その機能は利用できないか、既定のデータで動作します。",
          "カメラ：QR コードの読み取りや画像の撮影を選択した場合にのみ使用します。拒否した場合、機能が対応していれば手入力やファイル選択が可能です。",
          "マイク：音声入力に対応した機能を選択した場合にのみ使用します。拒否した場合もテキスト入力を継続できます。",
          "生体認証：パスキーによるサインインはお客様の端末が確認します。Hugo Studio が指紋や顔のテンプレートを受け取ることはありません。",
          "任意の権限を拒否しても、無効になるのはその権限を必要とする機能だけです。拒否を理由にカードティアを下げたり、JOY を差し引いたり、無関係な機能を止めたりすることはありません。",
        ],
      },
      {
        id: "ai",
        title: "第10条 — AI と健康機能の限界",
        items: [
          "HugoPSY、自己評価、睡眠トラッキング、アプリ内の健康分析は、自己記録および参考のためのツールです。診療行為ではなく、診断、処方、専門家の助言に代わるものではありません。",
          "AI サービスへ送信されるのは返答に必要な内容のみで、お客様が能動的にメッセージを送った場合に限られます。Google のインフラ上で Google Gemini がデータを処理する方法は、Google 自身のポリシーに従います。",
          "AI が生成した内容には誤りが含まれることがあります。学業、仕事、重要な判断に用いる前に必ず検証してください。",
          "緊急時は AI の返答を待たないでください。信頼できる人、最寄りの医療機関、またはお住まいの地域の緊急支援サービスにご連絡ください。",
          "Study with Hugo の修了証はアプリ内の学習進捗を記録するものであり、国の教育制度における学位や資格ではありません。",
          "Radio は公開されている放送ストリームを開くだけであり、Today は見出し、発行元自身による要約、原記事へのリンクのみを表示します。当該コンテンツの著作権は発行元に帰属します。",
        ],
      },
      {
        id: "payment",
        title: "第11条 — 有料サービス、予約、寄付",
        items: [
          "サービス料金はサービスページに掲載しています。作業範囲、期間、修正回数は着手前に書面で確定します。",
          "決済は PayOS および銀行を通じて処理されます。Hugo Studio がカード情報や銀行口座情報を保存することはなく、お客様の銀行口座にアクセスすることもできません。",
          "寄付は任意であり、売買取引ではなく、返金されません。ただし、技術的な不具合による二重取引や金額の誤りを除きます。寄付によって機能が解放されることはなく、見積もりや会員の権利にも影響しません。",
          "手付金のあるサービスについて：着手前の取消は未実施分を返金します。初回ドラフト納品後は、残作業量に応じて返金します。",
          "取引に関する申立ては注文コードを添えて " + CONTACT + " までお送りください。Hugo Studio は5営業日以内に回答します。",
          "決済フロー、銀行アプリ、PayOS のデータに属する問題は、PayOS または銀行の公式サポート窓口を通じてお手続きください。",
        ],
      },
      {
        id: "suspension",
        title: "第12条 — 停止、再審査、責任",
        items: [
          "リスクが緊急でない場合、Hugo Studio はアカウント全体をロックする前に、警告または該当機能のみの制限を優先します。緊急時には被害を防ぐため、先に遮断し後から確認することがあります。",
          "通知が可能な場合、会員には理由の区分、制限の範囲、想定される期間、または復旧審査に必要な対応が伝えられ、アカウントのメールアドレスから " + CONTACT + " へ回答できます。",
          "Hugo Studio はシステムログ、双方の証拠、リスクの程度に基づいて再検討し、制限の根拠が失われた時点でアクセスを回復するか、措置を縮小します。",
          "無料のコミュニティ機能は実際の運用能力に応じて提供され、無停止での提供や、学習・健康・キャリア・収入に関する特定の成果を保証するものではありません。",
          "法が認める範囲において、Hugo Studio は間接損害、期待利益、逸失機会、ならびに警告の無視、機能の誤用、不正確な情報の提供、重要な判断における AI コンテンツへの依存に起因する結果について責任を負いません。",
          "本文のいかなる記載も、個人データ保護、消費者の権利、故意または重過失に関する強行的な責任、その他法が排除を認めない義務を排除するものではありません。",
          "本規約はベトナム法に準拠します。紛争はまず電子メールによる協議で解決し、解決に至らない場合はベトナムの管轄裁判所の管轄とします。ご質問は " + CONTACT + " までお寄せください。",
        ],
      },
    ],
  },

  ko: {
    title: "약관 전문",
    intro: "이용약관, 개인정보처리방침, 회원 규칙을 하나로 통합한 본문입니다. 베트남어판이 원본이며 다른 언어는 참고 번역입니다.",
    sections: [
      {
        id: "scope",
        title: "제1조 — 적용 범위",
        items: [
          "Hugo Studio는 Lê Gia Huy가 운영하는 개인 제품으로, 공개 사이트, 회원 영역, 앱 및 함께 제공되는 도구로 구성됩니다.",
          "계정을 만들거나 본 약관이 제공된 뒤에도 서비스를 계속 이용하면, 회원에게 적용되는 부분을 읽고 동의한 것으로 봅니다.",
          "개인정보처리방침은 본 약관과 분리할 수 없는 일부입니다.",
          "Google, PayOS, 은행 등 제3자와 연결된 기능을 사용할 때에는 각자의 약관이 계속 회원을 구속합니다.",
          "하나의 권익에 합리적인 해석이 둘 이상 존재하면, 법이 허용하는 범위에서 회원에게 유리한 해석을 우선합니다.",
        ],
      },
      {
        id: "age",
        title: "제2조 — 계정과 연령",
        items: [
          "만 14세 미만은 공개 콘텐츠를 볼 수 있으나 회원 계정을 만들거나 사용할 수 없습니다.",
          "만 14세 이상 16세 미만: 계정이 개인정보 처리를 계속하기 전에 부모 또는 법정대리인이 개인정보처리방침을 읽고 동의해야 합니다. 시스템은 확인 시각을 기록하며, 연령 증명만을 위해 신분증을 요구하지 않습니다.",
          "만 16세 이상 18세 미만: 일반 회원 기능을 사용할 수 있습니다. 성인 기능, 거래, 완전한 행위능력이 필요한 합의는 계속 제한됩니다.",
          "만 18세 이상: 생년월일을 모두 입력하고 각 기능의 개별 조건을 충족하면 성인 기능이 열릴 수 있습니다.",
          "한 사람은 하나의 주 계정을 사용합니다. 추천 수, JOY, 업적, 혜택을 조작하려고 만든 추가 계정은 통합, 혜택 회수 또는 잠금 대상이 될 수 있습니다.",
          "생년월일은 연령 관문을 보호하기 위해 최초 입력 후 잠깁니다. 합리적인 확인을 거쳐 정정을 요청할 수 있습니다.",
          "계정이 만 14세 미만의 것이거나 필요한 동의가 없다고 볼 근거가 있으면, Hugo Studio는 확인을 위해 처리를 일시 중지한 뒤 법에 따라 데이터를 삭제하거나 제한할 수 있습니다.",
        ],
      },
      {
        id: "tiers",
        title: "제3조 — 카드 등급과 특전",
        items: [
          "회원 카드 등급은 회원의 추천 코드로 가입을 마친 사람 수를 기준으로 정해집니다. 실제 신규 회원이 계정을 만들고 회원의 코드를 입력한 경우에만 추천으로 집계됩니다.",
          "한 계정은 최초 가입 단계에서 추천인 코드를 하나만 입력할 수 있습니다. 자신의 코드를 쓰려고 계정을 더 만드는 행위는 부정행위이며, 관련 JOY와 특전이 회수될 수 있습니다.",
          "정당하게 부여된 특전은 계정에 기록되며, 사용 전에 상태, 만료일, 조건을 확인할 수 있습니다.",
          "Hugo Studio가 등급 구조를 변경하면 새 구조는 장래에 적용됩니다. 유효하고 만료되지 않은 혜택은 부여 당시 표시된 조건대로 유지됩니다. 다만 시스템 오류나 부정행위에서 비롯된 경우, 또는 법이 달리 요구하는 경우는 제외합니다.",
          "기능 종료로 어떤 혜택을 더 제공할 수 없게 되면, Hugo Studio는 실사용 가치가 비슷한 혜택으로 대체할 수 있으며 사전에 회원에게 알립니다.",
          "사용하지 않은 혜택은 현금으로 바뀌지 않습니다. JOY, 바우처, 이용 기간은 내부 혜택이며 예치금이나 투자가 아닙니다.",
        ],
      },
      {
        id: "star",
        title: "제4조 — Star 등급과 생일 보상",
        items: [
          "Star 등급은 읽을 때마다 생년월일로 계산되며 영구 저장하지 않습니다. Star-14는 만 18세 생일에 Star-18이 됩니다.",
          "Star-14(만 14세 이상 18세 미만): 계정 이용 기간 15일 추가.",
          "Star-18(만 18세 이상): 30일 추가와 함께 랜딩 페이지 또는 다중 페이지 웹사이트에 쓸 수 있는 15% 할인 바우처.",
          "Star-VIP(Hugo Studio가 부여하는 명예 등급): 90일 추가와 함께 정적 웹 15%, 동적 웹앱 10% 할인 바우처.",
          "보상은 생일이 있는 달에만, 연 1회 열리며 행운의 룰렛 1회가 포함됩니다.",
          "생년월일의 연·월·일을 모두 입력해야 합니다. 연도가 없으면 시스템은 나이를 알 수 없는 것으로 처리합니다.",
          "서비스 바우처는 발급일로부터 30일 뒤 만료되고 1회만 사용할 수 있으며, 프로젝트를 상의할 때 제시하면 됩니다.",
        ],
      },
      {
        id: "joy",
        title: "제5조 — JOY 포인트",
        items: [
          "JOY는 Hugo Studio 내부 활동을 기록하는 포인트입니다. 화폐도 결제 수단도 아니며, 현금으로 바꾸거나 은행 계좌로 출금할 수 없습니다.",
          "JOY는 매매하거나 시스템 밖으로 양도할 수 없습니다.",
          "JOY는 미션, 출석, 게임, 추천, 시스템 보상에서 생깁니다. 모든 적립과 차감은 지갑 기록에 남습니다.",
          "다른 사람에게 JOY를 보내려면 지갑에서 설정하는 6자리 거래 PIN이 필요합니다.",
          "기술적 오류, 오류 악용, 자동화 도구로 생긴 포인트는 올바른 잔액으로 조정될 수 있고, 관련 계정은 잠길 수 있습니다.",
          "계정이 삭제되거나 Hugo Studio가 운영을 종료하면 JOY 잔액은 소멸하며, 이로 인한 금전적 의무는 발생하지 않습니다.",
        ],
      },
      {
        id: "content",
        title: "제6조 — 회원의 콘텐츠",
        items: [
          "Bio 페이지, 사진, 커뮤니티 글, 메모 등 회원이 만든 것의 저작권은 회원에게 있습니다.",
          "회원은 Hugo Studio에 대해, 기능을 운영하는 목적에 한하여 선택한 범위에서 해당 콘텐츠를 저장하고 기술적으로 복제하며 표시할 권리를 부여합니다. 이 권리는 콘텐츠를 삭제하면 종료됩니다.",
          "게시하는 콘텐츠에 대한 권리를 보유하고 있음을 확인해 주세요. 직접 촬영했거나 사용 허락을 받은 사진, 직접 쓴 글, 유효한 라이선스가 있는 음악과 글꼴이어야 합니다.",
          "Hugo Studio는 회원의 비공개 콘텐츠를 자체 AI 모델 학습에 사용하지 않습니다.",
          "Bio 페이지는 공개 콘텐츠입니다. 링크를 아는 사람은 누구나 볼 수 있습니다. 다른 사람이 나온 사진, 학교 정보, 전화번호, 주소를 올리기 전에 신중히 판단해 주세요.",
          "저작권 침해 신고는 제목을 “[Copyright]”로 시작해 " + CONTACT + " 로 보내 주세요. Hugo Studio는 3영업일 이내에 접수를 확인하고, 필요한 정보를 모두 받은 날부터 10영업일 이내에 처리합니다.",
        ],
      },
      {
        id: "data",
        title: "제7조 — 개인정보",
        items: [
          "계정: Google에서 받는 이메일, 이름, 프로필 사진, 로그인 시각, WebAuthn을 쓰는 경우 기기의 공개 키.",
          "프로필과 콘텐츠: Bio, 링크, 사진, 메모, 수면 일지 및 회원이 직접 만든 것.",
          "HugoPSY와 AI: 답변 생성에 필요한 질문, 대화 내용, 자가 평가. 데이터베이스에 저장되는 HugoPSY 대화는 암호화됩니다.",
          "JOY와 활동: 잔액, 변동 기록, 게임 점수, 학습 진도, 체스 기록, 업적.",
          "예약과 후원: 이름, 이메일, 요청 내용, 금액, 거래 코드, PayOS가 반환하는 상태.",
          "기기와 운영: 기기 종류, 접근 경로, 기술적 오류, 성능 지표. 남용을 막기 위해 네트워크 주소를 처리할 수 있습니다.",
          "Hugo Studio는 회원의 Google 비밀번호, 은행 비밀번호, OTP를 볼 수 없고, 지문이나 얼굴 데이터를 받지 않으며, 이용 세션을 녹화하지 않습니다.",
          "사용 중인 인프라와 서비스(Google, MongoDB Atlas, Cloudinary, Pinecone, SendGrid, Render, Vercel, Cloudflare)는 여러 국가에 서버를 두고 있어, 해당 데이터가 베트남 밖으로 이전·저장될 수 있습니다.",
          "예상 보관 기간: 앱 내 알림 약 90일, 완료되지 않은 임시 상태 약 30일, 오류 로그 보통 30일 이내, 계정과 콘텐츠는 회원이 삭제할 때까지.",
        ],
      },
      {
        id: "rights",
        title: "제8조 — 정보 권리와 행사 방법",
        items: [
          "회원은 알 권리, 동의하거나 거부할 권리, 열람·정정할 권리, 사본을 받을 권리, 삭제하거나 처리를 제한할 권리, 동의를 철회할 권리, 처리에 반대할 권리, 이의를 제기할 권리, 법에 따라 배상을 청구할 권리를 가집니다.",
          "계정 이메일에서 " + CONTACT + " 로 행사하려는 권리와 해당 데이터 범위를 적어 보내 주세요.",
          "Hugo Studio는 회원이 정보주체 또는 적법한 대리인인지 확인하며, 사칭을 막는 데 필요한 정보만 요청합니다.",
          "유효한 요청에는 02영업일 이내에 1차 회신을 드립니다. 통상 처리 기간은 15일이며, 복잡한 요청이나 제3자 협조가 필요한 경우 현행 규정에 따라 20~30일이 걸릴 수 있습니다.",
          "정보 권리를 행사해도 다른 혜택을 잃지 않습니다. 어떤 데이터가 특정 기능의 기술적 전제라면, 삭제로 멈추는 것은 그 기능뿐입니다.",
          "삭제 요청 이후에도 Hugo Studio가 데이터를 보관하는 경우는 법령, 대사(對査) 의무, 분쟁, 타인의 권리가 이를 요구할 때뿐이며, 보관한 부분은 그 목적으로만 사용합니다.",
        ],
      },
      {
        id: "permissions",
        title: "제9조 — 기기 권한",
        items: [
          "알림: 리마인더와 계정 소식을 켤 때만 사용합니다. 거부해도 계정은 정상 작동하며 푸시 알림만 오지 않습니다.",
          "위치: 날씨, 위치 기반 기능, 위치 기반 로그인 보호를 켤 때만 사용합니다. 거부하면 해당 기능을 쓸 수 없거나 기본 데이터로 동작합니다.",
          "카메라: QR 코드 스캔이나 이미지 촬영을 선택할 때만 사용합니다. 거부하면 기능이 지원하는 곳에서는 직접 입력하거나 파일을 고를 수 있습니다.",
          "마이크: 음성 입력을 지원하는 기능을 선택할 때만 사용합니다. 거부해도 텍스트 입력을 계속할 수 있습니다.",
          "생체 인증: 패스키 로그인은 회원의 기기가 확인합니다. Hugo Studio는 지문이나 얼굴 템플릿을 받지 않습니다.",
          "선택 권한을 거부하면 그 권한이 필요한 기능만 꺼집니다. 거부를 이유로 카드 등급을 낮추거나 JOY를 차감하거나 관련 없는 기능을 막지 않습니다.",
        ],
      },
      {
        id: "ai",
        title: "제10조 — AI와 건강 기능의 한계",
        items: [
          "HugoPSY, 자가 평가, 수면 추적, 앱 내 건강 분석은 스스로 기록하고 참고하기 위한 도구입니다. 진료 행위가 아니며 진단, 처방, 전문가 상담을 대신하지 않습니다.",
          "AI 서비스로 전송되는 것은 답변에 필요한 내용뿐이며, 회원이 직접 메시지를 보낼 때에만 전송됩니다. Google 인프라에서 Google Gemini가 데이터를 처리하는 방식은 Google 자체 정책을 따릅니다.",
          "AI가 만든 내용은 틀릴 수 있습니다. 학업, 업무, 중요한 결정에 쓰기 전에 반드시 확인해 주세요.",
          "긴급한 상황에서는 AI의 답변을 기다리지 마세요. 믿을 수 있는 사람, 가까운 의료기관, 또는 계신 곳의 긴급 지원 서비스에 연락하세요.",
          "Study with Hugo 수료증은 앱 안의 학습 진도를 기록한 것이며, 국가 교육 제도의 학위나 자격증이 아닙니다.",
          "Radio는 공개 방송 스트림을 열어 줄 뿐이고, 오늘은 헤드라인과 언론사가 직접 쓴 요약, 원문 링크만 보여 줍니다. 해당 콘텐츠의 저작권은 발행사에 있습니다.",
        ],
      },
      {
        id: "payment",
        title: "제11조 — 유료 서비스, 예약, 후원",
        items: [
          "서비스 가격은 서비스 페이지에 게시되어 있습니다. 작업 범위, 기간, 수정 횟수는 시작 전에 서면으로 확정합니다.",
          "결제는 PayOS와 은행을 통해 처리됩니다. Hugo Studio는 카드나 은행 계좌 정보를 저장하지 않으며 회원의 은행 계좌에 접근할 수 없습니다.",
          "후원은 자발적인 것으로 매매 거래가 아니며 환불되지 않습니다. 다만 기술적 오류로 인한 중복 거래나 금액 오류는 예외입니다. 후원은 기능을 열어 주지 않고 견적이나 회원 권리에 영향을 주지 않습니다.",
          "선금이 있는 서비스: 착수 전 취소는 수행하지 않은 부분을 환불합니다. 첫 초안을 전달한 뒤에는 남은 작업량에 따라 환불합니다.",
          "거래 관련 이의는 주문 코드와 함께 " + CONTACT + " 로 보내 주세요. Hugo Studio는 5영업일 이내에 답변합니다.",
          "결제 흐름, 은행 앱, PayOS 데이터에 속한 문제는 PayOS 또는 은행의 공식 지원 창구를 통해 처리해야 합니다.",
        ],
      },
      {
        id: "suspension",
        title: "제12조 — 정지, 재검토, 책임",
        items: [
          "위험이 급박하지 않으면 Hugo Studio는 계정 전체를 잠그기 전에 경고 또는 해당 기능만 제한하는 방식을 우선합니다. 급박한 상황에서는 피해를 막기 위해 먼저 차단하고 나중에 확인할 수 있습니다.",
          "통지가 가능한 경우 회원은 사유의 유형, 제한 범위, 예상 기간 또는 복구 검토에 필요한 조치를 안내받으며, 계정 이메일에서 " + CONTACT + " 로 의견을 보낼 수 있습니다.",
          "Hugo Studio는 시스템 로그, 양측의 증거, 위험 수준을 바탕으로 다시 검토하고, 제한 근거가 사라지면 접근을 복구하거나 조치를 축소합니다.",
          "무료 커뮤니티 기능은 실제 운영 역량에 따라 제공되며, 중단 없는 이용이나 특정한 학습·건강·진로·수입 결과를 보장하지 않습니다.",
          "법이 허용하는 범위에서 Hugo Studio는 간접 손해, 기대 이익, 상실한 기회, 그리고 경고 무시, 기능 오용, 부정확한 정보 제공, 중요한 결정에서 AI 콘텐츠에 의존한 결과에 대해 책임지지 않습니다.",
          "본문의 어떤 내용도 개인정보 보호, 소비자 권리, 고의 또는 중과실에 관한 강행적 책임이나 법이 배제를 허용하지 않는 의무를 배제하지 않습니다.",
          "본 약관은 베트남 법의 적용을 받습니다. 분쟁은 먼저 이메일 협의로 해결하고, 해결되지 않으면 베트남의 관할 법원이 관할합니다. 문의는 " + CONTACT + " 로 보내 주세요.",
        ],
      },
    ],
  },
};
