/**
 * dailyInsightsData.js
 * 31 bí quyết công nghệ, AI prompting & kiến trúc web thực chiến mỗi ngày.
 * Xoay vòng tự động theo ngày trong tháng (1 - 31), mang lại giá trị thiết thực
 * mỗi sáng cho hội viên Hugo Studio.
 */

export const DAILY_INSIGHTS = [
  {
    id: 1,
    category: "Prompt AI",
    icon: "psychology",
    gradient: "linear-gradient(135deg, #06b6d4, #3b82f6)",
    title: "Phân tách ngữ cảnh bằng XML Tags",
    takeaway: "Khi giao tiếp với Claude hoặc GPT-4, bọc các phần bằng thẻ như <context>, <rules>, <input>. Mô hình hiểu ranh giới dữ liệu rõ hơn 40% và giảm hiện tượng nhầm lẫn câu lệnh.",
    actionLabel: "Mẫu thẻ: <rules>...</rules>",
  },
  {
    id: 2,
    category: "Frontend CSS",
    icon: "style",
    gradient: "linear-gradient(135deg, #8b5cf6, #ec4899)",
    title: "Tận dụng CSS Container Queries",
    takeaway: "Thay vì dùng media query theo toàn bộ màn hình (@media), dùng @container để component tự co giãn linh hoạt theo kích thước khung chứa nó. Bền vững tuyệt đối cho Design System.",
    actionLabel: "container-type: inline-size",
  },
  {
    id: 3,
    category: "Hiệu năng Web",
    icon: "bolt",
    gradient: "linear-gradient(135deg, #f59e0b, #ea580c)",
    title: "Tăng tốc LCP với fetchpriority='high'",
    takeaway: "Gắn thuộc tính fetchpriority='high' lên ảnh bìa hoặc font chữ chủ đạo của trang. Trình duyệt sẽ ưu tiên tải tài nguyên này ngay luồng đầu tiên, giảm Largest Contentful Paint tới 500ms.",
    actionLabel: "fetchpriority=\"high\"",
  },
  {
    id: 4,
    category: "Kiến trúc",
    icon: "architecture",
    gradient: "linear-gradient(135deg, #10b981, #059669)",
    title: "Nguyên lý Single Source of Truth (SSOT)",
    takeaway: "Các hằng số dùng chung giữa Backend và Frontend (như bảng giá, cấu hình quyền, cổng server) nên được đặt tập trung trong thư mục shared/, tránh sửa 1 nơi quên nơi còn lại.",
    actionLabel: "Shared Constants Pattern",
  },
  {
    id: 5,
    category: "Prompt AI",
    icon: "auto_awesome",
    gradient: "linear-gradient(135deg, #6366f1, #a855f7)",
    title: "Kỹ thuật Few-Shot Chain-of-Thought",
    takeaway: "Đưa cho AI 1 đến 2 ví dụ cụ thể về cách bạn tư duy giải bài toán mẫu (input -> step-by-step -> output) trước khi yêu cầu nó giải quyết vấn đề thực tế.",
    actionLabel: "Few-Shot Prompting",
  },
  {
    id: 6,
    category: "Giao diện",
    icon: "blur_on",
    gradient: "linear-gradient(135deg, #38bdf8, #6366f1)",
    title: "Hiệu ứng Liquid Glass chuẩn Apple",
    takeaway: "Để kính mờ trông chân thật thay vì xỉn màu: kết hợp backdrop-filter: saturate(190%) blur(28px) cùng viền bóng phản quang inset 0 1px 0 rgba(255,255,255,0.7).",
    actionLabel: "Liquid Glass Specular",
  },
  {
    id: 7,
    category: "Clean Code",
    icon: "code",
    gradient: "linear-gradient(135deg, #059669, #0284c7)",
    title: "Chống nghẽn giao dịch với Idempotency Key",
    takeaway: "Mọi thao tác trừ điểm, chuyển tiền hoặc gửi biểu mẫu quan trọng nên đính kèm một mã UUID ngẫu nhiên từ client. Backend kiểm tra mã này để đảm bảo không bao giờ trừ 2 lần.",
    actionLabel: "Idempotent Mutations",
  },
  {
    id: 8,
    category: "Hiệu năng",
    icon: "speed",
    gradient: "linear-gradient(135deg, #f97316, #db2777)",
    title: "Web Workers cho tác vụ nặng",
    takeaway: "Khi cần nén ảnh, xử lý mảng hàng nghìn phần tử hoặc tính toán thuật toán phức tạp, hãy đẩy sang Web Worker để Main Thread luôn đạt 60fps mượt mà.",
    actionLabel: "new Worker() Pipeline",
  },
  {
    id: 9,
    category: "Bảo mật",
    icon: "shield",
    gradient: "linear-gradient(135deg, #4f46e5, #06b6d4)",
    title: "Bảo vệ Session với HttpOnly Cookies",
    takeaway: "Không bao giờ lưu JWT token nhạy cảm trong localStorage vì dễ bị tấn công XSS. Dùng Cookie HttpOnly + SameSite=Lax để trình duyệt tự động quản lý an toàn.",
    actionLabel: "HttpOnly Cookie Pattern",
  },
  {
    id: 10,
    category: "Frontend CSS",
    icon: "view_quilt",
    gradient: "linear-gradient(135deg, #d97706, #b45309)",
    title: "CSS Subgrid cho bố cục Bento Card",
    takeaway: "Sử dụng grid-template-rows: subgrid trên các thẻ con trong lưới Bento để tiêu đề và chân trang của các thẻ luôn thẳng hàng tăm tắp với nhau dù nội dung dài ngắn khác nhau.",
    actionLabel: "display: grid; subgrid",
  },
  {
    id: 11,
    category: "React / State",
    icon: "sync_alt",
    gradient: "linear-gradient(135deg, #2563eb, #7c3aed)",
    title: "useTransition cho tương tác mượt",
    takeaway: "Dùng startTransition để bọc các cập nhật state lọc tìm kiếm hoặc chuyển tab lớn. React sẽ ưu tiên giữ phản hồi phím gõ lập tức trước khi render danh sách dài.",
    actionLabel: "useTransition Hook",
  },
  {
    id: 12,
    category: "Prompt AI",
    icon: "tune",
    gradient: "linear-gradient(135deg, #9333ea, #c026d3)",
    title: "Structured Outputs với JSON Schema",
    takeaway: "Khi cần AI trả về dữ liệu chuẩn để code phân tích, hãy yêu cầu nó tuân theo JSON Schema nghiêm ngặt. Tránh dùng regex phân tích văn bản tự do.",
    actionLabel: "Zod & JSON Schema Output",
  },
  {
    id: 13,
    category: "Thiết kế UX",
    icon: "touch_app",
    gradient: "linear-gradient(135deg, #0d9488, #0284c7)",
    title: "Vùng chạm ngón tay tối thiểu 44px",
    takeaway: "Theo tiêu chuẩn Apple Human Interface Guidelines (HIG), mọi nút bấm trên màn hình cảm ứng phải đạt kích thước tối thiểu 44x44px để tránh bấm trượt.",
    actionLabel: "Apple HIG Touch Target",
  },
  {
    id: 14,
    category: "Cơ sở dữ liệu",
    icon: "database",
    gradient: "linear-gradient(135deg, #475569, #1e293b)",
    title: "SQLite WAL Mode cho ứng dụng nhanh",
    takeaway: "Bật chế độ Write-Ahead Logging (PRAGMA journal_mode = WAL) trên SQLite giúp cho phép vô số tiến trình đọc đồng thời trong khi một tiến trình đang ghi.",
    actionLabel: "PRAGMA journal_mode = WAL",
  },
  {
    id: 15,
    category: "Frontend CSS",
    icon: "colorize",
    gradient: "linear-gradient(135deg, #e11d48, #be123c)",
    title: "Bộ chọn cha :has() trong CSS thuần",
    takeaway: "CSS :has() cho phép tạo kiểu thẻ cha dựa trên việc thẻ con có đang được check hay focus không (ví dụ: .card:has(input:checked)). Không cần bất kỳ JS listener nào.",
    actionLabel: "CSS :has() Selector",
  },
  {
    id: 16,
    category: "Kiến trúc",
    icon: "layers",
    gradient: "linear-gradient(135deg, #0284c7, #2563eb)",
    title: "Error Boundary cho từng Micro-Panel",
    takeaway: "Bọc LazyBoundary riêng cho từng panel con thay vì để cả trang chung 1 boundary. Nếu 1 widget bị lỗi mạng, các phần còn lại của ứng dụng vẫn hoạt động bình thường.",
    actionLabel: "Lazy & Error Boundary",
  },
  {
    id: 17,
    category: "Hiệu năng Web",
    icon: "image",
    gradient: "linear-gradient(135deg, #16a34a, #0d9488)",
    title: "Chuyển ảnh sang định dạng WebP / AVIF",
    takeaway: "Định dạng WebP và AVIF giảm kích thước file từ 30% đến 60% so với PNG/JPEG ở cùng chất lượng hình ảnh, giúp trang tải nhanh hơn gấp đôi.",
    actionLabel: "Next-gen Image Formats",
  },
  {
    id: 18,
    category: "Prompt AI",
    icon: "lightbulb",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    title: "Vai trò System vs User trong AI",
    takeaway: "Đưa quy tắc bất biến, phong cách trả lời và định dạng vào System Prompt. Chỉ đưa dữ liệu thay đổi của phiên làm việc vào User Message để AI không bị trôi lệnh.",
    actionLabel: "System Role Anchor",
  },
  {
    id: 19,
    category: "Thiết kế UX",
    icon: "animation",
    gradient: "linear-gradient(135deg, #8b5cf6, #3b82f6)",
    title: "Hiệu ứng nảy đàn hồi (Spring Scale)",
    takeaway: "Khi người dùng ấn vào thẻ bài, áp dụng transform: scale(0.985) kèm transition cubic-bezier(0.2, 0.8, 0.2, 1). Giao diện lập tức có cảm giác vật lý sống động.",
    actionLabel: "iOS Tactile Feedback",
  },
  {
    id: 20,
    category: "Node.js",
    icon: "memory",
    gradient: "linear-gradient(135deg, #10b981, #047857)",
    title: "In-memory Cache cho API đọc nhiều",
    takeaway: "Dùng cache bộ nhớ (NodeCache / Map) với thời gian hết hạn ngắn (10 - 30 giây) cho các endpoint như số dư ví, danh sách tin tức. Giảm 90% truy vấn database.",
    actionLabel: "In-Memory Short TTL",
  },
  {
    id: 21,
    category: "Bảo mật",
    icon: "lock",
    gradient: "linear-gradient(135deg, #64748b, #334155)",
    title: "Content Security Policy (CSP) chặt chẽ",
    takeaway: "Luôn cấu hình CSP với script-src 'self' và cấm eval() bừa bãi. Đây là lá chắn vững chắc nhất ngăn ngừa mã độc XSS bị tiêm vào trình duyệt của người dùng.",
    actionLabel: "Strict CSP Header",
  },
  {
    id: 22,
    category: "Frontend CSS",
    icon: "format_paint",
    gradient: "linear-gradient(135deg, #ea580c, #c2410c)",
    title: "Màu HSL có kiểm soát (Tailored HSL)",
    takeaway: "Sử dụng biến CSS lưu dạng HSL (ví dụ: --primary: 210 100% 50%) để dễ dàng tạo các biến thể màu mờ như hsl(var(--primary) / 0.15) cho viền kính và ánh phản chiếu.",
    actionLabel: "CSS Alpha Channels",
  },
  {
    id: 23,
    category: "Prompt AI",
    icon: "fact_check",
    gradient: "linear-gradient(135deg, #0ea5e9, #0369a1)",
    title: "Yêu cầu AI trích dẫn nguồn cụ thể",
    takeaway: "Khi phân tích tài liệu dài, hãy thêm lệnh: 'Với mỗi nhận định, hãy trích dẫn số trang hoặc dòng gốc'. Điều này buộc mô hình phải kiểm tra chéo và loại bỏ bịa đặt.",
    actionLabel: "Grounded Attribution",
  },
  {
    id: 24,
    category: "Giao diện",
    icon: "nightlight",
    gradient: "linear-gradient(135deg, #4338ca, #312e81)",
    title: "Thiết kế Dark Mode không dùng màu đen tuyền",
    takeaway: "Đừng dùng #000000 thuần cho nền tối, mắt sẽ nhanh mỏi khi đọc chữ trắng. Dùng màu xanh đen than chì (như hsl(240 18% 12%)) để giữ được độ sâu và tương phản mềm mại.",
    actionLabel: "Graphite Dark Surface",
  },
  {
    id: 25,
    category: "Clean Code",
    icon: "verified",
    gradient: "linear-gradient(135deg, #15803d, #166534)",
    title: "Kiểm tra tự động trước khi Deploy",
    takeaway: "Một script kiểm tra tự động duy nhất (run-all-checks.mjs) chạy đồng thời linter, type-check, kiểm tra import và ngân sách byte giúp bạn an tâm tuyệt đối trước mỗi lần release.",
    actionLabel: "One-Click Validation",
  },
  {
    id: 26,
    category: "Hiệu năng Web",
    icon: "swap_calls",
    gradient: "linear-gradient(135deg, #7c3aed, #6d28d9)",
    title: "View Transitions API trên Web hiện đại",
    takeaway: "Gọi document.startViewTransition(() => updateDOM()) để trình duyệt tự động tạo hiệu ứng chuyển cảnh mượt mà giữa hai màn hình mà không cần thư viện animation nặng nề.",
    actionLabel: "Native View Transitions",
  },
  {
    id: 27,
    category: "Tiêu chuẩn App",
    icon: "text_fields",
    gradient: "linear-gradient(135deg, #b91c1c, #991b1b)",
    title: "Sàn cỡ chữ 13px cho trải nghiệm đọc",
    takeaway: "Tránh dùng chữ nhỏ hơn 13px trong các ứng dụng thực tế. Cỡ chữ 13px - 15.5px là khoảng vàng giúp đọc lướt thoải mái trên cả điện thoại di động lẫn máy tính.",
    actionLabel: "13px Minimum Floor",
  },
  {
    id: 28,
    category: "Prompt AI",
    icon: "terminal",
    gradient: "linear-gradient(135deg, #0284c7, #0891b2)",
    title: "Khai báo rõ ràng kết quả mong muốn",
    takeaway: "Thay vì chỉ nói 'Hãy viết code tính tổng', hãy chỉ rõ: 'Viết hàm TypeScript thuần túy, có JSDoc, xử lý trường hợp mảng rỗng, không cài thư viện ngoài'.",
    actionLabel: "Explicit Constraints",
  },
  {
    id: 29,
    category: "Kiến trúc",
    icon: "share",
    gradient: "linear-gradient(135deg, #059669, #10b981)",
    title: "Web Share API cho chia sẻ native",
    takeaway: "Nếu trình duyệt hỗ trợ navigator.share(), hãy gọi thẳng bảng chia sẻ gốc của hệ điều hành thay vì tự vẽ modal mạng xã hội. Trải nghiệm tự nhiên và nhanh hơn gấp bội.",
    actionLabel: "navigator.share() Hook",
  },
  {
    id: 30,
    category: "Thiết kế UX",
    icon: "interests",
    gradient: "linear-gradient(135deg, #c026d3, #9333ea)",
    title: "Squircle bo góc chuẩn Apple",
    takeaway: "Sử dụng hình Squircle (bo góc mềm liên tục) thay vì hình bo tròn đơn thuần (border-radius hình học) giúp các icon và thẻ bài hòa quyện tự nhiên với võng mạc mắt người.",
    actionLabel: "Continuous Squircles",
  },
  {
    id: 31,
    category: "Hugo Studio",
    icon: "rocket_launch",
    gradient: "linear-gradient(135deg, #f59e0b, #ef4444)",
    title: "Tối ưu hóa liên tục cùng Hội viên",
    takeaway: "Mỗi cải tiến nhỏ về độ trễ, cỡ chữ, độ mờ kính và tính năng hàng ngày đều tích tiểu thành đại, biến Hugo Studio thành trải nghiệm công nghệ đáng nhớ mỗi ngày.",
    actionLabel: "Constant Refinement",
  },
];

/**
 * Lấy mẹo công nghệ của ngày hôm nay một cách tự động và nhất quán
 */
export function getTodayInsight() {
  const now = new Date();
  const day = now.getDate(); // 1 - 31
  const index = (day - 1) % DAILY_INSIGHTS.length;
  return DAILY_INSIGHTS[index];
}
