export const HUGOSO_COURSE_ORDER = ["calendar", "docs", "sheets", "gemini"];

export const HUGOSO_BUNDLE = {
  id: "bundle",
  title: "Office Ready Bundle",
  priceJoy: 1290,
  regularJoy: 1680,
  saving: 390,
};

const GOOGLE_HELP = {
  calendar: "https://support.google.com/calendar/",
  docs: "https://support.google.com/docs/",
  sheets: "https://support.google.com/docs/topic/9054603",
  gemini: "https://support.google.com/gemini/",
};

/**
 * Mọi lesson dùng cùng một hợp đồng dữ liệu để giao diện và bộ chấm không bị
 * thiếu phần. `guide`, `quiz`, `practice` được viết dạng tuple cho giáo trình
 * dễ audit, sau đó chuẩn hóa thành object mà HugoSOApp sử dụng.
 */
const defineLesson = ({
  id,
  stage,
  title,
  duration,
  summary,
  sourceUrl,
  availability = "Dùng được với tài khoản Google cá nhân và Workspace.",
  guide,
  tip,
  quiz,
  practice,
  free = false,
}) => {
  const normalizedGuide = guide.map(([heading, detail]) => ({ heading, detail }));
  return {
    id,
    stage,
    title,
    duration,
    summary,
    sourceUrl,
    availability,
    free,
    guide: normalizedGuide,
    learn: normalizedGuide.slice(0, 3).map(
      ({ heading }) => `Tự thực hiện được: ${heading.toLocaleLowerCase("vi-VN")}.`,
    ),
    tip,
    video: {
      title: `${stage}: ${title}`,
      scenes: normalizedGuide.slice(0, 3).map(({ heading }) => heading),
    },
    quiz: {
      question: quiz[0],
      options: quiz[1],
      correct: quiz[2],
      explanation: quiz[3],
    },
    practice: {
      prompt: practice[0],
      placeholder: practice[1],
      keywords: practice[2],
      minimumKeywords: practice[3],
      checklist: normalizedGuide.slice(-3).map(({ heading }) => heading),
    },
  };
};

const C = (config) => defineLesson({ ...config, sourceUrl: config.sourceUrl || GOOGLE_HELP.calendar });
const D = (config) => defineLesson({ ...config, sourceUrl: config.sourceUrl || GOOGLE_HELP.docs });
const S = (config) => defineLesson({ ...config, sourceUrl: config.sourceUrl || GOOGLE_HELP.sheets });
const G = (config) => defineLesson({ ...config, sourceUrl: config.sourceUrl || GOOGLE_HELP.gemini });

const calendarSteps = [
  C({
    id: "calendar-01", stage: "Cơ bản", title: "Làm quen giao diện và múi giờ", duration: "16 phút", free: true,
    summary: "Đọc đúng các vùng của Calendar và đặt múi giờ trước khi tạo dữ liệu.",
    sourceUrl: "https://support.google.com/calendar/answer/37064",
    guide: [
      ["Mở đúng tài khoản", "Vào calendar.google.com, kiểm tra ảnh đại diện và tài khoản đang dùng trước khi tạo lịch."],
      ["Đặt múi giờ chính", "Mở Settings → Time zone, chọn Asia/Ho_Chi_Minh; chỉ bật Ask to update khi bạn thường xuyên di chuyển."],
      ["Bật múi giờ phụ", "Chọn Display secondary time zone nếu làm việc quốc tế và đặt nhãn dễ nhận biết như VN hoặc UK."],
      ["Kiểm tra thực tế", "Tạo một event thử ở ngày mai, mở lại và xác nhận giờ hiển thị đúng trên web lẫn điện thoại."],
    ],
    tip: "Calendar lưu thời điểm theo UTC rồi hiển thị theo múi giờ người xem; đừng cộng trừ giờ thủ công trong tiêu đề.",
    quiz: ["Người được mời ở múi giờ khác sẽ thấy event thế nào?", ["Cùng con số giờ với người tạo", "Theo múi giờ của chính họ", "Luôn theo UTC"], 1, "Calendar tự hiển thị thời điểm theo múi giờ của từng người."],
    practice: ["Ghi múi giờ chính, múi giờ phụ và giờ của một event thử.", "Asia/Ho_Chi_Minh · London · Event 09:00 VN = … UK", ["asia", "ho_chi_minh", "event", "giờ", "múi"], 3],
  }),
  C({
    id: "calendar-01b", stage: "Cơ bản", title: "Phân biệt Event và Task", duration: "24 phút",
    summary: "Chọn đúng loại mục: cuộc hẹn có thời lượng hay việc cần hoàn thành.",
    sourceUrl: "https://support.google.com/tasks/answer/7675838",
    guide: [
      ["Nhận diện Event", "Dùng Event khi một hoạt động chiếm khung giờ, có địa điểm/Meet hoặc có khách mời."],
      ["Nhận diện Task", "Dùng Task cho việc cần hoàn thành; thêm ngày và giờ nếu cần xuất hiện trên lịch và nhận thông báo."],
      ["Tạo Task đúng", "Trong Calendar chọn Create → Task, nhập kết quả cụ thể, ngày/giờ, mô tả và Task list phù hợp."],
      ["Hoàn thành và kiểm tra", "Đánh dấu Complete sau khi làm; kiểm tra task đã vào mục Completed thay vì xóa để giữ dấu vết."],
    ],
    tip: "Viết Task bằng động từ + kết quả: “Gửi bản PDF cho Mai”, không viết tên chủ đề mơ hồ như “Báo cáo”.",
    quiz: ["Mục nào phù hợp với việc “Gửi báo cáo trước 17:00” và không cần mời ai?", ["Event", "Task", "Appointment schedule"], 1, "Task theo dõi việc phải hoàn thành; Event giữ một khoảng thời gian."],
    practice: ["Tạo một Event và một Task liên quan cùng dự án rồi mô tả sự khác nhau.", "Event: Review 14:00–14:30… / Task: Gửi PDF 17:00…", ["event", "task", "gửi", "giờ", "hoàn thành"], 3],
  }),
  C({
    id: "calendar-02", stage: "Cơ bản", title: "Event đầy đủ và lịch lặp", duration: "27 phút",
    summary: "Tạo event có mục tiêu, mô tả, địa điểm/Meet, thông báo và quy tắc lặp.",
    sourceUrl: "https://support.google.com/calendar/answer/72143",
    guide: [
      ["Đặt tiêu đề có kết quả", "Dùng mẫu [Loại] Kết quả, ví dụ “[Review] Chốt kế hoạch tháng 8”."],
      ["Điền chi tiết", "Chọn lịch chứa event, thời gian bắt đầu/kết thúc, địa điểm hoặc Google Meet và mô tả có agenda."],
      ["Cấu hình thông báo", "Thêm số lượng thông báo vừa đủ cho tính chất công việc; người khác không thấy màu event cá nhân của bạn."],
      ["Thiết lập lặp có điểm dừng", "Chọn Does not repeat → Custom và đặt ngày kết thúc; kiểm tra kỹ phạm vi khi sửa một instance hay cả series."],
    ],
    tip: "Một event tốt trả lời được: diễn ra khi nào, ở đâu, cần chuẩn bị gì và kết quả mong đợi là gì.",
    quiz: ["Khi sửa một event trong chuỗi lặp, lựa chọn nào chỉ thay đổi lần đang mở?", ["This event", "This and following", "All events"], 0, "This event chỉ áp dụng cho instance hiện tại."],
    practice: ["Mô tả một event lặp hàng tuần có ngày kết thúc, agenda và thông báo.", "Weekly review · Thứ Sáu 16:00 · kết thúc 30/09 · agenda…", ["lặp", "kết thúc", "agenda", "thông báo", "thứ"], 3],
  }),
  C({
    id: "calendar-02b", stage: "Thực hành", title: "Time-blocking bằng Event", duration: "26 phút",
    summary: "Biến danh sách việc thành kế hoạch tuần có khối tập trung và khoảng đệm.",
    guide: [
      ["Chọn ba ưu tiên", "Trước khi kéo lịch, chọn tối đa ba kết quả quan trọng trong tuần thay vì xếp mọi task."],
      ["Đặt khối làm việc", "Tạo event 45–90 phút cho từng kết quả; mô tả ghi đầu ra cần đạt, không chỉ tên môn hoặc dự án."],
      ["Thêm khoảng đệm", "Chừa thời gian chuyển ngữ cảnh, nghỉ và xử lý phát sinh giữa các cuộc họp hoặc khối tập trung."],
      ["Review cuối ngày", "Cuối ngày, chuyển khối chưa làm sang thời điểm thực tế; không sửa event đã qua để che mất lịch sử."],
    ],
    tip: "Time-blocking là phương pháp lập kế hoạch, không phải một loại event riêng và không yêu cầu gói Workspace.",
    quiz: ["Tài khoản cá nhân không có Focus time nên dùng gì để time-block?", ["Event thường", "Appointment schedule", "Task không ngày"], 0, "Event thường vẫn giữ được khung giờ; Focus time chỉ bổ sung tự động từ chối và tắt Chat."],
    practice: ["Lập ba time block cho một ngày, mỗi block có đầu ra và khoảng đệm.", "09:00–10:00 Draft… · 10:00–10:15 Buffer…", ["09", "đầu ra", "buffer", "phút", "block"], 3],
  }),
  C({
    id: "calendar-02c", stage: "Thực hành", title: "Focus time, Working hours và Out of office", duration: "30 phút",
    summary: "Dùng đúng các loại thời gian Workspace và biết phương án thay thế khi tài khoản không hỗ trợ.",
    sourceUrl: "https://support.google.com/calendar/answer/11190973",
    availability: "Focus time và Working hours phụ thuộc gói Workspace/quản trị viên; tài khoản không có tính năng dùng Event thường.",
    guide: [
      ["Kiểm tra khả dụng", "Trên máy tính mở Day hoặc Week view; Focus time chỉ tạo được từ hai chế độ này và cần gói Workspace đủ điều kiện."],
      ["Tạo Focus time", "Chọn khung giờ → Focus time, đặt thời lượng, tùy chọn tự từ chối meeting và tắt thông báo Chat."],
      ["Đặt Working hours", "Trong Settings → Working hours, bật các ngày/khung giờ làm việc; có thể chia một ngày thành nhiều khoảng."],
      ["Tạo Out of office", "Dùng Out of office cho thời gian vắng mặt và kiểm tra nội dung từ chối tự động trước khi lưu."],
    ],
    tip: "Nếu không thấy một nút, đừng kết luận thao tác sai: kiểm tra loại tài khoản, gói dịch vụ, quyền admin và chế độ Day/Week.",
    quiz: ["Focus time chỉ có thể được tạo trực tiếp từ chế độ xem nào?", ["Month và Year", "Day và Week", "Schedule duy nhất"], 1, "Google quy định tạo Focus time từ Day hoặc Week view."],
    practice: ["Ghi tính năng tài khoản của bạn có, cấu hình đã dùng và phương án thay thế nếu bị giới hạn.", "Có Focus time: … / Không có: dùng Event tên [Focus]…", ["focus", "event", "workspace", "từ chối", "week"], 3],
  }),
  C({
    id: "calendar-03", stage: "Thực hành", title: "Mời họp, agenda và tìm giờ", duration: "28 phút",
    summary: "Tạo lời mời có khách, agenda, tài liệu và thời gian phù hợp.",
    sourceUrl: "https://support.google.com/calendar/answer/72143",
    guide: [
      ["Thêm khách đúng vai trò", "Nhập email khách mời, phân biệt người bắt buộc và người chỉ cần được biết trong agenda."],
      ["Tìm thời gian", "Dùng lịch khả dụng hoặc Suggested times khi tài khoản đủ điều kiện; không giả định phần trống luôn nghĩa là người kia rảnh."],
      ["Viết agenda", "Mô tả gồm mục tiêu, chuẩn bị trước, các quyết định cần chốt và owner ghi biên bản."],
      ["Kiểm tra quyền khách", "Tắt Invite others hoặc Modify event nếu khách không cần các quyền này; gửi update có chủ đích khi sửa."],
    ],
    tip: "Đính kèm tài liệu làm việc trước cuộc họp và cấp quyền Drive trước, tránh mất thời gian xin quyền khi họp đã bắt đầu.",
    quiz: ["Muốn ngăn khách tự thêm người khác, bạn cần làm gì?", ["Tắt Invite others", "Xóa Google Meet", "Đặt event Private"], 0, "Guest permissions có tùy chọn Invite others riêng."],
    practice: ["Soạn lời mời họp 30 phút gồm mục tiêu, chuẩn bị, quyết định và owner.", "Mục tiêu… / Chuẩn bị… / Quyết định… / Owner…", ["mục tiêu", "chuẩn bị", "quyết định", "owner", "30"], 4],
  }),
  C({
    id: "calendar-03b", stage: "Nâng cao", title: "Lịch phụ, chia sẻ và quyền riêng tư", duration: "27 phút",
    summary: "Tách lịch theo mục đích và cấp mức quyền nhỏ nhất cần thiết.",
    sourceUrl: "https://support.google.com/calendar/answer/15716974",
    guide: [
      ["Tạo lịch phụ", "Trên máy tính, tạo lịch riêng cho dự án/nhóm; đặt tên, mô tả và múi giờ rõ ràng."],
      ["Chọn người hoặc nhóm", "Trong Settings and sharing → Shared with, thêm đúng email hoặc Google Group."],
      ["Cấp quyền tối thiểu", "Chọn See only free/busy nếu chỉ cần tìm giờ; chỉ cấp Make changes and manage sharing cho đồng quản trị."],
      ["Kiểm tra quyền rộng hơn", "Rà Public access và domain sharing vì quyền rộng hơn có thể lấn át quyền hạn chế cấp cho một cá nhân."],
    ],
    tip: "Private event không thể bù cho một lịch đã công khai toàn bộ chi tiết; luôn kiểm tra quyền ở cấp lịch trước.",
    quiz: ["Mức nào phù hợp khi người khác chỉ cần biết bạn bận hay rảnh?", ["See only free/busy", "See all event details", "Make changes and manage sharing"], 0, "Free/busy ẩn tên và chi tiết event."],
    practice: ["Lập ma trận quyền cho ba vai trò: đồng quản trị, thành viên và người ngoài.", "Admin: manage sharing… / Member: see details… / External: free/busy…", ["admin", "member", "external", "free", "sharing"], 4],
  }),
  C({
    id: "calendar-04", stage: "Nâng cao", title: "Appointment schedule căn bản", duration: "24 phút",
    summary: "Tạo schedule đầu tiên với duration, availability và cách gặp.",
    sourceUrl: "https://support.google.com/calendar/answer/10729749",
    availability: "Tạo Appointment schedule trên máy tính; một số thiết lập nâng cao cần Google Workspace hoặc Google One đủ điều kiện.",
    guide: [
      ["Tạo schedule", "Trên máy tính chọn Create → Appointment schedule, đặt tên công khai, thời lượng và các khung availability."],
      ["Đặt availability", "Chọn ngày/khung giờ có thể được đặt, scheduling window và khoảng thời gian hiệu lực của schedule."],
      ["Chọn calendar", "Chọn primary hoặc secondary calendar nhận booking và các calendar cần Check calendars for availability."],
      ["Chọn cách gặp", "Chọn Google Meet, gặp trực tiếp, gọi điện hoặc để người đặt tự chỉ định theo loại dịch vụ."],
    ],
    tip: "Tên appointment schedule hiển thị công khai trên booking page; dùng tên mô tả dịch vụ, không dùng ghi chú nội bộ.",
    quiz: ["Bạn có thể tạo Appointment schedule mới trực tiếp trong app Calendar trên điện thoại không?", ["Có trên mọi tài khoản", "Không, cần trình duyệt máy tính", "Chỉ trên Android"], 1, "Google hiện yêu cầu máy tính với trình duyệt được hỗ trợ để tạo schedule."],
    practice: ["Ghi cấu hình schedule đầu tiên: title, duration, availability, calendar và cách gặp.", "Tư vấn 30 phút · T2/T4 14:00–17:00 · Work calendar · Meet…", ["phút", "availability", "calendar", "meet"], 3],
  }),
  C({
    id: "calendar-04b", stage: "Nâng cao", title: "Booking page nâng cao và bài tốt nghiệp", duration: "29 phút",
    summary: "Chống double-booking, thu đủ thông tin và kiểm thử toàn bộ hành trình đặt lịch.",
    sourceUrl: "https://support.google.com/calendar/answer/10729749",
    availability: "Buffer, nhiều reminder, payment và một số tùy chọn booking cần gói Google Workspace/Google One đủ điều kiện.",
    guide: [
      ["Chống đặt quá tải", "Đặt buffer, maximum bookings/day, minimum/maximum advance notice và rà các calendar dùng để kiểm tra xung đột."],
      ["Cấu hình co-host", "Thêm co-host khi cần; availability của co-host không được kiểm tra mặc định nên phải thêm calendar liên quan vào availability checks."],
      ["Hoàn thiện form", "Viết mô tả, thêm trường booking form cần thiết, bật email verification khi phù hợp và cấu hình confirmation/reminder."],
      ["Kiểm thử như khách", "Mở link ở cửa sổ ẩn danh, thử múi giờ khác, giờ đang bận, email xác nhận, hủy và đổi lịch; ghi lại lỗi."],
    ],
    tip: "Không thu dữ liệu nhạy cảm trong booking form nếu không thật sự cần và chưa có quy trình bảo vệ dữ liệu.",
    quiz: ["Appointment schedule có tự kiểm tra lịch của co-host theo mặc định không?", ["Có", "Không", "Chỉ khi dùng Meet"], 1, "Google lưu ý cần thêm calendar của co-host vào availability checks để ngăn trùng."],
    practice: ["Nộp biên bản test booking gồm buffer, advance notice, form, xung đột, múi giờ và email.", "Buffer 15… đặt trước 12 giờ… conflict blocked… timezone OK… email OK…", ["buffer", "đặt trước", "form", "conflict", "múi giờ", "email"], 5],
  }),
];

const docsSteps = [
  D({
    id: "docs-01", stage: "Cơ bản", title: "Pages, Pageless và thiết lập tài liệu", duration: "18 phút", free: true,
    summary: "Chọn đúng chế độ trang trước khi xây báo cáo.",
    sourceUrl: "https://support.google.com/docs/answer/11528737",
    guide: [
      ["Xác định đầu ra", "Chọn Pages nếu cần in/PDF, header, footer và page number; chọn Pageless nếu ưu tiên đọc và cộng tác trên màn hình."],
      ["Đặt page setup", "Trong File → Page setup, chọn Pages, cỡ giấy, hướng trang, lề và màu trang theo yêu cầu tổ chức."],
      ["Đặt tên file", "Dùng tên có chủ đề, phiên bản và ngày; không dùng “Untitled document” hoặc “final-final”."],
      ["Kiểm tra quyền", "Mở Share và xác nhận General access trước khi nhập dữ liệu nhạy cảm."],
    ],
    tip: "Header, footer và page number không hiển thị trong Pageless; đây là khác biệt tính năng, không phải lỗi.",
    quiz: ["Chế độ nào cần dùng nếu báo cáo bắt buộc có header và số trang?", ["Pageless", "Pages", "Either, không khác nhau"], 1, "Các phần tử trang chỉ khả dụng/hiển thị trong Pages."],
    practice: ["Ghi lựa chọn Pages/Pageless cho một báo cáo và giải thích bằng ba yêu cầu đầu ra.", "Chọn Pages vì cần PDF, header và số trang…", ["pages", "pdf", "header", "trang", "lề"], 3],
  }),
  D({
    id: "docs-01b", stage: "Cơ bản", title: "Heading, outline và mục lục tự động", duration: "28 phút",
    summary: "Dùng cấu trúc ngữ nghĩa thay cho định dạng thủ công.",
    sourceUrl: "https://support.google.com/docs/answer/116338",
    guide: [
      ["Dựng cây nội dung", "Viết Title, Heading 1 cho chương, Heading 2 cho mục và Heading 3 cho tiểu mục; không nhảy cấp tùy tiện."],
      ["Áp dụng style", "Chọn đoạn → Paragraph styles; chỉnh một heading mẫu rồi Update Heading to match nếu cần style riêng."],
      ["Chèn mục lục", "Đặt con trỏ ở vị trí mục lục → Insert → Page elements → Table of contents và chọn kiểu."],
      ["Kiểm thử cập nhật", "Thêm một heading mới, bấm Refresh trên mục lục và kiểm tra liên kết dẫn đúng vị trí."],
    ],
    tip: "Chữ to và in đậm không tự trở thành heading; outline và mục lục chỉ hiểu Paragraph styles.",
    quiz: ["Mục lục Google Docs lấy cấu trúc từ đâu?", ["Các đoạn in đậm", "Title và Heading styles", "Comment"], 1, "Table of contents liên kết đến các title/heading."],
    practice: ["Viết cây cấu trúc có ít nhất ba Heading 1 và hai Heading 2 rồi mô tả kết quả refresh mục lục.", "H1 Introduction… H2 Scope… TOC đã refresh…", ["heading 1", "heading 2", "mục lục", "refresh"], 3],
  }),
  D({
    id: "docs-02", stage: "Cơ bản", title: "Document tabs và subtabs", duration: "24 phút",
    summary: "Tổ chức tài liệu dài bằng tabs mà không phá hierarchy heading.",
    sourceUrl: "https://support.google.com/docs/answer/15499791",
    guide: [
      ["Mở panel", "Chọn Show tabs and outlines ở góc trái; tài liệu mới luôn có Tab 1 và không xóa được nếu chưa có tab khác."],
      ["Tạo cấu trúc tab", "Thêm tab cho phần lớn, rename rõ nghĩa và chỉ dùng subtab khi thật sự cần phân cấp."],
      ["Hiểu giới hạn", "Tabs lồng tối đa ba cấp và một tài liệu tối đa 100 tabs; Suggesting mode không thêm/di chuyển/xóa tab."],
      ["Xuất đúng phạm vi", "Khi Download hoặc Print, chọn Current tab hay All tabs; mặc định có thể chỉ là tab hiện tại."],
    ],
    tip: "Tabs chia không gian lớn; headings tổ chức nội dung bên trong từng tab. Hai công cụ không thay thế nhau.",
    quiz: ["Khi tải một Docs có tabs, bạn cần kiểm tra điều gì?", ["Current tab hay All tabs", "Màu tab", "Chế độ dark mode"], 0, "Google yêu cầu chọn phạm vi tab khi download/print."],
    practice: ["Thiết kế tài liệu ba tabs, một subtab và ghi lựa chọn khi xuất toàn bộ PDF.", "Tab 1 Brief / Tab 2 Report → Subtab Appendix / Export All tabs…", ["tab", "subtab", "all tabs", "pdf"], 3],
  }),
  D({
    id: "docs-02a", stage: "Thực hành", title: "Chia sẻ và kiểm soát truy cập", duration: "22 phút",
    summary: "Phân biệt Viewer, Commenter, Editor và phạm vi General access.",
    sourceUrl: "https://support.google.com/docs/answer/2494822",
    guide: [
      ["Chọn phạm vi", "Để General access là Restricted khi tài liệu chưa sẵn sàng; chỉ mở link rộng hơn khi có lý do rõ ràng."],
      ["Chọn vai trò", "Viewer chỉ đọc, Commenter góp ý không sửa trực tiếp, Editor thay đổi nội dung và chia sẻ tùy cài đặt."],
      ["Gửi thông báo có ngữ cảnh", "Thêm message nói rõ người nhận cần review phần nào và hạn phản hồi."],
      ["Kiểm thử", "Dùng cửa sổ ẩn danh hoặc tài khoản thử để xác nhận người ngoài thấy đúng quyền."],
    ],
    tip: "Sao chép link không tự cấp quyền; luôn kiểm tra General access và vai trò trước khi gửi.",
    quiz: ["Vai trò nào phù hợp để góp ý nhưng không sửa trực tiếp bản gốc?", ["Viewer", "Commenter", "Editor"], 1, "Commenter có thể comment và thường có thể suggest nhưng không chỉnh trực tiếp."],
    practice: ["Lập ma trận quyền cho chủ file, reviewer và người chỉ đọc.", "Owner: Editor… Reviewer: Commenter… Reader: Viewer…", ["owner", "reviewer", "commenter", "viewer"], 3],
  }),
  D({
    id: "docs-02b", stage: "Thực hành", title: "Comments, Suggesting và action items", duration: "29 phút",
    summary: "Chọn đúng kênh cộng tác và giao việc có trách nhiệm.",
    sourceUrl: "https://support.google.com/docs/answer/6033474",
    availability: "Assign Tasks trực tiếp trong Docs chủ yếu dành cho tài khoản work/school trong cùng tổ chức; comments dùng rộng rãi hơn.",
    guide: [
      ["Dùng Comment đúng chỗ", "Bôi đen đúng đoạn, viết vấn đề + đề xuất + người cần phản hồi; @mention khi cần thông báo."],
      ["Dùng Suggesting", "Chuyển Editing → Suggesting để thay đổi không ghi đè bản gốc; chủ file Accept hoặc Reject từng đề xuất."],
      ["Giao action item", "Nếu tài khoản hỗ trợ, dùng @task hoặc assign comment cho đúng người và đặt hạn; bảo đảm họ có quyền truy cập."],
      ["Đóng vòng phản hồi", "Chỉ Resolve khi nội dung đã sửa và kiểm tra; dùng comment history để tìm lại thread đã đóng."],
    ],
    tip: "Comment thảo luận “nên sửa gì”; Suggesting trình bày chính xác “bản sửa sẽ trông thế nào”.",
    quiz: ["Chế độ nào cho phép đề xuất thay đổi mà chưa thay bản gốc?", ["Editing", "Suggesting", "Viewing"], 1, "Chủ file phải accept suggestion trước khi nó thay nội dung gốc."],
    practice: ["Mô tả một vòng review gồm comment, suggestion, phản hồi và resolve.", "Comment vấn đề → Suggesting bản sửa → Owner accept → Resolve…", ["comment", "suggesting", "accept", "resolve"], 4],
  }),
  D({
    id: "docs-02c", stage: "Thực hành", title: "Version history và khôi phục an toàn", duration: "18 phút",
    summary: "Đặt tên mốc, so sánh thay đổi và khôi phục mà không mất bản hiện tại.",
    sourceUrl: "https://support.google.com/docs/answer/190843",
    guide: [
      ["Mở lịch sử", "Chọn File → Version history → See version history; bạn cần quyền edit để duyệt phiên bản cũ."],
      ["Đặt tên mốc", "Trước vòng sửa lớn, chọn Name current version và dùng tên có ý nghĩa như “Approved outline”."],
      ["So sánh", "Chọn mốc và xem người sửa/màu thay đổi; xác định chính xác nội dung cần lấy lại."],
      ["Khôi phục an toàn", "Nếu chỉ cần một đoạn, tạo bản copy hoặc sao chép đoạn cũ; chỉ Restore version khi muốn đưa toàn tài liệu về mốc đó."],
    ],
    tip: "Version history không thay thế backup xuất bản; trước thao tác lớn, tạo named version hoặc bản copy.",
    quiz: ["Điều kiện để duyệt các phiên bản trước của Docs là gì?", ["Quyền xem", "Quyền chỉnh sửa", "Có link công khai"], 1, "Google yêu cầu edit permission để browse earlier versions."],
    practice: ["Đặt tên một version, tạo thay đổi thử và mô tả cách lấy lại mà không mất bản mới.", "Named version: Approved outline… tạo copy rồi lấy đoạn…", ["version", "name", "copy", "restore"], 3],
  }),
  D({
    id: "docs-03", stage: "Nâng cao", title: "Harvard: in-text citation chuẩn", duration: "34 phút",
    summary: "Viết trích dẫn tác giả–năm và hiểu rằng Harvard có nhiều biến thể.",
    sourceUrl: "https://support.google.com/docs/answer/10090962",
    guide: [
      ["Chọn style guide", "Xác nhận quy định Harvard của trường/tổ chức; Harvard không có một bản duy nhất áp dụng toàn cầu."],
      ["Viết paraphrase", "Dùng (Tác giả, Năm) hoặc Tác giả (Năm); trích trực tiếp cần trang nếu nguồn có số trang."],
      ["Xử lý tác giả tổ chức", "Dùng tên tổ chức khi không có cá nhân; không tự ghi Anonymous nếu trang có corporate author."],
      ["Hiểu giới hạn Docs", "Tools → Citations chỉ hỗ trợ MLA 8, APA 7 và Chicago Author-Date 17, không có lựa chọn Harvard riêng."],
    ],
    tip: "Có thể dùng Chicago Author-Date làm điểm tham khảo, nhưng phải chỉnh thủ công theo Harvard guide được yêu cầu.",
    quiz: ["Google Docs Citations có nút chọn Harvard trực tiếp không?", ["Có", "Không", "Chỉ trên Workspace"], 1, "Công cụ tích hợp hiện liệt kê MLA, APA và Chicago Author-Date."],
    practice: ["Viết một câu paraphrase và một trích dẫn trực tiếp có số trang theo Harvard guide của bạn.", "Nguyen (2025) cho rằng… / “…” (Nguyen, 2025, p. 18).", ["202", "nguyen", "p.", "trang", "("], 3],
  }),
  D({
    id: "docs-03b", stage: "Nâng cao", title: "Harvard: reference list và kiểm tra chéo", duration: "38 phút",
    summary: "Tạo reference cho sách, bài báo và website; kiểm tra 1–1 với citation.",
    sourceUrl: "https://support.google.com/docs/answer/10090962",
    guide: [
      ["Thu đủ metadata", "Ghi tác giả/tổ chức, năm, tiêu đề, nơi xuất bản hoặc journal, volume/issue/pages, DOI/URL và ngày truy cập khi guide yêu cầu."],
      ["Định dạng theo loại nguồn", "Không dùng một mẫu cho mọi nguồn; sách, journal article và webpage có trường khác nhau."],
      ["Sắp xếp danh sách", "Sắp xếp alphabet theo tác giả/tổ chức và dùng hanging indent theo guide của đơn vị."],
      ["Audit hai chiều", "Mỗi in-text citation phải có một reference và mỗi reference phải được trích trong bài; kiểm URL/DOI trước khi nộp."],
    ],
    tip: "Công cụ citation giúp lưu metadata nhưng không chịu trách nhiệm cho độ chính xác của dữ liệu bạn nhập.",
    quiz: ["Bước audit quan trọng nhất giữa bài và reference list là gì?", ["Mọi mục có cùng màu", "Đối chiếu citation và reference theo hai chiều", "Sắp theo ngày mới nhất"], 1, "Không được có citation thiếu reference hoặc reference chưa dùng."],
    practice: ["Tạo ba reference Harvard: sách, journal article và webpage, rồi ghi kết quả audit.", "Book: … / Journal: … DOI… / Web: … Accessed… / Audit 3–3", ["book", "journal", "doi", "accessed", "audit"], 4],
  }),
  D({
    id: "docs-04", stage: "Nâng cao", title: "Biên tập, accessibility và xuất bản", duration: "42 phút",
    summary: "Hoàn thiện báo cáo có cấu trúc, caption, alt text và PDF đúng phạm vi tabs.",
    sourceUrl: "https://support.google.com/docs/answer/86629",
    guide: [
      ["Biên tập ba vòng", "Vòng 1 kiểm luận điểm/cấu trúc; vòng 2 bằng chứng/citation; vòng 3 câu chữ, chính tả và format."],
      ["Tăng khả năng tiếp cận", "Giữ heading đúng cấp, link có mô tả, thêm alt text cho hình quan trọng và không dùng màu làm tín hiệu duy nhất."],
      ["Kiểm phần tử trang", "Trong Pages, rà section break, header/footer, page number, caption hình/bảng và mục lục."],
      ["Xuất và QA", "Download PDF với All tabs nếu cần; mở PDF, thử link, kiểm trang trống, bảng bị cắt và font thay đổi."],
    ],
    tip: "Luôn đánh giá file đầu ra, không chỉ bản Docs; PDF có thể phát sinh ngắt trang và cắt bảng khác màn soạn thảo.",
    quiz: ["Trình tự biên tập hợp lý là gì?", ["Format → chính tả → luận điểm", "Luận điểm → bằng chứng → câu chữ", "Màu → font → citation"], 1, "Sửa cấu trúc trước để tránh trau chuốt đoạn sau đó bị xóa."],
    practice: ["Nộp checklist QA tối thiểu sáu mục cho báo cáo PDF cuối khóa.", "□ Heading □ Citation-reference □ Alt text □ Caption □ All tabs □ Link…", ["heading", "citation", "alt", "caption", "pdf", "link"], 5],
  }),
];

const sheetsSteps = [
  S({
    id: "sheets-01", stage: "Cơ bản", title: "Mô hình dữ liệu sạch", duration: "20 phút", free: true,
    summary: "Thiết kế bảng theo nguyên tắc một hàng–một bản ghi, một cột–một thuộc tính.",
    guide: [
      ["Xác định grain", "Viết rõ một hàng đại diện cho điều gì: một task, một giao dịch hay một người."],
      ["Đặt header duy nhất", "Mỗi cột có tên không trùng, không để header rỗng và không nhét hai thuộc tính vào cùng cột."],
      ["Giữ vùng dữ liệu liên tục", "Không merge cell, không chèn subtotal thủ công và không dùng hàng trống để chia nhóm trong nguồn."],
      ["Chuẩn hóa kiểu", "Ngày là date, số là number, trạng thái dùng tập giá trị nhất quán; không trộn “N/A” vào cột số."],
    ],
    tip: "Một sheet đẹp chưa chắc là dữ liệu tốt; cấu trúc phải cho phép sort, filter, formula và Pivot không bị vỡ.",
    quiz: ["Trong bảng nguồn, một hàng nên đại diện cho gì?", ["Một bản ghi nhất quán", "Một nhóm có nhiều loại dữ liệu", "Một màu trạng thái"], 0, "Grain nhất quán là nền tảng của phân tích."],
    practice: ["Thiết kế tám cột cho task tracker và nêu grain của mỗi hàng.", "Mỗi hàng = 1 task; Task ID, Title, Owner, Status, Start, Due…", ["mỗi hàng", "task", "owner", "status", "due"], 4],
  }),
  S({
    id: "sheets-01b", stage: "Cơ bản", title: "Tables, column types và validation", duration: "31 phút",
    summary: "Chuyển range thành Table và ngăn dữ liệu sai từ lúc nhập.",
    sourceUrl: "https://support.google.com/docs/answer/14239833",
    guide: [
      ["Chuyển thành Table", "Chọn vùng có header → Format → Convert to table; đặt tên table dễ đọc và không trùng."],
      ["Đặt column type", "Chọn kiểu phù hợp như Number, Text, Date, Dropdown, Checkbox hoặc None cho dữ liệu hỗn hợp có chủ đích."],
      ["Thiết lập validation", "Với cột ngoài Table hoặc yêu cầu riêng, dùng Data validation, bật reject input khi giá trị sai phải bị chặn."],
      ["Kiểm tra view", "Tạo table filter view; xác nhận việc lọc/sort không làm thay đổi góc nhìn của cộng tác viên."],
    ],
    tip: "Table references như `DeptSales[Sales Amount]` tự mở rộng khi thêm/xóa dữ liệu và dễ đọc hơn range cứng.",
    quiz: ["Table view có lợi ích gì khi cộng tác?", ["Mọi người bị ép cùng bộ lọc", "Có thể lọc mà không ảnh hưởng góc nhìn người khác", "Tự khóa toàn bộ sheet"], 1, "Mỗi view có cấu hình filter/sort riêng."],
    practice: ["Mô tả Table task tracker gồm tên table, bốn column types và một quy tắc reject input.", "Tasks: Due=Date, Status=Dropdown… reject Status ngoài danh sách…", ["table", "date", "dropdown", "reject", "status"], 4],
  }),
  S({
    id: "sheets-02", stage: "Cơ bản", title: "Tham chiếu và công thức nền tảng", duration: "34 phút",
    summary: "Hiểu relative, absolute và mixed reference trước khi dùng hàm phức tạp.",
    guide: [
      ["Viết công thức", "Bắt đầu bằng `=`, tham chiếu ô thay vì gõ lại số và dùng ngoặc để thể hiện thứ tự tính."],
      ["Relative reference", "`A2` thay đổi theo vị trí khi copy; dùng cho phép tính từng hàng."],
      ["Absolute/mixed reference", "`$A$2` khóa cả hàng/cột; `$A2` hoặc `A$2` chỉ khóa một chiều."],
      ["Kiểm thử copy", "Copy công thức xuống và sang ngang, chọn vài ô để xác nhận reference đổi đúng ý."],
    ],
    tip: "Dấu phân cách hàm có thể là dấu phẩy hoặc chấm phẩy tùy Locale của file; đây không phải lỗi hàm.",
    quiz: ["Reference nào khóa cả cột A và hàng 2 khi sao chép?", ["A2", "$A$2", "A$2"], 1, "Hai dấu `$` tạo absolute reference hoàn toàn."],
    practice: ["Viết công thức tính Thành tiền = Số lượng × Đơn giá × tỷ lệ thuế cố định ở H1.", "=C2*D2*(1+$H$1)", ["c2", "d2", "$h$1", "="], 4],
  }),
  S({
    id: "sheets-02a", stage: "Thực hành", title: "IF, SUMIFS và COUNTIFS", duration: "35 phút",
    summary: "Tạo logic trạng thái và tổng hợp nhiều điều kiện mà không lọc tay.",
    guide: [
      ["Viết điều kiện rõ", "Dùng IF cho một quyết định đơn giản; tránh lồng quá nhiều IF khi có thể dùng bảng tra cứu."],
      ["Tổng hợp bằng SUMIFS", "Sum range đứng trước, sau đó là từng criteria range và criterion; các range phải cùng kích thước."],
      ["Đếm bằng COUNTIFS", "Dùng các cặp range/criterion để đếm bản ghi thỏa đồng thời nhiều điều kiện."],
      ["Kiểm tra biên", "Thử dữ liệu bằng đúng ngưỡng, rỗng, ngày cuối kỳ và trạng thái sai chính tả."],
    ],
    tip: "Đừng dùng toàn cột trong hàng chục SUMIFS lớn nếu file chậm; giới hạn range hợp lý hoặc dùng Table references.",
    quiz: ["Trong SUMIFS, đối số đầu tiên là gì?", ["Sum range", "Criterion đầu tiên", "Tên sheet"], 0, "Cú pháp bắt đầu bằng vùng cần cộng."],
    practice: ["Viết SUMIFS tính doanh thu của Owner ở H2 trong tháng ở H3.", "=SUMIFS(E2:E100,B2:B100,H2,C2:C100,H3)", ["sumifs", "e2:e", "b2:b", "h2", "h3"], 4],
  }),
  S({
    id: "sheets-02b", stage: "Thực hành", title: "XLOOKUP, FILTER và xử lý lỗi", duration: "39 phút",
    summary: "Tra cứu chính xác, trả tập kết quả và không che lỗi dữ liệu.",
    sourceUrl: "https://support.google.com/docs/answer/12405947",
    guide: [
      ["XLOOKUP exact match", "Dùng `XLOOKUP(search_key, lookup_range, result_range, missing_value)`; hai range phải có kích thước tương ứng."],
      ["Chọn missing value", "Trả thông báo rõ như “Không tìm thấy mã” thay vì để người dùng hiểu nhầm ô trống."],
      ["Dùng FILTER", "FILTER trả nhiều hàng thỏa điều kiện; các condition phải cùng chiều và cùng độ dài với range."],
      ["Xử lý lỗi có chủ đích", "Chỉ dùng IFERROR sau khi đã hiểu #N/A, #REF! hoặc #VALUE!; không bọc mọi công thức bằng chuỗi rỗng."],
    ],
    tip: "XLOOKUP mặc định exact match; match_mode và search_mode chỉ thêm khi yêu cầu nghiệp vụ thật sự cần.",
    quiz: ["Nếu FILTER không có dòng nào thỏa điều kiện, kết quả mặc định là gì?", ["Ô trống", "#N/A", "0"], 1, "FILTER trả #N/A khi không tìm thấy giá trị phù hợp."],
    practice: ["Viết XLOOKUP tìm giá theo mã A2 và FILTER trả các task có Status = Done.", "=XLOOKUP(A2,D2:D20,E2:E20,\"Không tìm thấy\") / =FILTER(A2:E,E2:E=\"Done\")", ["xlookup", "a2", "d2:d20", "filter", "done"], 5],
  }),
  S({
    id: "sheets-03", stage: "Thực hành", title: "Pivot table từ dữ liệu sạch", duration: "37 phút",
    summary: "Tóm tắt dữ liệu bằng Rows, Columns, Values và Filters.",
    sourceUrl: "https://support.google.com/docs/answer/7572895",
    guide: [
      ["Kiểm nguồn", "Nguồn phải có header, một grain, không subtotal và kiểu ngày/số đúng trước khi tạo Pivot."],
      ["Tạo Pivot", "Chọn nguồn → Insert → Pivot table; ưu tiên sheet mới để không đè vùng dữ liệu."],
      ["Cấu hình trường", "Thêm Rows cho nhóm chính, Columns nếu cần chiều thứ hai, Values với SUM/COUNT phù hợp và Filters để thu hẹp."],
      ["Nhóm và refresh", "Nhóm date theo tháng/quý khi cần; sau khi nguồn thay đổi, kiểm tra range nguồn và filter values."],
    ],
    tip: "Nếu Pivot đếm thay vì cộng, cột nguồn có thể đang chứa text hoặc kiểu số không nhất quán.",
    quiz: ["Muốn tổng doanh thu theo tháng, trường Doanh thu nên nằm ở đâu?", ["Rows", "Values với SUM", "Filters duy nhất"], 1, "Values thực hiện phép tổng hợp."],
    practice: ["Mô tả Pivot tổng doanh thu theo tháng và Owner, có một filter trạng thái.", "Rows: Month · Columns: Owner · Values: SUM Revenue · Filter: Status…", ["rows", "columns", "values", "sum", "filter"], 5],
  }),
  S({
    id: "sheets-03b", stage: "Nâng cao", title: "Chart, slicer và filter views", duration: "33 phút",
    summary: "Biến phân tích thành dashboard dễ đọc mà không phá dữ liệu chung.",
    sourceUrl: "https://support.google.com/docs/answer/3540681",
    guide: [
      ["Viết câu hỏi", "Mỗi chart phải trả lời một câu hỏi; line cho xu hướng thời gian, bar cho so sánh, tránh pie có quá nhiều nhóm."],
      ["Chọn vùng dữ liệu", "Dùng bảng tóm tắt/Pivot làm nguồn chart và kiểm tra header, series, trục và định dạng số."],
      ["Thêm tương tác", "Dùng slicer khi phù hợp với chart/Pivot; dùng filter view để mỗi người lọc riêng và có thể chia sẻ view."],
      ["Giảm nhiễu", "Bỏ 3D, màu thừa và label lặp; thêm title, đơn vị và nguồn/ngày cập nhật."],
    ],
    tip: "Nếu người xem không trả lời được câu hỏi trong năm giây, chart cần đơn giản hơn hoặc title cần cụ thể hơn.",
    quiz: ["Biểu đồ phù hợp nhất để theo dõi doanh thu theo tháng là gì?", ["Line chart", "Pie chart 12 lát", "Gauge"], 0, "Line chart thể hiện xu hướng theo thời gian rõ ràng."],
    practice: ["Đặc tả dashboard hai chart và hai filter views, nêu câu hỏi mỗi chart trả lời.", "Line: xu hướng tháng… Bar: so Owner… View: My open tasks…", ["line", "bar", "filter view", "tháng", "owner"], 4],
  }),
  S({
    id: "sheets-04", stage: "Nâng cao", title: "Audit, protected ranges và bàn giao", duration: "44 phút",
    summary: "Bảo vệ công thức, kiểm lỗi và giao file có README vận hành.",
    guide: [
      ["Audit lỗi", "Tìm #N/A, #REF!, #VALUE!, ô số lưu dạng text, ngày sai locale và công thức bị lệch range."],
      ["Bảo vệ vùng", "Dùng Data → Protect sheets and ranges; chọn cảnh báo hoặc giới hạn người sửa, nhưng hiểu đây không phải biện pháp bảo mật tuyệt đối."],
      ["Viết README", "Ghi owner, mục đích, grain, nguồn, lịch cập nhật, từ điển cột, vùng nhập và vùng không được sửa."],
      ["Kiểm thử bàn giao", "Mở bằng tài khoản có quyền thấp hơn, thử nhập giá trị biên, filter và thêm dòng mới; xác nhận dashboard cập nhật."],
    ],
    tip: "Protected range kiểm soát chỉnh sửa, không ngăn người có quyền xem sao chép hoặc xuất dữ liệu.",
    quiz: ["Protected range nên được hiểu là gì?", ["Mã hóa dữ liệu", "Kiểm soát ai được sửa vùng", "Ẩn hoàn toàn dữ liệu"], 1, "Bảo vệ range không phải cơ chế mã hóa hay chống sao chép."],
    practice: ["Nộp checklist bàn giao tracker gồm audit, quyền, protected ranges, README và test dữ liệu mới.", "□ #N/A… □ Editor… □ Formula protected… □ README… □ Add row test…", ["audit", "quyền", "protect", "readme", "test"], 5],
  }),
];

const geminiSteps = [
  G({
    id: "gemini-01", stage: "Cơ bản", title: "Khả năng, giới hạn và dữ liệu an toàn", duration: "18 phút", free: true,
    summary: "Hiểu Gemini tạo nội dung xác suất, có thể sai và chịu điều kiện tài khoản.",
    sourceUrl: "https://support.google.com/gemini/answer/13594961",
    guide: [
      ["Kiểm tra tài khoản", "Xác nhận tài khoản cá nhân hay work/school, tuổi, gói AI và chính sách admin vì tính năng/giới hạn có thể khác."],
      ["Hiểu đầu ra", "Xem câu trả lời là bản nháp cần kiểm chứng, không phải nguồn sự thật hoặc quyết định cuối."],
      ["Phân loại dữ liệu", "Không đưa mật khẩu, mã thanh toán, hồ sơ sức khỏe, dữ liệu khách hàng hoặc tài liệu mật nếu chưa có quyền/chính sách phù hợp."],
      ["Kiểm tra Activity", "Đọc Gemini Apps Privacy Hub và cài đặt activity/connected apps trước khi dùng dữ liệu công việc."],
    ],
    tip: "Ẩn tên chưa chắc đã ẩn danh; ngày, chức danh và ngữ cảnh vẫn có thể nhận diện một người.",
    quiz: ["Cách đúng để dùng đầu ra Gemini trong công việc là gì?", ["Xuất bản ngay", "Xem như bản nháp và kiểm chứng", "Tin khi câu trả lời dài"], 1, "Mô hình có thể tạo thông tin sai dù văn phong tự tin."],
    practice: ["Phân loại bốn ví dụ dữ liệu thành Có thể dùng, Cần ẩn danh hoặc Không đưa vào.", "Agenda công khai: Có thể… / Danh sách khách hàng: Không…", ["có thể", "ẩn danh", "không", "khách hàng"], 3],
  }),
  G({
    id: "gemini-01b", stage: "Cơ bản", title: "Prompt có mục tiêu và bối cảnh", duration: "28 phút",
    summary: "Viết yêu cầu rõ Outcome, Context, Constraints và Output.",
    guide: [
      ["Outcome", "Mở đầu bằng kết quả cần đạt và người sẽ dùng kết quả, không bắt đầu bằng vai trò dài dòng."],
      ["Context", "Cung cấp dữ liệu nền cần thiết, giải thích thuật ngữ nội bộ và tách dữ kiện khỏi chỉ dẫn."],
      ["Constraints", "Nêu phạm vi, giọng văn, độ dài, điều không được suy đoán và yêu cầu hỏi lại khi thiếu dữ liệu."],
      ["Output", "Chỉ định cấu trúc đầu ra như bảng, checklist, JSON hoặc headings; cho một ví dụ tốt nếu định dạng khó."],
    ],
    tip: "Một ví dụ đầu ra tốt thường hiệu quả hơn nhiều tính từ như “chuyên nghiệp, hay, xuất sắc”.",
    quiz: ["Khi thiếu ngày họp quan trọng, prompt nên yêu cầu Gemini làm gì?", ["Tự chọn một ngày", "Hỏi lại", "Bỏ ngày"], 1, "Yêu cầu hỏi lại giúp ngăn mô hình tự suy đoán dữ liệu bắt buộc."],
    practice: ["Viết prompt tạo agenda có Outcome, Context, Constraints, Output và quy tắc hỏi lại.", "Outcome:… Context:… Không suy đoán… Output: bảng… Nếu thiếu ngày, hỏi…", ["outcome", "context", "không", "output", "hỏi"], 4],
  }),
  G({
    id: "gemini-01c", stage: "Cơ bản", title: "Lặp prompt và tự đánh giá", duration: "30 phút",
    summary: "Cải thiện đầu ra theo tiêu chí thay vì yêu cầu chung chung “viết hay hơn”.",
    guide: [
      ["Tạo bản nháp", "Chạy prompt ban đầu và lưu lại điểm chưa đạt; không thay toàn bộ prompt khi chưa biết lỗi nằm ở đâu."],
      ["Dùng rubric", "Đưa 3–5 tiêu chí có thể quan sát như đúng dữ kiện, đủ mục, dưới 300 từ, hành động rõ."],
      ["Yêu cầu critique", "Cho Gemini tự chỉ ra điểm chưa đạt theo rubric, nhưng bạn vẫn kiểm tra kết luận của nó."],
      ["Sửa một biến", "Mỗi vòng chỉ thay context, constraint hoặc example chính; so sánh bản trước/sau để biết điều gì tạo khác biệt."],
    ],
    tip: "Lưu prompt cùng phiên bản đầu ra tốt; chỉ lưu câu trả lời khiến quy trình khó tái tạo.",
    quiz: ["Cách sửa prompt nào giúp biết nguyên nhân chất lượng thay đổi?", ["Thay mọi thứ cùng lúc", "Mỗi vòng sửa một nhóm biến", "Chỉ thêm từ “hay hơn”"], 1, "Thay có kiểm soát giúp so sánh hiệu quả."],
    practice: ["Viết rubric bốn tiêu chí và mô tả một vòng sửa prompt dựa trên rubric.", "Đúng dữ kiện / đủ 4 mục / <300 từ / action rõ… Sửa constraint…", ["dữ kiện", "mục", "từ", "sửa", "rubric"], 4],
  }),
  G({
    id: "gemini-02", stage: "Thực hành", title: "Tải và phân tích file có kiểm soát", duration: "34 phút",
    summary: "Đặt câu hỏi bám file, giới hạn phạm vi và nhận diện hạn mức tính năng.",
    sourceUrl: "https://support.google.com/gemini/answer/14903178",
    availability: "Cần đăng nhập và từ 18 tuổi; loại file, Drive access và hạn mức phụ thuộc gói/tài khoản/admin.",
    guide: [
      ["Kiểm tra quyền", "Chỉ tải file bạn được phép xử lý; với work/school, Drive access có thể cần admin bật Connected Apps."],
      ["Đặt phạm vi nguồn", "Nói rõ “chỉ dùng file đã tải”, yêu cầu ghi “không tìm thấy” nếu file không có dữ kiện."],
      ["Chia câu hỏi", "Bắt đầu bằng cấu trúc/tóm tắt, sau đó hỏi claim, số liệu và đoạn liên quan; tránh yêu cầu khổng lồ trong một lần."],
      ["Đối chiếu file", "Mở file gốc cạnh câu trả lời, kiểm trang/section, phép tính và nội dung Gemini suy diễn thêm."],
    ],
    tip: "Gemini hiện cho phép nhiều loại file nhưng một số loại spreadsheet/code và hạn mức cao hơn cần Google AI Pro/Ultra.",
    quiz: ["Nếu file không chứa dữ kiện, bạn nên yêu cầu Gemini làm gì?", ["Tự bổ sung", "Ghi rõ không tìm thấy", "Dùng trí nhớ mô hình mà không báo"], 1, "Giới hạn nguồn phải được thể hiện rõ trong câu trả lời."],
    practice: ["Viết prompt phân tích file chỉ dùng nội dung trong file, yêu cầu dẫn section và báo thiếu.", "Chỉ dùng file… với mỗi claim ghi section… nếu không có, ghi Không tìm thấy…", ["chỉ dùng", "file", "section", "không tìm thấy"], 4],
  }),
  G({
    id: "gemini-02b", stage: "Thực hành", title: "Kiểm chứng claim và nguồn liên quan", duration: "27 phút",
    summary: "Tách claim, evidence và status trước khi dùng đầu ra.",
    sourceUrl: "https://support.google.com/gemini/",
    guide: [
      ["Tách claim", "Chuyển câu trả lời thành các mệnh đề kiểm chứng được; bỏ câu chỉ là phong cách hoặc ý kiến."],
      ["Tìm evidence", "Mở Related sources khi có, sau đó đọc chính nguồn; link xuất hiện không chứng minh toàn bộ câu trả lời."],
      ["Kiểm ngày và số", "Ưu tiên nguồn gốc/primary source, kiểm ngày cập nhật, đơn vị, mẫu số và phép tính độc lập."],
      ["Gắn status", "Đánh dấu Verified, Unsupported, Contradicted hoặc Needs expert review và loại claim chưa đạt khỏi bản bàn giao."],
    ],
    tip: "Không dùng chính câu trả lời Gemini để kiểm chứng một câu trả lời Gemini khác; phải quay về nguồn độc lập.",
    quiz: ["Một link trong Related sources chứng minh điều gì?", ["Toàn bộ câu trả lời đúng", "Chỉ cần mở và kiểm nội dung nguồn", "Gemini không thể sai"], 1, "Người dùng vẫn phải xác nhận nguồn thực sự hỗ trợ claim."],
    practice: ["Tạo bảng Claim–Evidence–Source date–Status cho ba claim.", "Claim 1… Evidence… 2026… Verified / Unsupported…", ["claim", "evidence", "source", "status", "verified"], 4],
  }),
  G({
    id: "gemini-03", stage: "Nâng cao", title: "Tạo Gem cho tác vụ lặp", duration: "32 phút",
    summary: "Đóng gói instruction, knowledge và rubric thành trợ lý dùng lại.",
    sourceUrl: "https://support.google.com/gemini/answer/15146780",
    availability: "Cần đăng nhập; tạo/chỉnh/xóa custom Gem trên Gemini web, sau đó có thể dùng ở web/mobile/Workspace side panel.",
    guide: [
      ["Chọn tác vụ lặp", "Gem phù hợp với mục tiêu và quy tắc ổn định; không tạo Gem cho một việc duy nhất hoặc quy trình đổi hàng ngày."],
      ["Viết instruction", "Nêu nhiệm vụ, người dùng, input cần hỏi, workflow, output format, tiêu chí và các lỗi phải tránh."],
      ["Thêm Knowledge", "Chỉ thêm file được phép dùng, mô tả độ ưu tiên của nguồn và quy tắc khi knowledge không đủ."],
      ["Preview và test", "Chạy ca chuẩn, ca thiếu dữ liệu và ca có yêu cầu trái instruction; sửa rồi Save/Update."],
    ],
    tip: "Gems không dùng được với Gemini Live; khả dụng của một số tính năng có thể khác theo tài khoản.",
    quiz: ["Nơi tạo và chỉnh custom Gem hiện nay là đâu?", ["Gemini web app", "Gemini Live", "Google Calendar"], 0, "Google cho phép dùng Gem trên nhiều bề mặt nhưng quản lý custom Gem trên web."],
    practice: ["Viết instruction cho Gem review báo cáo tuần, gồm input, workflow, output, rubric và lỗi tránh.", "Input: report… Workflow:… Output: Summary/Risks/Actions… Không bịa số…", ["input", "workflow", "output", "risks", "không"], 5],
  }),
  G({
    id: "gemini-03b", stage: "Nâng cao", title: "Canvas cho tài liệu và ứng dụng", duration: "36 phút",
    summary: "Đồng sáng tạo doc/app trong Canvas, chỉnh vùng chọn và kiểm tra an toàn chia sẻ.",
    sourceUrl: "https://support.google.com/gemini/answer/16047321",
    guide: [
      ["Mở Canvas", "Trên gemini.google.com chọn Add files → Canvas, mô tả rõ loại sản phẩm như doc, slide, app hoặc code."],
      ["Chỉnh có mục tiêu", "Dùng Select & ask để sửa một vùng thay vì yêu cầu viết lại toàn bộ; với app, mở Code và Console để xem lỗi."],
      ["Kiểm tra thay đổi", "Xem recent changes, test nội dung/code và không coi preview là sản phẩm đã QA."],
      ["Chia sẻ an toàn", "Đọc app info; Canvas app multi-user có thể dùng dữ liệu công khai cho người có link, không nhập dữ liệu nhạy cảm."],
    ],
    tip: "Public link của Canvas app là ranh giới bảo mật quan trọng; luôn giả định người có link có thể xem dữ liệu được app chia sẻ.",
    quiz: ["Muốn sửa một đoạn cụ thể trong Canvas, công cụ phù hợp là gì?", ["Select & ask", "Deep Research", "Delete chat"], 0, "Select & ask cho phép chọn vùng và mô tả thay đổi."],
    practice: ["Đặc tả một Canvas doc/app, ba ca test và checklist an toàn trước khi chia sẻ.", "Sản phẩm… Test 1/2/3… Không có dữ liệu nhạy cảm… review app info…", ["canvas", "test", "chia sẻ", "dữ liệu", "app"], 4],
  }),
  G({
    id: "gemini-03c", stage: "Nâng cao", title: "Deep Research có kế hoạch", duration: "38 phút",
    summary: "Chọn nguồn, duyệt kế hoạch và audit báo cáo nghiên cứu.",
    sourceUrl: "https://support.google.com/gemini/answer/15719111",
    availability: "Cần đăng nhập và từ 18 tuổi; có giới hạn số nghiên cứu, gói Pro/Ultra có hạn mức và model cao hơn.",
    guide: [
      ["Đóng khung câu hỏi", "Nêu quyết định cần hỗ trợ, phạm vi thời gian/địa lý, loại nguồn ưu tiên và tiêu chí loại trừ."],
      ["Chọn nguồn", "Deep Research mặc định dùng Google Search; Gmail/Drive chỉ khả dụng khi Workspace app được kết nối. Có thể thêm file/NotebookLM."],
      ["Duyệt kế hoạch", "Đọc research plan trước khi chạy, bổ sung nhánh bị thiếu và bỏ câu hỏi ngoài phạm vi."],
      ["Audit báo cáo", "Mở nguồn quan trọng, kiểm claim–citation, ngày, xung đột lợi ích và ghi rõ giới hạn trước khi export sang Docs."],
    ],
    tip: "Báo cáo dài không đồng nghĩa nghiên cứu tốt; chất lượng phụ thuộc câu hỏi, nguồn và audit sau cùng.",
    quiz: ["Nguồn mặc định của Deep Research là gì?", ["Google Search", "Gmail cá nhân", "Mọi file Drive"], 0, "Gmail/Drive cần Connected Apps; Search là nguồn mặc định."],
    practice: ["Viết research brief gồm câu hỏi, phạm vi, nguồn ưu tiên, loại trừ và checklist audit.", "Question… 2024–2026… ưu tiên official… loại blog affiliate… audit citation…", ["question", "phạm vi", "nguồn", "loại", "audit"], 4],
  }),
  G({
    id: "gemini-04", stage: "Nâng cao", title: "Workflow tốt nghiệp có con người kiểm soát", duration: "42 phút",
    summary: "Kết hợp Sheets, Gemini, Docs và Calendar thành quy trình có thể audit.",
    sourceUrl: "https://support.google.com/gemini/",
    guide: [
      ["Nhận brief", "Ghi owner, outcome, dữ liệu được phép dùng, deadline, rubric và người phê duyệt."],
      ["Chuẩn hóa dữ liệu", "Làm sạch số liệu ở Sheets, khóa phạm vi và ghi ngày cập nhật trước khi đưa phần cần thiết sang Gemini."],
      ["Tạo và kiểm chứng", "Dùng Gemini tạo draft, lưu prompt/version, kiểm claim–evidence rồi biên tập báo cáo trong Docs."],
      ["Phê duyệt và lưu dấu vết", "Đặt review trên Calendar, nhận approval của người chịu trách nhiệm và lưu nguồn, version cùng decision log."],
    ],
    tip: "AI rút ngắn quãng đường từ dữ liệu đến bản nháp; người phê duyệt vẫn chịu trách nhiệm với quyết định cuối.",
    quiz: ["Ai chịu trách nhiệm cuối với tài liệu được Gemini hỗ trợ?", ["Gemini", "Người kiểm tra và phê duyệt", "File nguồn"], 1, "Trách nhiệm không chuyển sang mô hình AI."],
    practice: ["Mô tả workflow tám bước có Sheets, Gemini, Docs, Calendar, checkpoint kiểm chứng và approval.", "1 Sheets clean… 2 Freeze… 3 Gemini draft… 4 Claim audit… 5 Docs… 6 Calendar review…", ["sheets", "gemini", "docs", "calendar", "audit", "approval"], 6],
  }),
];

export const HUGOSO_COURSES = {
  calendar: {
    id: "calendar",
    eyebrow: "Quản trị thời gian",
    title: "Google Calendar chuẩn công việc",
    shortTitle: "Calendar",
    description: "Từ Event/Task cơ bản đến lịch nhóm, Focus time và booking page.",
    outcome: "Tự vận hành một tuần làm việc, tổ chức họp và nhận lịch hẹn không trùng.",
    priceJoy: 320,
    duration: "4 giờ 11 phút",
    level: "Cơ bản → Nâng cao",
    icon: "calendar_month",
    color: "#4285f4",
    soft: "#eaf2ff",
    sourceUrl: GOOGLE_HELP.calendar,
    sourceLabel: "Google Calendar Help",
    steps: calendarSteps,
  },
  docs: {
    id: "docs",
    eyebrow: "Văn bản học thuật",
    title: "Google Docs & báo cáo Harvard",
    shortTitle: "Docs",
    description: "Từ cấu trúc tài liệu đến cộng tác, Harvard và xuất bản báo cáo.",
    outcome: "Hoàn thiện báo cáo có cấu trúc, trích dẫn kiểm chứng được và PDF đạt chuẩn.",
    priceJoy: 450,
    duration: "4 giờ 13 phút",
    level: "Cơ bản → Học thuật",
    icon: "description",
    color: "#1a73e8",
    soft: "#e9f2ff",
    sourceUrl: GOOGLE_HELP.docs,
    sourceLabel: "Google Docs Editors Help",
    steps: docsSteps,
  },
  sheets: {
    id: "sheets",
    eyebrow: "Dữ liệu và báo cáo",
    title: "Google Sheets chuẩn vận hành",
    shortTitle: "Sheets",
    description: "Từ dữ liệu sạch đến formula, Pivot, dashboard và bàn giao an toàn.",
    outcome: "Xây tracker có validation, công thức, phân tích và dashboard tự cập nhật.",
    priceJoy: 520,
    duration: "4 giờ 33 phút",
    level: "Cơ bản → Phân tích",
    icon: "table_chart",
    color: "#0f9d58",
    soft: "#e5f7ed",
    sourceUrl: GOOGLE_HELP.sheets,
    sourceLabel: "Google Docs Editors Help",
    steps: sheetsSteps,
  },
  gemini: {
    id: "gemini",
    eyebrow: "Năng lực AI",
    title: "Google Gemini cho học tập & công việc",
    shortTitle: "Gemini",
    description: "Từ prompt an toàn đến Gems, Canvas, Deep Research và workflow audit.",
    outcome: "Tạo quy trình AI lặp lại được, có nguồn, tiêu chí và người phê duyệt.",
    priceJoy: 390,
    duration: "4 giờ 45 phút",
    level: "Cơ bản → Workflow AI",
    icon: "auto_awesome",
    color: "#7c4dff",
    soft: "#f0ebff",
    sourceUrl: GOOGLE_HELP.gemini,
    sourceLabel: "Gemini Apps Help",
    steps: geminiSteps,
  },
};

export const HUGOSO_ALL_STEPS = HUGOSO_COURSE_ORDER.flatMap(
  (courseId) => HUGOSO_COURSES[courseId].steps,
);

export const getCourseProgress = (course, completedIds) => {
  const completed = course.steps.filter((step) => completedIds.has(`hugoso-${step.id}`)).length;
  return {
    completed,
    total: course.steps.length,
    percent: Math.round((completed / course.steps.length) * 100),
  };
};
