/**
 * Chữ của thông báo — MỘT nguồn duy nhất cho cả trình duyệt lẫn máy chủ.
 *
 * Trước đây máy chủ ghi thẳng câu tiếng Việt vào MongoDB ("Đã mở dùng thử…",
 * "Thanh toán thành công!"), nên máy đặt tiếng Hàn mở hộp thư vẫn thấy tiếng
 * Việt và không có cách nào sửa: câu đã nằm trong dữ liệu rồi.
 *
 * Giờ máy chủ chỉ lưu KHOÁ + THAM SỐ (`i18nKey` / `i18nParams` trong
 * models/InAppNotification.js), còn câu chữ dựng lúc hiển thị theo ngôn ngữ
 * người đọc đang dùng. Thông báo đẩy thì máy chủ dựng sẵn theo ngôn ngữ của
 * từng thiết bị (`NotificationSubscription.device.locale`) vì hệ điều hành vẽ
 * nó, không phải app.
 *
 * File nằm ở `shared/` chứ không phải trong bộ i18n của frontend: máy chủ cũng
 * phải đọc được để soạn push. Hai bản chép tay ở hai phía chắc chắn sẽ lệch.
 *
 * Quy ước khoá:
 *   `source.<joy_source>`  — tiêu đề cho một biến động JOY (xem
 *                            server/utils/joySources.js, khoá trùng nhau).
 *   `event.<tên>.title`    — tiêu đề của một sự kiện.
 *   `event.<tên>.message`  — câu mô tả của chính sự kiện đó.
 *
 * Tham số viết dạng {{tên}}. Giá trị là chuỗi ngày ISO sẽ tự động đổi sang
 * định dạng ngày của ngôn ngữ đang dựng.
 */

const LANGUAGES = ["vi", "en", "zh", "th", "ja", "ko", "id", "es", "fr"];

export const NOTIFICATION_TEXT = {
  vi: {
    "source.referral_referrer": "Quà giới thiệu",
    "source.referral_referee": "Quà giới thiệu",
    "source.chess_win": "Thắng trận cờ vua",
    "source.chess_match": "Trận đấu cờ vua",
    "source.companion": "Trị liệu tâm lý",
    "source.checkin": "Điểm danh nhận JOY",
    "source.gift_code": "Đổi mã quà tặng",
    "source.store_purchase": "Mua hàng",
    "source.admin_adjustment": "Điều chỉnh JOY",
    "source.companion_unlock": "Mở khoá tính năng trị liệu",
    "source.daily_challenge": "Thử thách hàng ngày",
    "source.arcade_score": "Kỷ lục mới ở sân chơi",
    "source.focus_session": "Phiên tập trung sâu",
    "source.aura_theme_rent": "Thuê giao diện tập trung",
    "source.joy_gift_sent": "Gửi JOY cho bạn bè",
    "source.joy_gift_received": "Nhận JOY từ bạn bè",
    "source.ide_learning": "Hoàn thành bài học Phát triển Web",
    "source.hugoso_course": "Mở khoá phần Năng suất số và AI",
    "source.info_bonus": "Khám phá Thông tin và phiên bản",
    "source.feature_subscription": "Trao đổi JOY mở khoá tính năng",
    "source.bio_theme_rental": "Trao đổi JOY đổi giao diện Bio",
    "source.file_compression": "Trao đổi JOY nén tệp",
    "source.admin_direct_add": "Nhận JOY từ Admin",
    "source.app_plan": "Mở gói ứng dụng",
    "source.app_plan_gift": "Tặng gói ứng dụng",
    "source.ide_course_completion": "Tốt nghiệp bộ Phát triển Web",
    "source.chat_tokens_exchange": "Đổi thêm lượt trò chuyện",
    "source.coder_exam_retake": "Mua lượt thi lại",
    "source.lifetime_unlock": "Mở khoá vĩnh viễn một chặng",
    "source.lifetime_unlock_all": "Mở khoá vĩnh viễn toàn bộ chặng",
    "source.info_read_bonus": "Đọc tin trong Thông tin và phiên bản",
    "source.ide_phase_1_completion": "Hoàn thành phần 1 · Phát triển Web",
    "source.ide_phase_2_completion": "Hoàn thành phần 2 · Phát triển Web",
    "source.ide_phase_3_completion": "Hoàn thành phần 3 · Phát triển Web",
    "source.ide_phase_4_completion": "Hoàn thành phần 4 · Phát triển Web",
    "source.ide_phase_5_completion": "Hoàn thành phần 5 · Phát triển Web",
    "source.ide_phase_6_completion": "Hoàn thành phần 6 · Phát triển Web",
    "source.ide_phase_7_completion": "Hoàn thành bộ Phát triển Web",
    "source.birthday_spin": "Vòng quay tháng sinh nhật",
    "source.credit": "Nhận JOY",
    "source.debit": "Dùng JOY",

    "event.trialStarted.title": "Đã mở dùng thử {{app}}",
    "event.trialStarted.message": "Bạn có {{days}} ngày dùng thử miễn phí, hết hạn ngày {{date}}.",
    "event.appGift.title": "{{sender}} đã tặng bạn {{item}}",
    "event.appGift.message": "Mở cửa hàng để bắt đầu dùng ngay.",
    "event.adminBonus.title": "Nhận JOY thưởng",
    "event.adminBonus.message": "Admin vừa tặng bạn {{amount}} JOY.",
    "event.adminBonusReason.title": "Nhận JOY thưởng",
    "event.adminBonusReason.message": "Admin vừa tặng bạn {{amount}} JOY. Lý do: {{reason}}",
    "event.cartCheckout.title": "Thanh toán thành công",
    "event.cartCheckout.message": "{{count}} sản phẩm · {{total}} JOY · Mã đơn: {{code}}",
    "event.productPurchase.title": "Mua hàng thành công",
    "event.productPurchase.message": "Bạn đã mua “{{product}}” với {{total}} JOY. Mã đơn: {{code}}",
    "event.wellnessNudge.title": "Lời nhắn chăm sóc tinh thần",
    "event.wellnessNudge.message": "Hôm nay có một gợi ý nhỏ dành cho bạn.",
    "event.paymentRequest.title": "Yêu cầu thanh toán",
    "event.paymentRequest.message": "Admin gửi một yêu cầu thanh toán {{amount}} ₫. Lý do: {{reason}}",
  },

  en: {
    "source.referral_referrer": "Referral reward",
    "source.referral_referee": "Referral reward",
    "source.chess_win": "Chess victory",
    "source.chess_match": "Chess match",
    "source.companion": "Therapy session",
    "source.checkin": "Daily check-in",
    "source.gift_code": "Gift code redeemed",
    "source.store_purchase": "Purchase",
    "source.admin_adjustment": "JOY adjustment",
    "source.companion_unlock": "Therapy feature unlocked",
    "source.daily_challenge": "Daily challenge",
    "source.arcade_score": "New arcade record",
    "source.focus_session": "Deep focus session",
    "source.aura_theme_rent": "Focus theme rental",
    "source.joy_gift_sent": "JOY sent to a friend",
    "source.joy_gift_received": "JOY from a friend",
    "source.ide_learning": "Web Development lesson completed",
    "source.hugoso_course": "Digital Productivity & AI unlocked",
    "source.info_bonus": "Explored Info and Version",
    "source.feature_subscription": "JOY spent to unlock a feature",
    "source.bio_theme_rental": "JOY spent on a Bio theme",
    "source.file_compression": "JOY spent on file compression",
    "source.admin_direct_add": "JOY from the admin",
    "source.app_plan": "App plan opened",
    "source.app_plan_gift": "App plan gifted",
    "source.ide_course_completion": "Web Development track completed",
    "source.chat_tokens_exchange": "Extra chat turns",
    "source.coder_exam_retake": "Exam retake purchased",
    "source.lifetime_unlock": "Lifetime access to a stage",
    "source.lifetime_unlock_all": "Lifetime access to every stage",
    "source.info_read_bonus": "Read a post in Info and Version",
    "source.ide_phase_1_completion": "Part 1 completed · Web Development",
    "source.ide_phase_2_completion": "Part 2 completed · Web Development",
    "source.ide_phase_3_completion": "Part 3 completed · Web Development",
    "source.ide_phase_4_completion": "Part 4 completed · Web Development",
    "source.ide_phase_5_completion": "Part 5 completed · Web Development",
    "source.ide_phase_6_completion": "Part 6 completed · Web Development",
    "source.ide_phase_7_completion": "Web Development track finished",
    "source.birthday_spin": "Birthday month spin",
    "source.credit": "JOY received",
    "source.debit": "JOY spent",

    "event.trialStarted.title": "{{app}} trial started",
    "event.trialStarted.message": "You have {{days}} free trial days, ending {{date}}.",
    "event.appGift.title": "{{sender}} gifted you {{item}}",
    "event.appGift.message": "Open the store to start using it.",
    "event.adminBonus.title": "Bonus JOY received",
    "event.adminBonus.message": "The admin just gave you {{amount}} JOY.",
    "event.adminBonusReason.title": "Bonus JOY received",
    "event.adminBonusReason.message": "The admin just gave you {{amount}} JOY. Reason: {{reason}}",
    "event.cartCheckout.title": "Payment complete",
    "event.cartCheckout.message": "{{count}} items · {{total}} JOY · Order: {{code}}",
    "event.productPurchase.title": "Purchase complete",
    "event.productPurchase.message": "You bought “{{product}}” for {{total}} JOY. Order: {{code}}",
    "event.wellnessNudge.title": "A wellbeing nudge",
    "event.wellnessNudge.message": "There is a small suggestion waiting for you today.",
    "event.paymentRequest.title": "Payment request",
    "event.paymentRequest.message": "The admin sent a payment request for {{amount}} ₫. Reason: {{reason}}",
  },

  zh: {
    "source.referral_referrer": "邀请奖励",
    "source.referral_referee": "邀请奖励",
    "source.chess_win": "国际象棋获胜",
    "source.chess_match": "国际象棋对局",
    "source.companion": "心理疗愈",
    "source.checkin": "每日签到",
    "source.gift_code": "兑换礼品码",
    "source.store_purchase": "购买",
    "source.admin_adjustment": "JOY 调整",
    "source.companion_unlock": "解锁疗愈功能",
    "source.daily_challenge": "每日挑战",
    "source.arcade_score": "游艺厅新纪录",
    "source.focus_session": "深度专注时段",
    "source.aura_theme_rent": "租用专注主题",
    "source.joy_gift_sent": "赠送 JOY 给朋友",
    "source.joy_gift_received": "收到朋友的 JOY",
    "source.ide_learning": "完成 Web 开发课程",
    "source.hugoso_course": "解锁数字效率与 AI",
    "source.info_bonus": "浏览系统信息与版本",
    "source.feature_subscription": "用 JOY 解锁功能",
    "source.bio_theme_rental": "用 JOY 更换 Bio 主题",
    "source.file_compression": "用 JOY 压缩文件",
    "source.admin_direct_add": "管理员赠送 JOY",
    "source.app_plan": "开通应用套餐",
    "source.app_plan_gift": "赠送应用套餐",
    "source.ide_course_completion": "完成 Web 开发全课程",
    "source.chat_tokens_exchange": "兑换更多对话次数",
    "source.coder_exam_retake": "购买重考次数",
    "source.lifetime_unlock": "永久解锁一个阶段",
    "source.lifetime_unlock_all": "永久解锁全部阶段",
    "source.info_read_bonus": "阅读系统信息与版本",
    "source.ide_phase_1_completion": "完成第 1 部分 · Web 开发",
    "source.ide_phase_2_completion": "完成第 2 部分 · Web 开发",
    "source.ide_phase_3_completion": "完成第 3 部分 · Web 开发",
    "source.ide_phase_4_completion": "完成第 4 部分 · Web 开发",
    "source.ide_phase_5_completion": "完成第 5 部分 · Web 开发",
    "source.ide_phase_6_completion": "完成第 6 部分 · Web 开发",
    "source.ide_phase_7_completion": "完成 Web 开发全部内容",
    "source.birthday_spin": "生日月转盘",
    "source.credit": "获得 JOY",
    "source.debit": "使用 JOY",

    "event.trialStarted.title": "已开始 {{app}} 试用",
    "event.trialStarted.message": "你有 {{days}} 天免费试用，到期日 {{date}}。",
    "event.appGift.title": "{{sender}} 送了你 {{item}}",
    "event.appGift.message": "打开商店即可开始使用。",
    "event.adminBonus.title": "收到奖励 JOY",
    "event.adminBonus.message": "管理员刚刚赠送你 {{amount}} JOY。",
    "event.adminBonusReason.title": "收到奖励 JOY",
    "event.adminBonusReason.message": "管理员刚刚赠送你 {{amount}} JOY。原因：{{reason}}",
    "event.cartCheckout.title": "支付成功",
    "event.cartCheckout.message": "{{count}} 件商品 · {{total}} JOY · 订单号：{{code}}",
    "event.productPurchase.title": "购买成功",
    "event.productPurchase.message": "你以 {{total}} JOY 购买了“{{product}}”。订单号：{{code}}",
    "event.wellnessNudge.title": "心理关怀提醒",
    "event.wellnessNudge.message": "今天有一个小建议等着你。",
    "event.paymentRequest.title": "付款请求",
    "event.paymentRequest.message": "管理员发来一笔 {{amount}} ₫ 的付款请求。原因：{{reason}}",
  },

  th: {
    "source.referral_referrer": "รางวัลแนะนำเพื่อน",
    "source.referral_referee": "รางวัลแนะนำเพื่อน",
    "source.chess_win": "ชนะหมากรุก",
    "source.chess_match": "แมตช์หมากรุก",
    "source.companion": "การบำบัดจิตใจ",
    "source.checkin": "เช็คอินประจำวัน",
    "source.gift_code": "แลกโค้ดของขวัญ",
    "source.store_purchase": "การซื้อ",
    "source.admin_adjustment": "ปรับยอด JOY",
    "source.companion_unlock": "ปลดล็อกฟีเจอร์บำบัด",
    "source.daily_challenge": "ภารกิจประจำวัน",
    "source.arcade_score": "สถิติใหม่ในลานเล่น",
    "source.focus_session": "ช่วงสมาธิเข้มข้น",
    "source.aura_theme_rent": "เช่าธีมสมาธิ",
    "source.joy_gift_sent": "ส่ง JOY ให้เพื่อน",
    "source.joy_gift_received": "รับ JOY จากเพื่อน",
    "source.ide_learning": "เรียนจบบทเรียนพัฒนาเว็บ",
    "source.hugoso_course": "ปลดล็อกประสิทธิภาพดิจิทัลและ AI",
    "source.info_bonus": "สำรวจข้อมูลและเวอร์ชัน",
    "source.feature_subscription": "ใช้ JOY ปลดล็อกฟีเจอร์",
    "source.bio_theme_rental": "ใช้ JOY เปลี่ยนธีม Bio",
    "source.file_compression": "ใช้ JOY บีบอัดไฟล์",
    "source.admin_direct_add": "รับ JOY จากผู้ดูแล",
    "source.app_plan": "เปิดแพ็กเกจแอป",
    "source.app_plan_gift": "มอบแพ็กเกจแอป",
    "source.ide_course_completion": "จบหลักสูตรพัฒนาเว็บ",
    "source.chat_tokens_exchange": "แลกจำนวนแชทเพิ่ม",
    "source.coder_exam_retake": "ซื้อสิทธิ์สอบซ่อม",
    "source.lifetime_unlock": "ปลดล็อกถาวรหนึ่งช่วง",
    "source.lifetime_unlock_all": "ปลดล็อกถาวรทุกช่วง",
    "source.info_read_bonus": "อ่านข่าวในข้อมูลและเวอร์ชัน",
    "source.ide_phase_1_completion": "จบส่วนที่ 1 · พัฒนาเว็บ",
    "source.ide_phase_2_completion": "จบส่วนที่ 2 · พัฒนาเว็บ",
    "source.ide_phase_3_completion": "จบส่วนที่ 3 · พัฒนาเว็บ",
    "source.ide_phase_4_completion": "จบส่วนที่ 4 · พัฒนาเว็บ",
    "source.ide_phase_5_completion": "จบส่วนที่ 5 · พัฒนาเว็บ",
    "source.ide_phase_6_completion": "จบส่วนที่ 6 · พัฒนาเว็บ",
    "source.ide_phase_7_completion": "จบชุดพัฒนาเว็บทั้งหมด",
    "source.birthday_spin": "วงล้อเดือนเกิด",
    "source.credit": "ได้รับ JOY",
    "source.debit": "ใช้ JOY",

    "event.trialStarted.title": "เริ่มทดลองใช้ {{app}} แล้ว",
    "event.trialStarted.message": "คุณมีเวลาทดลองใช้ฟรี {{days}} วัน สิ้นสุด {{date}}",
    "event.appGift.title": "{{sender}} มอบ {{item}} ให้คุณ",
    "event.appGift.message": "เปิดร้านค้าเพื่อเริ่มใช้งานได้เลย",
    "event.adminBonus.title": "ได้รับ JOY พิเศษ",
    "event.adminBonus.message": "ผู้ดูแลเพิ่งมอบ {{amount}} JOY ให้คุณ",
    "event.adminBonusReason.title": "ได้รับ JOY พิเศษ",
    "event.adminBonusReason.message": "ผู้ดูแลเพิ่งมอบ {{amount}} JOY ให้คุณ เหตุผล: {{reason}}",
    "event.cartCheckout.title": "ชำระเงินสำเร็จ",
    "event.cartCheckout.message": "{{count}} รายการ · {{total}} JOY · เลขที่สั่งซื้อ: {{code}}",
    "event.productPurchase.title": "ซื้อสำเร็จ",
    "event.productPurchase.message": "คุณซื้อ “{{product}}” ด้วย {{total}} JOY เลขที่สั่งซื้อ: {{code}}",
    "event.wellnessNudge.title": "ข้อความดูแลใจ",
    "event.wellnessNudge.message": "วันนี้มีคำแนะนำเล็ก ๆ รอคุณอยู่",
    "event.paymentRequest.title": "คำขอชำระเงิน",
    "event.paymentRequest.message": "ผู้ดูแลส่งคำขอชำระเงิน {{amount}} ₫ เหตุผล: {{reason}}",
  },

  ja: {
    "source.referral_referrer": "紹介特典",
    "source.referral_referee": "紹介特典",
    "source.chess_win": "チェス勝利",
    "source.chess_match": "チェス対局",
    "source.companion": "こころのケア",
    "source.checkin": "毎日のチェックイン",
    "source.gift_code": "ギフトコード引き換え",
    "source.store_purchase": "購入",
    "source.admin_adjustment": "JOY調整",
    "source.companion_unlock": "ケア機能の解放",
    "source.daily_challenge": "デイリーチャレンジ",
    "source.arcade_score": "遊技場の新記録",
    "source.focus_session": "集中セッション",
    "source.aura_theme_rent": "集中テーマのレンタル",
    "source.joy_gift_sent": "友だちへJOYを送信",
    "source.joy_gift_received": "友だちからJOYを受取",
    "source.ide_learning": "Web開発レッスン修了",
    "source.hugoso_course": "デジタル生産性とAIを解放",
    "source.info_bonus": "情報とバージョンを閲覧",
    "source.feature_subscription": "JOYで機能を解放",
    "source.bio_theme_rental": "JOYでBioのテーマを変更",
    "source.file_compression": "JOYでファイル圧縮",
    "source.admin_direct_add": "管理者からのJOY",
    "source.app_plan": "アプリプラン開始",
    "source.app_plan_gift": "アプリプランを贈る",
    "source.ide_course_completion": "Web開発コース修了",
    "source.chat_tokens_exchange": "チャット回数の追加",
    "source.coder_exam_retake": "再試験の購入",
    "source.lifetime_unlock": "1章を永久解放",
    "source.lifetime_unlock_all": "全章を永久解放",
    "source.info_read_bonus": "情報とバージョンを読了",
    "source.ide_phase_1_completion": "第1部 修了 · Web開発",
    "source.ide_phase_2_completion": "第2部 修了 · Web開発",
    "source.ide_phase_3_completion": "第3部 修了 · Web開発",
    "source.ide_phase_4_completion": "第4部 修了 · Web開発",
    "source.ide_phase_5_completion": "第5部 修了 · Web開発",
    "source.ide_phase_6_completion": "第6部 修了 · Web開発",
    "source.ide_phase_7_completion": "Web開発をすべて修了",
    "source.birthday_spin": "誕生月ルーレット",
    "source.credit": "JOY獲得",
    "source.debit": "JOY利用",

    "event.trialStarted.title": "{{app}}の体験を開始しました",
    "event.trialStarted.message": "無料体験は{{days}}日間、{{date}}までです。",
    "event.appGift.title": "{{sender}}さんが{{item}}を贈りました",
    "event.appGift.message": "ストアを開くとすぐに使えます。",
    "event.adminBonus.title": "ボーナスJOYを受け取りました",
    "event.adminBonus.message": "管理者から{{amount}} JOYが贈られました。",
    "event.adminBonusReason.title": "ボーナスJOYを受け取りました",
    "event.adminBonusReason.message": "管理者から{{amount}} JOYが贈られました。理由：{{reason}}",
    "event.cartCheckout.title": "支払いが完了しました",
    "event.cartCheckout.message": "{{count}}点 · {{total}} JOY · 注文番号：{{code}}",
    "event.productPurchase.title": "購入が完了しました",
    "event.productPurchase.message": "「{{product}}」を{{total}} JOYで購入しました。注文番号：{{code}}",
    "event.wellnessNudge.title": "こころのケアのお知らせ",
    "event.wellnessNudge.message": "今日はあなたに小さな提案があります。",
    "event.paymentRequest.title": "支払いリクエスト",
    "event.paymentRequest.message": "管理者から{{amount}} ₫の支払いリクエストが届きました。理由：{{reason}}",
  },

  ko: {
    "source.referral_referrer": "추천 보상",
    "source.referral_referee": "추천 보상",
    "source.chess_win": "체스 승리",
    "source.chess_match": "체스 대국",
    "source.companion": "마음 돌봄",
    "source.checkin": "일일 출석",
    "source.gift_code": "선물 코드 사용",
    "source.store_purchase": "구매",
    "source.admin_adjustment": "JOY 조정",
    "source.companion_unlock": "돌봄 기능 해제",
    "source.daily_challenge": "일일 도전",
    "source.arcade_score": "오락실 신기록",
    "source.focus_session": "몰입 세션",
    "source.aura_theme_rent": "몰입 테마 대여",
    "source.joy_gift_sent": "친구에게 JOY 전송",
    "source.joy_gift_received": "친구에게 받은 JOY",
    "source.ide_learning": "웹 개발 수업 완료",
    "source.hugoso_course": "디지털 생산성과 AI 해제",
    "source.info_bonus": "정보와 버전 살펴보기",
    "source.feature_subscription": "JOY로 기능 해제",
    "source.bio_theme_rental": "JOY로 Bio 테마 변경",
    "source.file_compression": "JOY로 파일 압축",
    "source.admin_direct_add": "관리자가 준 JOY",
    "source.app_plan": "앱 이용권 개시",
    "source.app_plan_gift": "앱 이용권 선물",
    "source.ide_course_completion": "웹 개발 과정 수료",
    "source.chat_tokens_exchange": "대화 횟수 추가",
    "source.coder_exam_retake": "재시험 구매",
    "source.lifetime_unlock": "한 단계 평생 해제",
    "source.lifetime_unlock_all": "모든 단계 평생 해제",
    "source.info_read_bonus": "정보와 버전 읽기",
    "source.ide_phase_1_completion": "1부 완료 · 웹 개발",
    "source.ide_phase_2_completion": "2부 완료 · 웹 개발",
    "source.ide_phase_3_completion": "3부 완료 · 웹 개발",
    "source.ide_phase_4_completion": "4부 완료 · 웹 개발",
    "source.ide_phase_5_completion": "5부 완료 · 웹 개발",
    "source.ide_phase_6_completion": "6부 완료 · 웹 개발",
    "source.ide_phase_7_completion": "웹 개발 전 과정 완료",
    "source.birthday_spin": "생일의 달 룰렛",
    "source.credit": "JOY 획득",
    "source.debit": "JOY 사용",

    "event.trialStarted.title": "{{app}} 체험을 시작했어요",
    "event.trialStarted.message": "무료 체험 {{days}}일, {{date}}에 종료됩니다.",
    "event.appGift.title": "{{sender}}님이 {{item}}을(를) 선물했어요",
    "event.appGift.message": "스토어를 열면 바로 사용할 수 있어요.",
    "event.adminBonus.title": "보너스 JOY 도착",
    "event.adminBonus.message": "관리자가 방금 {{amount}} JOY를 보냈어요.",
    "event.adminBonusReason.title": "보너스 JOY 도착",
    "event.adminBonusReason.message": "관리자가 방금 {{amount}} JOY를 보냈어요. 사유: {{reason}}",
    "event.cartCheckout.title": "결제가 완료되었어요",
    "event.cartCheckout.message": "{{count}}개 · {{total}} JOY · 주문번호: {{code}}",
    "event.productPurchase.title": "구매가 완료되었어요",
    "event.productPurchase.message": "“{{product}}”을(를) {{total}} JOY로 구매했어요. 주문번호: {{code}}",
    "event.wellnessNudge.title": "마음 돌봄 알림",
    "event.wellnessNudge.message": "오늘 당신을 위한 작은 제안이 있어요.",
    "event.paymentRequest.title": "결제 요청",
    "event.paymentRequest.message": "관리자가 {{amount}} ₫ 결제를 요청했어요. 사유: {{reason}}",
  },

  id: {
    "source.referral_referrer": "Hadiah referal",
    "source.referral_referee": "Hadiah referal",
    "source.chess_win": "Menang catur",
    "source.chess_match": "Pertandingan catur",
    "source.companion": "Sesi terapi",
    "source.checkin": "Absen harian",
    "source.gift_code": "Kode hadiah ditukar",
    "source.store_purchase": "Pembelian",
    "source.admin_adjustment": "Penyesuaian JOY",
    "source.companion_unlock": "Fitur terapi terbuka",
    "source.daily_challenge": "Tantangan harian",
    "source.arcade_score": "Rekor baru di arena",
    "source.focus_session": "Sesi fokus mendalam",
    "source.aura_theme_rent": "Sewa tema fokus",
    "source.joy_gift_sent": "Kirim JOY ke teman",
    "source.joy_gift_received": "JOY dari teman",
    "source.ide_learning": "Materi Pengembangan Web selesai",
    "source.hugoso_course": "Produktivitas Digital dan AI terbuka",
    "source.info_bonus": "Menjelajah Info dan Versi",
    "source.feature_subscription": "JOY untuk membuka fitur",
    "source.bio_theme_rental": "JOY untuk tema Bio",
    "source.file_compression": "JOY untuk kompresi berkas",
    "source.admin_direct_add": "JOY dari admin",
    "source.app_plan": "Paket aplikasi dibuka",
    "source.app_plan_gift": "Paket aplikasi dihadiahkan",
    "source.ide_course_completion": "Lulus jalur Pengembangan Web",
    "source.chat_tokens_exchange": "Tambah giliran obrolan",
    "source.coder_exam_retake": "Beli kesempatan ujian ulang",
    "source.lifetime_unlock": "Akses selamanya satu tahap",
    "source.lifetime_unlock_all": "Akses selamanya semua tahap",
    "source.info_read_bonus": "Membaca Info dan Versi",
    "source.ide_phase_1_completion": "Bagian 1 selesai · Pengembangan Web",
    "source.ide_phase_2_completion": "Bagian 2 selesai · Pengembangan Web",
    "source.ide_phase_3_completion": "Bagian 3 selesai · Pengembangan Web",
    "source.ide_phase_4_completion": "Bagian 4 selesai · Pengembangan Web",
    "source.ide_phase_5_completion": "Bagian 5 selesai · Pengembangan Web",
    "source.ide_phase_6_completion": "Bagian 6 selesai · Pengembangan Web",
    "source.ide_phase_7_completion": "Seluruh Pengembangan Web selesai",
    "source.birthday_spin": "Putaran bulan ulang tahun",
    "source.credit": "JOY diterima",
    "source.debit": "JOY terpakai",

    "event.trialStarted.title": "Uji coba {{app}} dimulai",
    "event.trialStarted.message": "Kamu punya {{days}} hari uji coba gratis, berakhir {{date}}.",
    "event.appGift.title": "{{sender}} menghadiahkan {{item}}",
    "event.appGift.message": "Buka toko untuk mulai memakainya.",
    "event.adminBonus.title": "JOY bonus diterima",
    "event.adminBonus.message": "Admin baru saja memberimu {{amount}} JOY.",
    "event.adminBonusReason.title": "JOY bonus diterima",
    "event.adminBonusReason.message": "Admin baru saja memberimu {{amount}} JOY. Alasan: {{reason}}",
    "event.cartCheckout.title": "Pembayaran berhasil",
    "event.cartCheckout.message": "{{count}} produk · {{total}} JOY · Kode pesanan: {{code}}",
    "event.productPurchase.title": "Pembelian berhasil",
    "event.productPurchase.message": "Kamu membeli “{{product}}” seharga {{total}} JOY. Kode pesanan: {{code}}",
    "event.wellnessNudge.title": "Pengingat kesejahteraan",
    "event.wellnessNudge.message": "Ada saran kecil untukmu hari ini.",
    "event.paymentRequest.title": "Permintaan pembayaran",
    "event.paymentRequest.message": "Admin mengirim permintaan pembayaran {{amount}} ₫. Alasan: {{reason}}",
  },

  es: {
    "source.referral_referrer": "Recompensa por invitar",
    "source.referral_referee": "Recompensa por invitación",
    "source.chess_win": "Victoria en ajedrez",
    "source.chess_match": "Partida de ajedrez",
    "source.companion": "Sesión de acompañamiento",
    "source.checkin": "Registro diario",
    "source.gift_code": "Código de regalo canjeado",
    "source.store_purchase": "Compra",
    "source.admin_adjustment": "Ajuste de JOY",
    "source.companion_unlock": "Función de terapia desbloqueada",
    "source.daily_challenge": "Reto diario",
    "source.arcade_score": "Nuevo récord en los recreativos",
    "source.focus_session": "Sesión de concentración",
    "source.aura_theme_rent": "Alquiler de tema de enfoque",
    "source.joy_gift_sent": "JOY enviado a un amigo",
    "source.joy_gift_received": "JOY de un amigo",
    "source.ide_learning": "Lección de desarrollo web completada",
    "source.hugoso_course": "Productividad digital e IA desbloqueadas",
    "source.info_bonus": "Exploraste Info y versión",
    "source.feature_subscription": "JOY para desbloquear una función",
    "source.bio_theme_rental": "JOY para un tema de Bio",
    "source.file_compression": "JOY para comprimir archivos",
    "source.admin_direct_add": "JOY del administrador",
    "source.app_plan": "Plan de app activado",
    "source.app_plan_gift": "Plan de app regalado",
    "source.ide_course_completion": "Ruta de desarrollo web completada",
    "source.chat_tokens_exchange": "Turnos de chat adicionales",
    "source.coder_exam_retake": "Repetición de examen comprada",
    "source.lifetime_unlock": "Acceso de por vida a una etapa",
    "source.lifetime_unlock_all": "Acceso de por vida a todas las etapas",
    "source.info_read_bonus": "Leíste Info y versión",
    "source.ide_phase_1_completion": "Parte 1 completada · Desarrollo web",
    "source.ide_phase_2_completion": "Parte 2 completada · Desarrollo web",
    "source.ide_phase_3_completion": "Parte 3 completada · Desarrollo web",
    "source.ide_phase_4_completion": "Parte 4 completada · Desarrollo web",
    "source.ide_phase_5_completion": "Parte 5 completada · Desarrollo web",
    "source.ide_phase_6_completion": "Parte 6 completada · Desarrollo web",
    "source.ide_phase_7_completion": "Desarrollo web terminado",
    "source.birthday_spin": "Ruleta del mes de cumpleaños",
    "source.credit": "JOY recibido",
    "source.debit": "JOY gastado",

    "event.trialStarted.title": "Prueba de {{app}} iniciada",
    "event.trialStarted.message": "Tienes {{days}} días de prueba gratis; termina el {{date}}.",
    "event.appGift.title": "{{sender}} te regaló {{item}}",
    "event.appGift.message": "Abre la tienda para empezar a usarlo.",
    "event.adminBonus.title": "JOY de regalo recibido",
    "event.adminBonus.message": "El administrador acaba de darte {{amount}} JOY.",
    "event.adminBonusReason.title": "JOY de regalo recibido",
    "event.adminBonusReason.message": "El administrador acaba de darte {{amount}} JOY. Motivo: {{reason}}",
    "event.cartCheckout.title": "Pago completado",
    "event.cartCheckout.message": "{{count}} productos · {{total}} JOY · Pedido: {{code}}",
    "event.productPurchase.title": "Compra completada",
    "event.productPurchase.message": "Compraste «{{product}}» por {{total}} JOY. Pedido: {{code}}",
    "event.wellnessNudge.title": "Recordatorio de bienestar",
    "event.wellnessNudge.message": "Hoy hay una pequeña sugerencia para ti.",
    "event.paymentRequest.title": "Solicitud de pago",
    "event.paymentRequest.message": "El administrador envió una solicitud de pago de {{amount}} ₫. Motivo: {{reason}}",
  },

  fr: {
    "source.referral_referrer": "Récompense de parrainage",
    "source.referral_referee": "Récompense de parrainage",
    "source.chess_win": "Victoire aux échecs",
    "source.chess_match": "Partie d’échecs",
    "source.companion": "Séance d’accompagnement",
    "source.checkin": "Pointage quotidien",
    "source.gift_code": "Code cadeau utilisé",
    "source.store_purchase": "Achat",
    "source.admin_adjustment": "Ajustement de JOY",
    "source.companion_unlock": "Fonction de thérapie débloquée",
    "source.daily_challenge": "Défi du jour",
    "source.arcade_score": "Nouveau record en salle de jeux",
    "source.focus_session": "Séance de concentration",
    "source.aura_theme_rent": "Location d’un thème de concentration",
    "source.joy_gift_sent": "JOY envoyé à un ami",
    "source.joy_gift_received": "JOY reçu d’un ami",
    "source.ide_learning": "Leçon de développement web terminée",
    "source.hugoso_course": "Productivité numérique et IA débloquées",
    "source.info_bonus": "Exploration d’Infos et version",
    "source.feature_subscription": "JOY pour débloquer une fonction",
    "source.bio_theme_rental": "JOY pour un thème Bio",
    "source.file_compression": "JOY pour compresser un fichier",
    "source.admin_direct_add": "JOY de l’administrateur",
    "source.app_plan": "Forfait d’application ouvert",
    "source.app_plan_gift": "Forfait d’application offert",
    "source.ide_course_completion": "Parcours de développement web terminé",
    "source.chat_tokens_exchange": "Tours de discussion supplémentaires",
    "source.coder_exam_retake": "Nouvelle tentative d’examen achetée",
    "source.lifetime_unlock": "Accès à vie à une étape",
    "source.lifetime_unlock_all": "Accès à vie à toutes les étapes",
    "source.info_read_bonus": "Lecture d’Infos et version",
    "source.ide_phase_1_completion": "Partie 1 terminée · Développement web",
    "source.ide_phase_2_completion": "Partie 2 terminée · Développement web",
    "source.ide_phase_3_completion": "Partie 3 terminée · Développement web",
    "source.ide_phase_4_completion": "Partie 4 terminée · Développement web",
    "source.ide_phase_5_completion": "Partie 5 terminée · Développement web",
    "source.ide_phase_6_completion": "Partie 6 terminée · Développement web",
    "source.ide_phase_7_completion": "Développement web entièrement terminé",
    "source.birthday_spin": "Roue du mois d’anniversaire",
    "source.credit": "JOY reçus",
    "source.debit": "JOY dépensés",

    "event.trialStarted.title": "Essai de {{app}} lancé",
    "event.trialStarted.message": "Vous avez {{days}} jours d’essai gratuit, jusqu’au {{date}}.",
    "event.appGift.title": "{{sender}} vous a offert {{item}}",
    "event.appGift.message": "Ouvrez la boutique pour commencer à l’utiliser.",
    "event.adminBonus.title": "JOY bonus reçus",
    "event.adminBonus.message": "L’administrateur vient de vous offrir {{amount}} JOY.",
    "event.adminBonusReason.title": "JOY bonus reçus",
    "event.adminBonusReason.message": "L’administrateur vient de vous offrir {{amount}} JOY. Motif : {{reason}}",
    "event.cartCheckout.title": "Paiement effectué",
    "event.cartCheckout.message": "{{count}} produits · {{total}} JOY · Commande : {{code}}",
    "event.productPurchase.title": "Achat effectué",
    "event.productPurchase.message": "Vous avez acheté « {{product}} » pour {{total}} JOY. Commande : {{code}}",
    "event.wellnessNudge.title": "Rappel bien-être",
    "event.wellnessNudge.message": "Une petite suggestion vous attend aujourd’hui.",
    "event.paymentRequest.title": "Demande de paiement",
    "event.paymentRequest.message": "L’administrateur a envoyé une demande de paiement de {{amount}} ₫. Motif : {{reason}}",
  },
};

/** Mã ngôn ngữ hợp lệ, chấp nhận cả dạng "ko-KR" hoặc "zh_CN". */
export function notificationLanguage(input) {
  const code = String(input || "").toLowerCase().replace("_", "-").split("-")[0];
  return LANGUAGES.includes(code) ? code : "vi";
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}(T|$)/;

/** Thay {{tham số}}; giá trị là ngày ISO thì đổi sang định dạng của ngôn ngữ. */
function interpolate(template, params, language) {
  return template.replace(/\{\{(\w+)\}\}/g, (whole, name) => {
    const value = params?.[name];
    if (value === undefined || value === null) return whole;
    if (typeof value === "string" && ISO_DATE.test(value)) {
      const date = new Date(value);
      if (!Number.isNaN(date.getTime())) return date.toLocaleDateString(language);
    }
    if (typeof value === "number") return value.toLocaleString(language);
    return String(value);
  });
}

/**
 * Dựng tiêu đề + nội dung của một thông báo.
 *
 * Trả `null` khi không có khoá (thông báo cũ, hoặc tin admin tự viết) — nơi gọi
 * cứ dùng tiếp `title`/`message` đã lưu trong DB.
 */
export function renderNotification(key, params = {}, language = "vi") {
  if (!key) return null;
  const lang = notificationLanguage(language);
  const dict = NOTIFICATION_TEXT[lang];
  const fallback = NOTIFICATION_TEXT.vi;
  const pick = (name) => dict[name] ?? fallback[name] ?? null;

  const title = pick(`${key}.title`) ?? pick(key);
  if (!title) return null;
  const message = pick(`${key}.message`);

  return {
    title: interpolate(title, params, lang),
    // `note` là chữ người dùng tự viết (lời nhắn kèm quà, lý do của admin).
    // Không dịch được và cũng không nên dịch — nó thay hẳn câu mặc định.
    message: params?.note
      ? String(params.note)
      : (message ? interpolate(message, params, lang) : ""),
  };
}

export const NOTIFICATION_LANGUAGES = LANGUAGES;
